// Code generated by ent, DO NOT EDIT.

package resourcemapping

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the resourcemapping type in the database.
	Label = "resource_mapping"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldResourceTypeID holds the string denoting the resource_type_id field in the database.
	FieldResourceTypeID = "resource_type_id"
	// FieldStorageKind holds the string denoting the storage_kind field in the database.
	FieldStorageKind = "storage_kind"
	// FieldTableName holds the string denoting the table_name field in the database.
	FieldTableName = "table_name"
	// FieldIDField holds the string denoting the id_field field in the database.
	FieldIDField = "id_field"
	// FieldSpaceField holds the string denoting the space_field field in the database.
	FieldSpaceField = "space_field"
	// FieldGroupField holds the string denoting the group_field field in the database.
	FieldGroupField = "group_field"
	// FieldOwnerMemberField holds the string denoting the owner_member_field field in the database.
	FieldOwnerMemberField = "owner_member_field"
	// FieldVisibilityField holds the string denoting the visibility_field field in the database.
	FieldVisibilityField = "visibility_field"
	// FieldMetadataField holds the string denoting the metadata_field field in the database.
	FieldMetadataField = "metadata_field"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldMetadata holds the string denoting the metadata field in the database.
	FieldMetadata = "metadata"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the resourcemapping in the database.
	Table = "resource_mappings"
)

// Columns holds all SQL columns for resourcemapping fields.
var Columns = []string{
	FieldID,
	FieldResourceTypeID,
	FieldStorageKind,
	FieldTableName,
	FieldIDField,
	FieldSpaceField,
	FieldGroupField,
	FieldOwnerMemberField,
	FieldVisibilityField,
	FieldMetadataField,
	FieldStatus,
	FieldMetadata,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// ResourceTypeIDValidator is a validator for the "resource_type_id" field. It is called by the builders before save.
	ResourceTypeIDValidator func(string) error
	// DefaultStorageKind holds the default value on creation for the "storage_kind" field.
	DefaultStorageKind string
	// DefaultIDField holds the default value on creation for the "id_field" field.
	DefaultIDField string
	// DefaultSpaceField holds the default value on creation for the "space_field" field.
	DefaultSpaceField string
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(string) error
)

// OrderOption defines the ordering options for the ResourceMapping queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByResourceTypeID orders the results by the resource_type_id field.
func ByResourceTypeID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResourceTypeID, opts...).ToFunc()
}

// ByStorageKind orders the results by the storage_kind field.
func ByStorageKind(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStorageKind, opts...).ToFunc()
}

// ByTableName orders the results by the table_name field.
func ByTableName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTableName, opts...).ToFunc()
}

// ByIDField orders the results by the id_field field.
func ByIDField(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIDField, opts...).ToFunc()
}

// BySpaceField orders the results by the space_field field.
func BySpaceField(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSpaceField, opts...).ToFunc()
}

// ByGroupField orders the results by the group_field field.
func ByGroupField(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGroupField, opts...).ToFunc()
}

// ByOwnerMemberField orders the results by the owner_member_field field.
func ByOwnerMemberField(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOwnerMemberField, opts...).ToFunc()
}

// ByVisibilityField orders the results by the visibility_field field.
func ByVisibilityField(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVisibilityField, opts...).ToFunc()
}

// ByMetadataField orders the results by the metadata_field field.
func ByMetadataField(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMetadataField, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
