// Code generated by ent, DO NOT EDIT.

package pluginadminmenu

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/plystra/plystra/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.PluginAdminMenu {
	return predicate.PluginAdminMenu(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.PluginAdminMenu {
	return predicate.PluginAdminMenu(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.PluginAdminMenu {
	return predicate.PluginAdminMenu(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.PluginAdminMenu {
	return predicate.PluginAdminMenu(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.PluginAdminMenu {
	return predicate.PluginAdminMenu(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.PluginAdminMenu {
	return predicate.PluginAdminMenu(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.PluginAdminMenu {
	return predicate.PluginAdminMenu(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.PluginAdminMenu {
	return predicate.PluginAdminMenu(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.PluginAdminMenu {
	return predicate.PluginAdminMenu(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.PluginAdminMenu {
	return predicate.PluginAdminMenu(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.PluginAdminMenu {
	return predicate.PluginAdminMenu(sql.FieldContainsFold(FieldID, id))
}

// PluginID applies equality check predicate on the "plugin_id" field. It's identical to PluginIDEQ.
func PluginID(v string) predicate.PluginAdminMenu {
	return predicate.PluginAdminMenu(sql.FieldEQ(FieldPluginID, v))
}

// Path applies equality check predicate on the "path" field. It's identical to PathEQ.
func Path(v string) predicate.PluginAdminMenu {
	return predicate.PluginAdminMenu(sql.FieldEQ(FieldPath, v))
}

// Icon applies equality check predicate on the "icon" field. It's identical to IconEQ.
func Icon(v string) predicate.PluginAdminMenu {
	return predicate.PluginAdminMenu(sql.FieldEQ(FieldIcon, v))
}

// RequiredPermission applies equality check predicate on the "required_permission" field. It's identical to RequiredPermissionEQ.
func RequiredPermission(v string) predicate.PluginAdminMenu {
	return predicate.PluginAdminMenu(sql.FieldEQ(FieldRequiredPermission, v))
}

// SortOrder applies equality check predicate on the "sort_order" field. It's identical to SortOrderEQ.
func SortOrder(v int) predicate.PluginAdminMenu {
	return predicate.PluginAdminMenu(sql.FieldEQ(FieldSortOrder, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.PluginAdminMenu {
	return predicate.PluginAdminMenu(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.PluginAdminMenu {
	return predicate.PluginAdminMenu(sql.FieldEQ(FieldUpdatedAt, v))
}

// PluginIDEQ applies the EQ predicate on the "plugin_id" field.
func PluginIDEQ(v string) predicate.PluginAdminMenu {
	return predicate.PluginAdminMenu(sql.FieldEQ(FieldPluginID, v))
}

// PluginIDNEQ applies the NEQ predicate on the "plugin_id" field.
func PluginIDNEQ(v string) predicate.PluginAdminMenu {
	return predicate.PluginAdminMenu(sql.FieldNEQ(FieldPluginID, v))
}

// PluginIDIn applies the In predicate on the "plugin_id" field.
func PluginIDIn(vs ...string) predicate.PluginAdminMenu {
	return predicate.PluginAdminMenu(sql.FieldIn(FieldPluginID, vs...))
}

// PluginIDNotIn applies the NotIn predicate on the "plugin_id" field.
func PluginIDNotIn(vs ...string) predicate.PluginAdminMenu {
	return predicate.PluginAdminMenu(sql.FieldNotIn(FieldPluginID, vs...))
}

// PluginIDGT applies the GT predicate on the "plugin_id" field.
func PluginIDGT(v string) predicate.PluginAdminMenu {
	return predicate.PluginAdminMenu(sql.FieldGT(FieldPluginID, v))
}

// PluginIDGTE applies the GTE predicate on the "plugin_id" field.
func PluginIDGTE(v string) predicate.PluginAdminMenu {
	return predicate.PluginAdminMenu(sql.FieldGTE(FieldPluginID, v))
}

// PluginIDLT applies the LT predicate on the "plugin_id" field.
func PluginIDLT(v string) predicate.PluginAdminMenu {
	return predicate.PluginAdminMenu(sql.FieldLT(FieldPluginID, v))
}

// PluginIDLTE applies the LTE predicate on the "plugin_id" field.
func PluginIDLTE(v string) predicate.PluginAdminMenu {
	return predicate.PluginAdminMenu(sql.FieldLTE(FieldPluginID, v))
}

// PluginIDContains applies the Contains predicate on the "plugin_id" field.
func PluginIDContains(v string) predicate.PluginAdminMenu {
	return predicate.PluginAdminMenu(sql.FieldContains(FieldPluginID, v))
}

// PluginIDHasPrefix applies the HasPrefix predicate on the "plugin_id" field.
func PluginIDHasPrefix(v string) predicate.PluginAdminMenu {
	return predicate.PluginAdminMenu(sql.FieldHasPrefix(FieldPluginID, v))
}

// PluginIDHasSuffix applies the HasSuffix predicate on the "plugin_id" field.
func PluginIDHasSuffix(v string) predicate.PluginAdminMenu {
	return predicate.PluginAdminMenu(sql.FieldHasSuffix(FieldPluginID, v))
}

// PluginIDEqualFold applies the EqualFold predicate on the "plugin_id" field.
func PluginIDEqualFold(v string) predicate.PluginAdminMenu {
	return predicate.PluginAdminMenu(sql.FieldEqualFold(FieldPluginID, v))
}

// PluginIDContainsFold applies the ContainsFold predicate on the "plugin_id" field.
func PluginIDContainsFold(v string) predicate.PluginAdminMenu {
	return predicate.PluginAdminMenu(sql.FieldContainsFold(FieldPluginID, v))
}

// LabelEQ applies the EQ predicate on the "label" field.
func LabelEQ(v string) predicate.PluginAdminMenu {
	return predicate.PluginAdminMenu(sql.FieldEQ(FieldLabel, v))
}

// LabelNEQ applies the NEQ predicate on the "label" field.
func LabelNEQ(v string) predicate.PluginAdminMenu {
	return predicate.PluginAdminMenu(sql.FieldNEQ(FieldLabel, v))
}

// LabelIn applies the In predicate on the "label" field.
func LabelIn(vs ...string) predicate.PluginAdminMenu {
	return predicate.PluginAdminMenu(sql.FieldIn(FieldLabel, vs...))
}

// LabelNotIn applies the NotIn predicate on the "label" field.
func LabelNotIn(vs ...string) predicate.PluginAdminMenu {
	return predicate.PluginAdminMenu(sql.FieldNotIn(FieldLabel, vs...))
}

// LabelGT applies the GT predicate on the "label" field.
func LabelGT(v string) predicate.PluginAdminMenu {
	return predicate.PluginAdminMenu(sql.FieldGT(FieldLabel, v))
}

// LabelGTE applies the GTE predicate on the "label" field.
func LabelGTE(v string) predicate.PluginAdminMenu {
	return predicate.PluginAdminMenu(sql.FieldGTE(FieldLabel, v))
}

// LabelLT applies the LT predicate on the "label" field.
func LabelLT(v string) predicate.PluginAdminMenu {
	return predicate.PluginAdminMenu(sql.FieldLT(FieldLabel, v))
}

// LabelLTE applies the LTE predicate on the "label" field.
func LabelLTE(v string) predicate.PluginAdminMenu {
	return predicate.PluginAdminMenu(sql.FieldLTE(FieldLabel, v))
}

// LabelContains applies the Contains predicate on the "label" field.
func LabelContains(v string) predicate.PluginAdminMenu {
	return predicate.PluginAdminMenu(sql.FieldContains(FieldLabel, v))
}

// LabelHasPrefix applies the HasPrefix predicate on the "label" field.
func LabelHasPrefix(v string) predicate.PluginAdminMenu {
	return predicate.PluginAdminMenu(sql.FieldHasPrefix(FieldLabel, v))
}

// LabelHasSuffix applies the HasSuffix predicate on the "label" field.
func LabelHasSuffix(v string) predicate.PluginAdminMenu {
	return predicate.PluginAdminMenu(sql.FieldHasSuffix(FieldLabel, v))
}

// LabelEqualFold applies the EqualFold predicate on the "label" field.
func LabelEqualFold(v string) predicate.PluginAdminMenu {
	return predicate.PluginAdminMenu(sql.FieldEqualFold(FieldLabel, v))
}

// LabelContainsFold applies the ContainsFold predicate on the "label" field.
func LabelContainsFold(v string) predicate.PluginAdminMenu {
	return predicate.PluginAdminMenu(sql.FieldContainsFold(FieldLabel, v))
}

// PathEQ applies the EQ predicate on the "path" field.
func PathEQ(v string) predicate.PluginAdminMenu {
	return predicate.PluginAdminMenu(sql.FieldEQ(FieldPath, v))
}

// PathNEQ applies the NEQ predicate on the "path" field.
func PathNEQ(v string) predicate.PluginAdminMenu {
	return predicate.PluginAdminMenu(sql.FieldNEQ(FieldPath, v))
}

// PathIn applies the In predicate on the "path" field.
func PathIn(vs ...string) predicate.PluginAdminMenu {
	return predicate.PluginAdminMenu(sql.FieldIn(FieldPath, vs...))
}

// PathNotIn applies the NotIn predicate on the "path" field.
func PathNotIn(vs ...string) predicate.PluginAdminMenu {
	return predicate.PluginAdminMenu(sql.FieldNotIn(FieldPath, vs...))
}

// PathGT applies the GT predicate on the "path" field.
func PathGT(v string) predicate.PluginAdminMenu {
	return predicate.PluginAdminMenu(sql.FieldGT(FieldPath, v))
}

// PathGTE applies the GTE predicate on the "path" field.
func PathGTE(v string) predicate.PluginAdminMenu {
	return predicate.PluginAdminMenu(sql.FieldGTE(FieldPath, v))
}

// PathLT applies the LT predicate on the "path" field.
func PathLT(v string) predicate.PluginAdminMenu {
	return predicate.PluginAdminMenu(sql.FieldLT(FieldPath, v))
}

// PathLTE applies the LTE predicate on the "path" field.
func PathLTE(v string) predicate.PluginAdminMenu {
	return predicate.PluginAdminMenu(sql.FieldLTE(FieldPath, v))
}

// PathContains applies the Contains predicate on the "path" field.
func PathContains(v string) predicate.PluginAdminMenu {
	return predicate.PluginAdminMenu(sql.FieldContains(FieldPath, v))
}

// PathHasPrefix applies the HasPrefix predicate on the "path" field.
func PathHasPrefix(v string) predicate.PluginAdminMenu {
	return predicate.PluginAdminMenu(sql.FieldHasPrefix(FieldPath, v))
}

// PathHasSuffix applies the HasSuffix predicate on the "path" field.
func PathHasSuffix(v string) predicate.PluginAdminMenu {
	return predicate.PluginAdminMenu(sql.FieldHasSuffix(FieldPath, v))
}

// PathEqualFold applies the EqualFold predicate on the "path" field.
func PathEqualFold(v string) predicate.PluginAdminMenu {
	return predicate.PluginAdminMenu(sql.FieldEqualFold(FieldPath, v))
}

// PathContainsFold applies the ContainsFold predicate on the "path" field.
func PathContainsFold(v string) predicate.PluginAdminMenu {
	return predicate.PluginAdminMenu(sql.FieldContainsFold(FieldPath, v))
}

// IconEQ applies the EQ predicate on the "icon" field.
func IconEQ(v string) predicate.PluginAdminMenu {
	return predicate.PluginAdminMenu(sql.FieldEQ(FieldIcon, v))
}

// IconNEQ applies the NEQ predicate on the "icon" field.
func IconNEQ(v string) predicate.PluginAdminMenu {
	return predicate.PluginAdminMenu(sql.FieldNEQ(FieldIcon, v))
}

// IconIn applies the In predicate on the "icon" field.
func IconIn(vs ...string) predicate.PluginAdminMenu {
	return predicate.PluginAdminMenu(sql.FieldIn(FieldIcon, vs...))
}

// IconNotIn applies the NotIn predicate on the "icon" field.
func IconNotIn(vs ...string) predicate.PluginAdminMenu {
	return predicate.PluginAdminMenu(sql.FieldNotIn(FieldIcon, vs...))
}

// IconGT applies the GT predicate on the "icon" field.
func IconGT(v string) predicate.PluginAdminMenu {
	return predicate.PluginAdminMenu(sql.FieldGT(FieldIcon, v))
}

// IconGTE applies the GTE predicate on the "icon" field.
func IconGTE(v string) predicate.PluginAdminMenu {
	return predicate.PluginAdminMenu(sql.FieldGTE(FieldIcon, v))
}

// IconLT applies the LT predicate on the "icon" field.
func IconLT(v string) predicate.PluginAdminMenu {
	return predicate.PluginAdminMenu(sql.FieldLT(FieldIcon, v))
}

// IconLTE applies the LTE predicate on the "icon" field.
func IconLTE(v string) predicate.PluginAdminMenu {
	return predicate.PluginAdminMenu(sql.FieldLTE(FieldIcon, v))
}

// IconContains applies the Contains predicate on the "icon" field.
func IconContains(v string) predicate.PluginAdminMenu {
	return predicate.PluginAdminMenu(sql.FieldContains(FieldIcon, v))
}

// IconHasPrefix applies the HasPrefix predicate on the "icon" field.
func IconHasPrefix(v string) predicate.PluginAdminMenu {
	return predicate.PluginAdminMenu(sql.FieldHasPrefix(FieldIcon, v))
}

// IconHasSuffix applies the HasSuffix predicate on the "icon" field.
func IconHasSuffix(v string) predicate.PluginAdminMenu {
	return predicate.PluginAdminMenu(sql.FieldHasSuffix(FieldIcon, v))
}

// IconIsNil applies the IsNil predicate on the "icon" field.
func IconIsNil() predicate.PluginAdminMenu {
	return predicate.PluginAdminMenu(sql.FieldIsNull(FieldIcon))
}

// IconNotNil applies the NotNil predicate on the "icon" field.
func IconNotNil() predicate.PluginAdminMenu {
	return predicate.PluginAdminMenu(sql.FieldNotNull(FieldIcon))
}

// IconEqualFold applies the EqualFold predicate on the "icon" field.
func IconEqualFold(v string) predicate.PluginAdminMenu {
	return predicate.PluginAdminMenu(sql.FieldEqualFold(FieldIcon, v))
}

// IconContainsFold applies the ContainsFold predicate on the "icon" field.
func IconContainsFold(v string) predicate.PluginAdminMenu {
	return predicate.PluginAdminMenu(sql.FieldContainsFold(FieldIcon, v))
}

// RequiredPermissionEQ applies the EQ predicate on the "required_permission" field.
func RequiredPermissionEQ(v string) predicate.PluginAdminMenu {
	return predicate.PluginAdminMenu(sql.FieldEQ(FieldRequiredPermission, v))
}

// RequiredPermissionNEQ applies the NEQ predicate on the "required_permission" field.
func RequiredPermissionNEQ(v string) predicate.PluginAdminMenu {
	return predicate.PluginAdminMenu(sql.FieldNEQ(FieldRequiredPermission, v))
}

// RequiredPermissionIn applies the In predicate on the "required_permission" field.
func RequiredPermissionIn(vs ...string) predicate.PluginAdminMenu {
	return predicate.PluginAdminMenu(sql.FieldIn(FieldRequiredPermission, vs...))
}

// RequiredPermissionNotIn applies the NotIn predicate on the "required_permission" field.
func RequiredPermissionNotIn(vs ...string) predicate.PluginAdminMenu {
	return predicate.PluginAdminMenu(sql.FieldNotIn(FieldRequiredPermission, vs...))
}

// RequiredPermissionGT applies the GT predicate on the "required_permission" field.
func RequiredPermissionGT(v string) predicate.PluginAdminMenu {
	return predicate.PluginAdminMenu(sql.FieldGT(FieldRequiredPermission, v))
}

// RequiredPermissionGTE applies the GTE predicate on the "required_permission" field.
func RequiredPermissionGTE(v string) predicate.PluginAdminMenu {
	return predicate.PluginAdminMenu(sql.FieldGTE(FieldRequiredPermission, v))
}

// RequiredPermissionLT applies the LT predicate on the "required_permission" field.
func RequiredPermissionLT(v string) predicate.PluginAdminMenu {
	return predicate.PluginAdminMenu(sql.FieldLT(FieldRequiredPermission, v))
}

// RequiredPermissionLTE applies the LTE predicate on the "required_permission" field.
func RequiredPermissionLTE(v string) predicate.PluginAdminMenu {
	return predicate.PluginAdminMenu(sql.FieldLTE(FieldRequiredPermission, v))
}

// RequiredPermissionContains applies the Contains predicate on the "required_permission" field.
func RequiredPermissionContains(v string) predicate.PluginAdminMenu {
	return predicate.PluginAdminMenu(sql.FieldContains(FieldRequiredPermission, v))
}

// RequiredPermissionHasPrefix applies the HasPrefix predicate on the "required_permission" field.
func RequiredPermissionHasPrefix(v string) predicate.PluginAdminMenu {
	return predicate.PluginAdminMenu(sql.FieldHasPrefix(FieldRequiredPermission, v))
}

// RequiredPermissionHasSuffix applies the HasSuffix predicate on the "required_permission" field.
func RequiredPermissionHasSuffix(v string) predicate.PluginAdminMenu {
	return predicate.PluginAdminMenu(sql.FieldHasSuffix(FieldRequiredPermission, v))
}

// RequiredPermissionIsNil applies the IsNil predicate on the "required_permission" field.
func RequiredPermissionIsNil() predicate.PluginAdminMenu {
	return predicate.PluginAdminMenu(sql.FieldIsNull(FieldRequiredPermission))
}

// RequiredPermissionNotNil applies the NotNil predicate on the "required_permission" field.
func RequiredPermissionNotNil() predicate.PluginAdminMenu {
	return predicate.PluginAdminMenu(sql.FieldNotNull(FieldRequiredPermission))
}

// RequiredPermissionEqualFold applies the EqualFold predicate on the "required_permission" field.
func RequiredPermissionEqualFold(v string) predicate.PluginAdminMenu {
	return predicate.PluginAdminMenu(sql.FieldEqualFold(FieldRequiredPermission, v))
}

// RequiredPermissionContainsFold applies the ContainsFold predicate on the "required_permission" field.
func RequiredPermissionContainsFold(v string) predicate.PluginAdminMenu {
	return predicate.PluginAdminMenu(sql.FieldContainsFold(FieldRequiredPermission, v))
}

// SortOrderEQ applies the EQ predicate on the "sort_order" field.
func SortOrderEQ(v int) predicate.PluginAdminMenu {
	return predicate.PluginAdminMenu(sql.FieldEQ(FieldSortOrder, v))
}

// SortOrderNEQ applies the NEQ predicate on the "sort_order" field.
func SortOrderNEQ(v int) predicate.PluginAdminMenu {
	return predicate.PluginAdminMenu(sql.FieldNEQ(FieldSortOrder, v))
}

// SortOrderIn applies the In predicate on the "sort_order" field.
func SortOrderIn(vs ...int) predicate.PluginAdminMenu {
	return predicate.PluginAdminMenu(sql.FieldIn(FieldSortOrder, vs...))
}

// SortOrderNotIn applies the NotIn predicate on the "sort_order" field.
func SortOrderNotIn(vs ...int) predicate.PluginAdminMenu {
	return predicate.PluginAdminMenu(sql.FieldNotIn(FieldSortOrder, vs...))
}

// SortOrderGT applies the GT predicate on the "sort_order" field.
func SortOrderGT(v int) predicate.PluginAdminMenu {
	return predicate.PluginAdminMenu(sql.FieldGT(FieldSortOrder, v))
}

// SortOrderGTE applies the GTE predicate on the "sort_order" field.
func SortOrderGTE(v int) predicate.PluginAdminMenu {
	return predicate.PluginAdminMenu(sql.FieldGTE(FieldSortOrder, v))
}

// SortOrderLT applies the LT predicate on the "sort_order" field.
func SortOrderLT(v int) predicate.PluginAdminMenu {
	return predicate.PluginAdminMenu(sql.FieldLT(FieldSortOrder, v))
}

// SortOrderLTE applies the LTE predicate on the "sort_order" field.
func SortOrderLTE(v int) predicate.PluginAdminMenu {
	return predicate.PluginAdminMenu(sql.FieldLTE(FieldSortOrder, v))
}

// MetadataIsNil applies the IsNil predicate on the "metadata" field.
func MetadataIsNil() predicate.PluginAdminMenu {
	return predicate.PluginAdminMenu(sql.FieldIsNull(FieldMetadata))
}

// MetadataNotNil applies the NotNil predicate on the "metadata" field.
func MetadataNotNil() predicate.PluginAdminMenu {
	return predicate.PluginAdminMenu(sql.FieldNotNull(FieldMetadata))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.PluginAdminMenu {
	return predicate.PluginAdminMenu(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.PluginAdminMenu {
	return predicate.PluginAdminMenu(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.PluginAdminMenu {
	return predicate.PluginAdminMenu(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.PluginAdminMenu {
	return predicate.PluginAdminMenu(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.PluginAdminMenu {
	return predicate.PluginAdminMenu(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.PluginAdminMenu {
	return predicate.PluginAdminMenu(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.PluginAdminMenu {
	return predicate.PluginAdminMenu(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.PluginAdminMenu {
	return predicate.PluginAdminMenu(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.PluginAdminMenu {
	return predicate.PluginAdminMenu(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.PluginAdminMenu {
	return predicate.PluginAdminMenu(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.PluginAdminMenu {
	return predicate.PluginAdminMenu(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.PluginAdminMenu {
	return predicate.PluginAdminMenu(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.PluginAdminMenu {
	return predicate.PluginAdminMenu(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.PluginAdminMenu {
	return predicate.PluginAdminMenu(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.PluginAdminMenu {
	return predicate.PluginAdminMenu(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.PluginAdminMenu {
	return predicate.PluginAdminMenu(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.PluginAdminMenu) predicate.PluginAdminMenu {
	return predicate.PluginAdminMenu(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.PluginAdminMenu) predicate.PluginAdminMenu {
	return predicate.PluginAdminMenu(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.PluginAdminMenu) predicate.PluginAdminMenu {
	return predicate.PluginAdminMenu(sql.NotPredicates(p))
}
