// Code generated by ent, DO NOT EDIT.

package authchallenge

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/plystra/plystra/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldContainsFold(FieldID, id))
}

// Purpose applies equality check predicate on the "purpose" field. It's identical to PurposeEQ.
func Purpose(v string) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldEQ(FieldPurpose, v))
}

// DeliveryMethod applies equality check predicate on the "delivery_method" field. It's identical to DeliveryMethodEQ.
func DeliveryMethod(v string) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldEQ(FieldDeliveryMethod, v))
}

// Email applies equality check predicate on the "email" field. It's identical to EmailEQ.
func Email(v string) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldEQ(FieldEmail, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v string) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldEQ(FieldUserID, v))
}

// SecretHash applies equality check predicate on the "secret_hash" field. It's identical to SecretHashEQ.
func SecretHash(v string) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldEQ(FieldSecretHash, v))
}

// CodeHash applies equality check predicate on the "code_hash" field. It's identical to CodeHashEQ.
func CodeHash(v string) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldEQ(FieldCodeHash, v))
}

// RedirectURL applies equality check predicate on the "redirect_url" field. It's identical to RedirectURLEQ.
func RedirectURL(v string) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldEQ(FieldRedirectURL, v))
}

// RequestIP applies equality check predicate on the "request_ip" field. It's identical to RequestIPEQ.
func RequestIP(v string) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldEQ(FieldRequestIP, v))
}

// RequestUserAgent applies equality check predicate on the "request_user_agent" field. It's identical to RequestUserAgentEQ.
func RequestUserAgent(v string) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldEQ(FieldRequestUserAgent, v))
}

// Attempts applies equality check predicate on the "attempts" field. It's identical to AttemptsEQ.
func Attempts(v int) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldEQ(FieldAttempts, v))
}

// MaxAttempts applies equality check predicate on the "max_attempts" field. It's identical to MaxAttemptsEQ.
func MaxAttempts(v int) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldEQ(FieldMaxAttempts, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldEQ(FieldStatus, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldEQ(FieldExpiresAt, v))
}

// ConsumedAt applies equality check predicate on the "consumed_at" field. It's identical to ConsumedAtEQ.
func ConsumedAt(v time.Time) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldEQ(FieldConsumedAt, v))
}

// RevokedAt applies equality check predicate on the "revoked_at" field. It's identical to RevokedAtEQ.
func RevokedAt(v time.Time) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldEQ(FieldRevokedAt, v))
}

// EmailProviderMessageID applies equality check predicate on the "email_provider_message_id" field. It's identical to EmailProviderMessageIDEQ.
func EmailProviderMessageID(v string) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldEQ(FieldEmailProviderMessageID, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldEQ(FieldDeletedAt, v))
}

// PurposeEQ applies the EQ predicate on the "purpose" field.
func PurposeEQ(v string) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldEQ(FieldPurpose, v))
}

// PurposeNEQ applies the NEQ predicate on the "purpose" field.
func PurposeNEQ(v string) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldNEQ(FieldPurpose, v))
}

// PurposeIn applies the In predicate on the "purpose" field.
func PurposeIn(vs ...string) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldIn(FieldPurpose, vs...))
}

// PurposeNotIn applies the NotIn predicate on the "purpose" field.
func PurposeNotIn(vs ...string) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldNotIn(FieldPurpose, vs...))
}

// PurposeGT applies the GT predicate on the "purpose" field.
func PurposeGT(v string) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldGT(FieldPurpose, v))
}

// PurposeGTE applies the GTE predicate on the "purpose" field.
func PurposeGTE(v string) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldGTE(FieldPurpose, v))
}

// PurposeLT applies the LT predicate on the "purpose" field.
func PurposeLT(v string) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldLT(FieldPurpose, v))
}

// PurposeLTE applies the LTE predicate on the "purpose" field.
func PurposeLTE(v string) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldLTE(FieldPurpose, v))
}

// PurposeContains applies the Contains predicate on the "purpose" field.
func PurposeContains(v string) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldContains(FieldPurpose, v))
}

// PurposeHasPrefix applies the HasPrefix predicate on the "purpose" field.
func PurposeHasPrefix(v string) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldHasPrefix(FieldPurpose, v))
}

// PurposeHasSuffix applies the HasSuffix predicate on the "purpose" field.
func PurposeHasSuffix(v string) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldHasSuffix(FieldPurpose, v))
}

// PurposeEqualFold applies the EqualFold predicate on the "purpose" field.
func PurposeEqualFold(v string) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldEqualFold(FieldPurpose, v))
}

// PurposeContainsFold applies the ContainsFold predicate on the "purpose" field.
func PurposeContainsFold(v string) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldContainsFold(FieldPurpose, v))
}

// DeliveryMethodEQ applies the EQ predicate on the "delivery_method" field.
func DeliveryMethodEQ(v string) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldEQ(FieldDeliveryMethod, v))
}

// DeliveryMethodNEQ applies the NEQ predicate on the "delivery_method" field.
func DeliveryMethodNEQ(v string) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldNEQ(FieldDeliveryMethod, v))
}

// DeliveryMethodIn applies the In predicate on the "delivery_method" field.
func DeliveryMethodIn(vs ...string) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldIn(FieldDeliveryMethod, vs...))
}

// DeliveryMethodNotIn applies the NotIn predicate on the "delivery_method" field.
func DeliveryMethodNotIn(vs ...string) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldNotIn(FieldDeliveryMethod, vs...))
}

// DeliveryMethodGT applies the GT predicate on the "delivery_method" field.
func DeliveryMethodGT(v string) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldGT(FieldDeliveryMethod, v))
}

// DeliveryMethodGTE applies the GTE predicate on the "delivery_method" field.
func DeliveryMethodGTE(v string) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldGTE(FieldDeliveryMethod, v))
}

// DeliveryMethodLT applies the LT predicate on the "delivery_method" field.
func DeliveryMethodLT(v string) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldLT(FieldDeliveryMethod, v))
}

// DeliveryMethodLTE applies the LTE predicate on the "delivery_method" field.
func DeliveryMethodLTE(v string) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldLTE(FieldDeliveryMethod, v))
}

// DeliveryMethodContains applies the Contains predicate on the "delivery_method" field.
func DeliveryMethodContains(v string) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldContains(FieldDeliveryMethod, v))
}

// DeliveryMethodHasPrefix applies the HasPrefix predicate on the "delivery_method" field.
func DeliveryMethodHasPrefix(v string) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldHasPrefix(FieldDeliveryMethod, v))
}

// DeliveryMethodHasSuffix applies the HasSuffix predicate on the "delivery_method" field.
func DeliveryMethodHasSuffix(v string) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldHasSuffix(FieldDeliveryMethod, v))
}

// DeliveryMethodEqualFold applies the EqualFold predicate on the "delivery_method" field.
func DeliveryMethodEqualFold(v string) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldEqualFold(FieldDeliveryMethod, v))
}

// DeliveryMethodContainsFold applies the ContainsFold predicate on the "delivery_method" field.
func DeliveryMethodContainsFold(v string) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldContainsFold(FieldDeliveryMethod, v))
}

// EmailEQ applies the EQ predicate on the "email" field.
func EmailEQ(v string) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldEQ(FieldEmail, v))
}

// EmailNEQ applies the NEQ predicate on the "email" field.
func EmailNEQ(v string) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldNEQ(FieldEmail, v))
}

// EmailIn applies the In predicate on the "email" field.
func EmailIn(vs ...string) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldIn(FieldEmail, vs...))
}

// EmailNotIn applies the NotIn predicate on the "email" field.
func EmailNotIn(vs ...string) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldNotIn(FieldEmail, vs...))
}

// EmailGT applies the GT predicate on the "email" field.
func EmailGT(v string) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldGT(FieldEmail, v))
}

// EmailGTE applies the GTE predicate on the "email" field.
func EmailGTE(v string) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldGTE(FieldEmail, v))
}

// EmailLT applies the LT predicate on the "email" field.
func EmailLT(v string) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldLT(FieldEmail, v))
}

// EmailLTE applies the LTE predicate on the "email" field.
func EmailLTE(v string) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldLTE(FieldEmail, v))
}

// EmailContains applies the Contains predicate on the "email" field.
func EmailContains(v string) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldContains(FieldEmail, v))
}

// EmailHasPrefix applies the HasPrefix predicate on the "email" field.
func EmailHasPrefix(v string) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldHasPrefix(FieldEmail, v))
}

// EmailHasSuffix applies the HasSuffix predicate on the "email" field.
func EmailHasSuffix(v string) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldHasSuffix(FieldEmail, v))
}

// EmailEqualFold applies the EqualFold predicate on the "email" field.
func EmailEqualFold(v string) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldEqualFold(FieldEmail, v))
}

// EmailContainsFold applies the ContainsFold predicate on the "email" field.
func EmailContainsFold(v string) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldContainsFold(FieldEmail, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v string) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v string) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...string) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...string) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v string) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v string) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v string) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v string) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldLTE(FieldUserID, v))
}

// UserIDContains applies the Contains predicate on the "user_id" field.
func UserIDContains(v string) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldContains(FieldUserID, v))
}

// UserIDHasPrefix applies the HasPrefix predicate on the "user_id" field.
func UserIDHasPrefix(v string) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldHasPrefix(FieldUserID, v))
}

// UserIDHasSuffix applies the HasSuffix predicate on the "user_id" field.
func UserIDHasSuffix(v string) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldHasSuffix(FieldUserID, v))
}

// UserIDIsNil applies the IsNil predicate on the "user_id" field.
func UserIDIsNil() predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldIsNull(FieldUserID))
}

// UserIDNotNil applies the NotNil predicate on the "user_id" field.
func UserIDNotNil() predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldNotNull(FieldUserID))
}

// UserIDEqualFold applies the EqualFold predicate on the "user_id" field.
func UserIDEqualFold(v string) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldEqualFold(FieldUserID, v))
}

// UserIDContainsFold applies the ContainsFold predicate on the "user_id" field.
func UserIDContainsFold(v string) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldContainsFold(FieldUserID, v))
}

// SecretHashEQ applies the EQ predicate on the "secret_hash" field.
func SecretHashEQ(v string) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldEQ(FieldSecretHash, v))
}

// SecretHashNEQ applies the NEQ predicate on the "secret_hash" field.
func SecretHashNEQ(v string) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldNEQ(FieldSecretHash, v))
}

// SecretHashIn applies the In predicate on the "secret_hash" field.
func SecretHashIn(vs ...string) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldIn(FieldSecretHash, vs...))
}

// SecretHashNotIn applies the NotIn predicate on the "secret_hash" field.
func SecretHashNotIn(vs ...string) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldNotIn(FieldSecretHash, vs...))
}

// SecretHashGT applies the GT predicate on the "secret_hash" field.
func SecretHashGT(v string) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldGT(FieldSecretHash, v))
}

// SecretHashGTE applies the GTE predicate on the "secret_hash" field.
func SecretHashGTE(v string) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldGTE(FieldSecretHash, v))
}

// SecretHashLT applies the LT predicate on the "secret_hash" field.
func SecretHashLT(v string) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldLT(FieldSecretHash, v))
}

// SecretHashLTE applies the LTE predicate on the "secret_hash" field.
func SecretHashLTE(v string) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldLTE(FieldSecretHash, v))
}

// SecretHashContains applies the Contains predicate on the "secret_hash" field.
func SecretHashContains(v string) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldContains(FieldSecretHash, v))
}

// SecretHashHasPrefix applies the HasPrefix predicate on the "secret_hash" field.
func SecretHashHasPrefix(v string) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldHasPrefix(FieldSecretHash, v))
}

// SecretHashHasSuffix applies the HasSuffix predicate on the "secret_hash" field.
func SecretHashHasSuffix(v string) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldHasSuffix(FieldSecretHash, v))
}

// SecretHashEqualFold applies the EqualFold predicate on the "secret_hash" field.
func SecretHashEqualFold(v string) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldEqualFold(FieldSecretHash, v))
}

// SecretHashContainsFold applies the ContainsFold predicate on the "secret_hash" field.
func SecretHashContainsFold(v string) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldContainsFold(FieldSecretHash, v))
}

// CodeHashEQ applies the EQ predicate on the "code_hash" field.
func CodeHashEQ(v string) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldEQ(FieldCodeHash, v))
}

// CodeHashNEQ applies the NEQ predicate on the "code_hash" field.
func CodeHashNEQ(v string) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldNEQ(FieldCodeHash, v))
}

// CodeHashIn applies the In predicate on the "code_hash" field.
func CodeHashIn(vs ...string) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldIn(FieldCodeHash, vs...))
}

// CodeHashNotIn applies the NotIn predicate on the "code_hash" field.
func CodeHashNotIn(vs ...string) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldNotIn(FieldCodeHash, vs...))
}

// CodeHashGT applies the GT predicate on the "code_hash" field.
func CodeHashGT(v string) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldGT(FieldCodeHash, v))
}

// CodeHashGTE applies the GTE predicate on the "code_hash" field.
func CodeHashGTE(v string) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldGTE(FieldCodeHash, v))
}

// CodeHashLT applies the LT predicate on the "code_hash" field.
func CodeHashLT(v string) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldLT(FieldCodeHash, v))
}

// CodeHashLTE applies the LTE predicate on the "code_hash" field.
func CodeHashLTE(v string) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldLTE(FieldCodeHash, v))
}

// CodeHashContains applies the Contains predicate on the "code_hash" field.
func CodeHashContains(v string) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldContains(FieldCodeHash, v))
}

// CodeHashHasPrefix applies the HasPrefix predicate on the "code_hash" field.
func CodeHashHasPrefix(v string) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldHasPrefix(FieldCodeHash, v))
}

// CodeHashHasSuffix applies the HasSuffix predicate on the "code_hash" field.
func CodeHashHasSuffix(v string) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldHasSuffix(FieldCodeHash, v))
}

// CodeHashIsNil applies the IsNil predicate on the "code_hash" field.
func CodeHashIsNil() predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldIsNull(FieldCodeHash))
}

// CodeHashNotNil applies the NotNil predicate on the "code_hash" field.
func CodeHashNotNil() predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldNotNull(FieldCodeHash))
}

// CodeHashEqualFold applies the EqualFold predicate on the "code_hash" field.
func CodeHashEqualFold(v string) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldEqualFold(FieldCodeHash, v))
}

// CodeHashContainsFold applies the ContainsFold predicate on the "code_hash" field.
func CodeHashContainsFold(v string) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldContainsFold(FieldCodeHash, v))
}

// RedirectURLEQ applies the EQ predicate on the "redirect_url" field.
func RedirectURLEQ(v string) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldEQ(FieldRedirectURL, v))
}

// RedirectURLNEQ applies the NEQ predicate on the "redirect_url" field.
func RedirectURLNEQ(v string) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldNEQ(FieldRedirectURL, v))
}

// RedirectURLIn applies the In predicate on the "redirect_url" field.
func RedirectURLIn(vs ...string) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldIn(FieldRedirectURL, vs...))
}

// RedirectURLNotIn applies the NotIn predicate on the "redirect_url" field.
func RedirectURLNotIn(vs ...string) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldNotIn(FieldRedirectURL, vs...))
}

// RedirectURLGT applies the GT predicate on the "redirect_url" field.
func RedirectURLGT(v string) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldGT(FieldRedirectURL, v))
}

// RedirectURLGTE applies the GTE predicate on the "redirect_url" field.
func RedirectURLGTE(v string) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldGTE(FieldRedirectURL, v))
}

// RedirectURLLT applies the LT predicate on the "redirect_url" field.
func RedirectURLLT(v string) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldLT(FieldRedirectURL, v))
}

// RedirectURLLTE applies the LTE predicate on the "redirect_url" field.
func RedirectURLLTE(v string) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldLTE(FieldRedirectURL, v))
}

// RedirectURLContains applies the Contains predicate on the "redirect_url" field.
func RedirectURLContains(v string) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldContains(FieldRedirectURL, v))
}

// RedirectURLHasPrefix applies the HasPrefix predicate on the "redirect_url" field.
func RedirectURLHasPrefix(v string) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldHasPrefix(FieldRedirectURL, v))
}

// RedirectURLHasSuffix applies the HasSuffix predicate on the "redirect_url" field.
func RedirectURLHasSuffix(v string) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldHasSuffix(FieldRedirectURL, v))
}

// RedirectURLIsNil applies the IsNil predicate on the "redirect_url" field.
func RedirectURLIsNil() predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldIsNull(FieldRedirectURL))
}

// RedirectURLNotNil applies the NotNil predicate on the "redirect_url" field.
func RedirectURLNotNil() predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldNotNull(FieldRedirectURL))
}

// RedirectURLEqualFold applies the EqualFold predicate on the "redirect_url" field.
func RedirectURLEqualFold(v string) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldEqualFold(FieldRedirectURL, v))
}

// RedirectURLContainsFold applies the ContainsFold predicate on the "redirect_url" field.
func RedirectURLContainsFold(v string) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldContainsFold(FieldRedirectURL, v))
}

// RequestIPEQ applies the EQ predicate on the "request_ip" field.
func RequestIPEQ(v string) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldEQ(FieldRequestIP, v))
}

// RequestIPNEQ applies the NEQ predicate on the "request_ip" field.
func RequestIPNEQ(v string) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldNEQ(FieldRequestIP, v))
}

// RequestIPIn applies the In predicate on the "request_ip" field.
func RequestIPIn(vs ...string) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldIn(FieldRequestIP, vs...))
}

// RequestIPNotIn applies the NotIn predicate on the "request_ip" field.
func RequestIPNotIn(vs ...string) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldNotIn(FieldRequestIP, vs...))
}

// RequestIPGT applies the GT predicate on the "request_ip" field.
func RequestIPGT(v string) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldGT(FieldRequestIP, v))
}

// RequestIPGTE applies the GTE predicate on the "request_ip" field.
func RequestIPGTE(v string) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldGTE(FieldRequestIP, v))
}

// RequestIPLT applies the LT predicate on the "request_ip" field.
func RequestIPLT(v string) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldLT(FieldRequestIP, v))
}

// RequestIPLTE applies the LTE predicate on the "request_ip" field.
func RequestIPLTE(v string) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldLTE(FieldRequestIP, v))
}

// RequestIPContains applies the Contains predicate on the "request_ip" field.
func RequestIPContains(v string) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldContains(FieldRequestIP, v))
}

// RequestIPHasPrefix applies the HasPrefix predicate on the "request_ip" field.
func RequestIPHasPrefix(v string) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldHasPrefix(FieldRequestIP, v))
}

// RequestIPHasSuffix applies the HasSuffix predicate on the "request_ip" field.
func RequestIPHasSuffix(v string) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldHasSuffix(FieldRequestIP, v))
}

// RequestIPIsNil applies the IsNil predicate on the "request_ip" field.
func RequestIPIsNil() predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldIsNull(FieldRequestIP))
}

// RequestIPNotNil applies the NotNil predicate on the "request_ip" field.
func RequestIPNotNil() predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldNotNull(FieldRequestIP))
}

// RequestIPEqualFold applies the EqualFold predicate on the "request_ip" field.
func RequestIPEqualFold(v string) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldEqualFold(FieldRequestIP, v))
}

// RequestIPContainsFold applies the ContainsFold predicate on the "request_ip" field.
func RequestIPContainsFold(v string) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldContainsFold(FieldRequestIP, v))
}

// RequestUserAgentEQ applies the EQ predicate on the "request_user_agent" field.
func RequestUserAgentEQ(v string) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldEQ(FieldRequestUserAgent, v))
}

// RequestUserAgentNEQ applies the NEQ predicate on the "request_user_agent" field.
func RequestUserAgentNEQ(v string) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldNEQ(FieldRequestUserAgent, v))
}

// RequestUserAgentIn applies the In predicate on the "request_user_agent" field.
func RequestUserAgentIn(vs ...string) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldIn(FieldRequestUserAgent, vs...))
}

// RequestUserAgentNotIn applies the NotIn predicate on the "request_user_agent" field.
func RequestUserAgentNotIn(vs ...string) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldNotIn(FieldRequestUserAgent, vs...))
}

// RequestUserAgentGT applies the GT predicate on the "request_user_agent" field.
func RequestUserAgentGT(v string) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldGT(FieldRequestUserAgent, v))
}

// RequestUserAgentGTE applies the GTE predicate on the "request_user_agent" field.
func RequestUserAgentGTE(v string) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldGTE(FieldRequestUserAgent, v))
}

// RequestUserAgentLT applies the LT predicate on the "request_user_agent" field.
func RequestUserAgentLT(v string) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldLT(FieldRequestUserAgent, v))
}

// RequestUserAgentLTE applies the LTE predicate on the "request_user_agent" field.
func RequestUserAgentLTE(v string) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldLTE(FieldRequestUserAgent, v))
}

// RequestUserAgentContains applies the Contains predicate on the "request_user_agent" field.
func RequestUserAgentContains(v string) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldContains(FieldRequestUserAgent, v))
}

// RequestUserAgentHasPrefix applies the HasPrefix predicate on the "request_user_agent" field.
func RequestUserAgentHasPrefix(v string) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldHasPrefix(FieldRequestUserAgent, v))
}

// RequestUserAgentHasSuffix applies the HasSuffix predicate on the "request_user_agent" field.
func RequestUserAgentHasSuffix(v string) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldHasSuffix(FieldRequestUserAgent, v))
}

// RequestUserAgentIsNil applies the IsNil predicate on the "request_user_agent" field.
func RequestUserAgentIsNil() predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldIsNull(FieldRequestUserAgent))
}

// RequestUserAgentNotNil applies the NotNil predicate on the "request_user_agent" field.
func RequestUserAgentNotNil() predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldNotNull(FieldRequestUserAgent))
}

// RequestUserAgentEqualFold applies the EqualFold predicate on the "request_user_agent" field.
func RequestUserAgentEqualFold(v string) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldEqualFold(FieldRequestUserAgent, v))
}

// RequestUserAgentContainsFold applies the ContainsFold predicate on the "request_user_agent" field.
func RequestUserAgentContainsFold(v string) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldContainsFold(FieldRequestUserAgent, v))
}

// AttemptsEQ applies the EQ predicate on the "attempts" field.
func AttemptsEQ(v int) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldEQ(FieldAttempts, v))
}

// AttemptsNEQ applies the NEQ predicate on the "attempts" field.
func AttemptsNEQ(v int) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldNEQ(FieldAttempts, v))
}

// AttemptsIn applies the In predicate on the "attempts" field.
func AttemptsIn(vs ...int) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldIn(FieldAttempts, vs...))
}

// AttemptsNotIn applies the NotIn predicate on the "attempts" field.
func AttemptsNotIn(vs ...int) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldNotIn(FieldAttempts, vs...))
}

// AttemptsGT applies the GT predicate on the "attempts" field.
func AttemptsGT(v int) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldGT(FieldAttempts, v))
}

// AttemptsGTE applies the GTE predicate on the "attempts" field.
func AttemptsGTE(v int) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldGTE(FieldAttempts, v))
}

// AttemptsLT applies the LT predicate on the "attempts" field.
func AttemptsLT(v int) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldLT(FieldAttempts, v))
}

// AttemptsLTE applies the LTE predicate on the "attempts" field.
func AttemptsLTE(v int) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldLTE(FieldAttempts, v))
}

// MaxAttemptsEQ applies the EQ predicate on the "max_attempts" field.
func MaxAttemptsEQ(v int) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldEQ(FieldMaxAttempts, v))
}

// MaxAttemptsNEQ applies the NEQ predicate on the "max_attempts" field.
func MaxAttemptsNEQ(v int) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldNEQ(FieldMaxAttempts, v))
}

// MaxAttemptsIn applies the In predicate on the "max_attempts" field.
func MaxAttemptsIn(vs ...int) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldIn(FieldMaxAttempts, vs...))
}

// MaxAttemptsNotIn applies the NotIn predicate on the "max_attempts" field.
func MaxAttemptsNotIn(vs ...int) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldNotIn(FieldMaxAttempts, vs...))
}

// MaxAttemptsGT applies the GT predicate on the "max_attempts" field.
func MaxAttemptsGT(v int) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldGT(FieldMaxAttempts, v))
}

// MaxAttemptsGTE applies the GTE predicate on the "max_attempts" field.
func MaxAttemptsGTE(v int) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldGTE(FieldMaxAttempts, v))
}

// MaxAttemptsLT applies the LT predicate on the "max_attempts" field.
func MaxAttemptsLT(v int) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldLT(FieldMaxAttempts, v))
}

// MaxAttemptsLTE applies the LTE predicate on the "max_attempts" field.
func MaxAttemptsLTE(v int) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldLTE(FieldMaxAttempts, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldContainsFold(FieldStatus, v))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldLTE(FieldExpiresAt, v))
}

// ConsumedAtEQ applies the EQ predicate on the "consumed_at" field.
func ConsumedAtEQ(v time.Time) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldEQ(FieldConsumedAt, v))
}

// ConsumedAtNEQ applies the NEQ predicate on the "consumed_at" field.
func ConsumedAtNEQ(v time.Time) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldNEQ(FieldConsumedAt, v))
}

// ConsumedAtIn applies the In predicate on the "consumed_at" field.
func ConsumedAtIn(vs ...time.Time) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldIn(FieldConsumedAt, vs...))
}

// ConsumedAtNotIn applies the NotIn predicate on the "consumed_at" field.
func ConsumedAtNotIn(vs ...time.Time) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldNotIn(FieldConsumedAt, vs...))
}

// ConsumedAtGT applies the GT predicate on the "consumed_at" field.
func ConsumedAtGT(v time.Time) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldGT(FieldConsumedAt, v))
}

// ConsumedAtGTE applies the GTE predicate on the "consumed_at" field.
func ConsumedAtGTE(v time.Time) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldGTE(FieldConsumedAt, v))
}

// ConsumedAtLT applies the LT predicate on the "consumed_at" field.
func ConsumedAtLT(v time.Time) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldLT(FieldConsumedAt, v))
}

// ConsumedAtLTE applies the LTE predicate on the "consumed_at" field.
func ConsumedAtLTE(v time.Time) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldLTE(FieldConsumedAt, v))
}

// ConsumedAtIsNil applies the IsNil predicate on the "consumed_at" field.
func ConsumedAtIsNil() predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldIsNull(FieldConsumedAt))
}

// ConsumedAtNotNil applies the NotNil predicate on the "consumed_at" field.
func ConsumedAtNotNil() predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldNotNull(FieldConsumedAt))
}

// RevokedAtEQ applies the EQ predicate on the "revoked_at" field.
func RevokedAtEQ(v time.Time) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldEQ(FieldRevokedAt, v))
}

// RevokedAtNEQ applies the NEQ predicate on the "revoked_at" field.
func RevokedAtNEQ(v time.Time) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldNEQ(FieldRevokedAt, v))
}

// RevokedAtIn applies the In predicate on the "revoked_at" field.
func RevokedAtIn(vs ...time.Time) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldIn(FieldRevokedAt, vs...))
}

// RevokedAtNotIn applies the NotIn predicate on the "revoked_at" field.
func RevokedAtNotIn(vs ...time.Time) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldNotIn(FieldRevokedAt, vs...))
}

// RevokedAtGT applies the GT predicate on the "revoked_at" field.
func RevokedAtGT(v time.Time) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldGT(FieldRevokedAt, v))
}

// RevokedAtGTE applies the GTE predicate on the "revoked_at" field.
func RevokedAtGTE(v time.Time) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldGTE(FieldRevokedAt, v))
}

// RevokedAtLT applies the LT predicate on the "revoked_at" field.
func RevokedAtLT(v time.Time) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldLT(FieldRevokedAt, v))
}

// RevokedAtLTE applies the LTE predicate on the "revoked_at" field.
func RevokedAtLTE(v time.Time) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldLTE(FieldRevokedAt, v))
}

// RevokedAtIsNil applies the IsNil predicate on the "revoked_at" field.
func RevokedAtIsNil() predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldIsNull(FieldRevokedAt))
}

// RevokedAtNotNil applies the NotNil predicate on the "revoked_at" field.
func RevokedAtNotNil() predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldNotNull(FieldRevokedAt))
}

// EmailProviderMessageIDEQ applies the EQ predicate on the "email_provider_message_id" field.
func EmailProviderMessageIDEQ(v string) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldEQ(FieldEmailProviderMessageID, v))
}

// EmailProviderMessageIDNEQ applies the NEQ predicate on the "email_provider_message_id" field.
func EmailProviderMessageIDNEQ(v string) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldNEQ(FieldEmailProviderMessageID, v))
}

// EmailProviderMessageIDIn applies the In predicate on the "email_provider_message_id" field.
func EmailProviderMessageIDIn(vs ...string) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldIn(FieldEmailProviderMessageID, vs...))
}

// EmailProviderMessageIDNotIn applies the NotIn predicate on the "email_provider_message_id" field.
func EmailProviderMessageIDNotIn(vs ...string) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldNotIn(FieldEmailProviderMessageID, vs...))
}

// EmailProviderMessageIDGT applies the GT predicate on the "email_provider_message_id" field.
func EmailProviderMessageIDGT(v string) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldGT(FieldEmailProviderMessageID, v))
}

// EmailProviderMessageIDGTE applies the GTE predicate on the "email_provider_message_id" field.
func EmailProviderMessageIDGTE(v string) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldGTE(FieldEmailProviderMessageID, v))
}

// EmailProviderMessageIDLT applies the LT predicate on the "email_provider_message_id" field.
func EmailProviderMessageIDLT(v string) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldLT(FieldEmailProviderMessageID, v))
}

// EmailProviderMessageIDLTE applies the LTE predicate on the "email_provider_message_id" field.
func EmailProviderMessageIDLTE(v string) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldLTE(FieldEmailProviderMessageID, v))
}

// EmailProviderMessageIDContains applies the Contains predicate on the "email_provider_message_id" field.
func EmailProviderMessageIDContains(v string) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldContains(FieldEmailProviderMessageID, v))
}

// EmailProviderMessageIDHasPrefix applies the HasPrefix predicate on the "email_provider_message_id" field.
func EmailProviderMessageIDHasPrefix(v string) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldHasPrefix(FieldEmailProviderMessageID, v))
}

// EmailProviderMessageIDHasSuffix applies the HasSuffix predicate on the "email_provider_message_id" field.
func EmailProviderMessageIDHasSuffix(v string) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldHasSuffix(FieldEmailProviderMessageID, v))
}

// EmailProviderMessageIDIsNil applies the IsNil predicate on the "email_provider_message_id" field.
func EmailProviderMessageIDIsNil() predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldIsNull(FieldEmailProviderMessageID))
}

// EmailProviderMessageIDNotNil applies the NotNil predicate on the "email_provider_message_id" field.
func EmailProviderMessageIDNotNil() predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldNotNull(FieldEmailProviderMessageID))
}

// EmailProviderMessageIDEqualFold applies the EqualFold predicate on the "email_provider_message_id" field.
func EmailProviderMessageIDEqualFold(v string) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldEqualFold(FieldEmailProviderMessageID, v))
}

// EmailProviderMessageIDContainsFold applies the ContainsFold predicate on the "email_provider_message_id" field.
func EmailProviderMessageIDContainsFold(v string) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldContainsFold(FieldEmailProviderMessageID, v))
}

// MetadataIsNil applies the IsNil predicate on the "metadata" field.
func MetadataIsNil() predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldIsNull(FieldMetadata))
}

// MetadataNotNil applies the NotNil predicate on the "metadata" field.
func MetadataNotNil() predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldNotNull(FieldMetadata))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.FieldNotNull(FieldDeletedAt))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AuthChallenge) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AuthChallenge) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AuthChallenge) predicate.AuthChallenge {
	return predicate.AuthChallenge(sql.NotPredicates(p))
}
