// Code generated by ent, DO NOT EDIT.

package appdatarecord

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/plystra/plystra/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.AppDataRecord {
	return predicate.AppDataRecord(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.AppDataRecord {
	return predicate.AppDataRecord(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.AppDataRecord {
	return predicate.AppDataRecord(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.AppDataRecord {
	return predicate.AppDataRecord(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.AppDataRecord {
	return predicate.AppDataRecord(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.AppDataRecord {
	return predicate.AppDataRecord(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.AppDataRecord {
	return predicate.AppDataRecord(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.AppDataRecord {
	return predicate.AppDataRecord(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.AppDataRecord {
	return predicate.AppDataRecord(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.AppDataRecord {
	return predicate.AppDataRecord(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.AppDataRecord {
	return predicate.AppDataRecord(sql.FieldContainsFold(FieldID, id))
}

// SpaceID applies equality check predicate on the "space_id" field. It's identical to SpaceIDEQ.
func SpaceID(v string) predicate.AppDataRecord {
	return predicate.AppDataRecord(sql.FieldEQ(FieldSpaceID, v))
}

// ModelID applies equality check predicate on the "model_id" field. It's identical to ModelIDEQ.
func ModelID(v string) predicate.AppDataRecord {
	return predicate.AppDataRecord(sql.FieldEQ(FieldModelID, v))
}

// ModelKey applies equality check predicate on the "model_key" field. It's identical to ModelKeyEQ.
func ModelKey(v string) predicate.AppDataRecord {
	return predicate.AppDataRecord(sql.FieldEQ(FieldModelKey, v))
}

// GroupID applies equality check predicate on the "group_id" field. It's identical to GroupIDEQ.
func GroupID(v string) predicate.AppDataRecord {
	return predicate.AppDataRecord(sql.FieldEQ(FieldGroupID, v))
}

// OwnerMemberID applies equality check predicate on the "owner_member_id" field. It's identical to OwnerMemberIDEQ.
func OwnerMemberID(v string) predicate.AppDataRecord {
	return predicate.AppDataRecord(sql.FieldEQ(FieldOwnerMemberID, v))
}

// DisplayName applies equality check predicate on the "display_name" field. It's identical to DisplayNameEQ.
func DisplayName(v string) predicate.AppDataRecord {
	return predicate.AppDataRecord(sql.FieldEQ(FieldDisplayName, v))
}

// Visibility applies equality check predicate on the "visibility" field. It's identical to VisibilityEQ.
func Visibility(v string) predicate.AppDataRecord {
	return predicate.AppDataRecord(sql.FieldEQ(FieldVisibility, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.AppDataRecord {
	return predicate.AppDataRecord(sql.FieldEQ(FieldStatus, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.AppDataRecord {
	return predicate.AppDataRecord(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.AppDataRecord {
	return predicate.AppDataRecord(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.AppDataRecord {
	return predicate.AppDataRecord(sql.FieldEQ(FieldDeletedAt, v))
}

// SpaceIDEQ applies the EQ predicate on the "space_id" field.
func SpaceIDEQ(v string) predicate.AppDataRecord {
	return predicate.AppDataRecord(sql.FieldEQ(FieldSpaceID, v))
}

// SpaceIDNEQ applies the NEQ predicate on the "space_id" field.
func SpaceIDNEQ(v string) predicate.AppDataRecord {
	return predicate.AppDataRecord(sql.FieldNEQ(FieldSpaceID, v))
}

// SpaceIDIn applies the In predicate on the "space_id" field.
func SpaceIDIn(vs ...string) predicate.AppDataRecord {
	return predicate.AppDataRecord(sql.FieldIn(FieldSpaceID, vs...))
}

// SpaceIDNotIn applies the NotIn predicate on the "space_id" field.
func SpaceIDNotIn(vs ...string) predicate.AppDataRecord {
	return predicate.AppDataRecord(sql.FieldNotIn(FieldSpaceID, vs...))
}

// SpaceIDGT applies the GT predicate on the "space_id" field.
func SpaceIDGT(v string) predicate.AppDataRecord {
	return predicate.AppDataRecord(sql.FieldGT(FieldSpaceID, v))
}

// SpaceIDGTE applies the GTE predicate on the "space_id" field.
func SpaceIDGTE(v string) predicate.AppDataRecord {
	return predicate.AppDataRecord(sql.FieldGTE(FieldSpaceID, v))
}

// SpaceIDLT applies the LT predicate on the "space_id" field.
func SpaceIDLT(v string) predicate.AppDataRecord {
	return predicate.AppDataRecord(sql.FieldLT(FieldSpaceID, v))
}

// SpaceIDLTE applies the LTE predicate on the "space_id" field.
func SpaceIDLTE(v string) predicate.AppDataRecord {
	return predicate.AppDataRecord(sql.FieldLTE(FieldSpaceID, v))
}

// SpaceIDContains applies the Contains predicate on the "space_id" field.
func SpaceIDContains(v string) predicate.AppDataRecord {
	return predicate.AppDataRecord(sql.FieldContains(FieldSpaceID, v))
}

// SpaceIDHasPrefix applies the HasPrefix predicate on the "space_id" field.
func SpaceIDHasPrefix(v string) predicate.AppDataRecord {
	return predicate.AppDataRecord(sql.FieldHasPrefix(FieldSpaceID, v))
}

// SpaceIDHasSuffix applies the HasSuffix predicate on the "space_id" field.
func SpaceIDHasSuffix(v string) predicate.AppDataRecord {
	return predicate.AppDataRecord(sql.FieldHasSuffix(FieldSpaceID, v))
}

// SpaceIDEqualFold applies the EqualFold predicate on the "space_id" field.
func SpaceIDEqualFold(v string) predicate.AppDataRecord {
	return predicate.AppDataRecord(sql.FieldEqualFold(FieldSpaceID, v))
}

// SpaceIDContainsFold applies the ContainsFold predicate on the "space_id" field.
func SpaceIDContainsFold(v string) predicate.AppDataRecord {
	return predicate.AppDataRecord(sql.FieldContainsFold(FieldSpaceID, v))
}

// ModelIDEQ applies the EQ predicate on the "model_id" field.
func ModelIDEQ(v string) predicate.AppDataRecord {
	return predicate.AppDataRecord(sql.FieldEQ(FieldModelID, v))
}

// ModelIDNEQ applies the NEQ predicate on the "model_id" field.
func ModelIDNEQ(v string) predicate.AppDataRecord {
	return predicate.AppDataRecord(sql.FieldNEQ(FieldModelID, v))
}

// ModelIDIn applies the In predicate on the "model_id" field.
func ModelIDIn(vs ...string) predicate.AppDataRecord {
	return predicate.AppDataRecord(sql.FieldIn(FieldModelID, vs...))
}

// ModelIDNotIn applies the NotIn predicate on the "model_id" field.
func ModelIDNotIn(vs ...string) predicate.AppDataRecord {
	return predicate.AppDataRecord(sql.FieldNotIn(FieldModelID, vs...))
}

// ModelIDGT applies the GT predicate on the "model_id" field.
func ModelIDGT(v string) predicate.AppDataRecord {
	return predicate.AppDataRecord(sql.FieldGT(FieldModelID, v))
}

// ModelIDGTE applies the GTE predicate on the "model_id" field.
func ModelIDGTE(v string) predicate.AppDataRecord {
	return predicate.AppDataRecord(sql.FieldGTE(FieldModelID, v))
}

// ModelIDLT applies the LT predicate on the "model_id" field.
func ModelIDLT(v string) predicate.AppDataRecord {
	return predicate.AppDataRecord(sql.FieldLT(FieldModelID, v))
}

// ModelIDLTE applies the LTE predicate on the "model_id" field.
func ModelIDLTE(v string) predicate.AppDataRecord {
	return predicate.AppDataRecord(sql.FieldLTE(FieldModelID, v))
}

// ModelIDContains applies the Contains predicate on the "model_id" field.
func ModelIDContains(v string) predicate.AppDataRecord {
	return predicate.AppDataRecord(sql.FieldContains(FieldModelID, v))
}

// ModelIDHasPrefix applies the HasPrefix predicate on the "model_id" field.
func ModelIDHasPrefix(v string) predicate.AppDataRecord {
	return predicate.AppDataRecord(sql.FieldHasPrefix(FieldModelID, v))
}

// ModelIDHasSuffix applies the HasSuffix predicate on the "model_id" field.
func ModelIDHasSuffix(v string) predicate.AppDataRecord {
	return predicate.AppDataRecord(sql.FieldHasSuffix(FieldModelID, v))
}

// ModelIDEqualFold applies the EqualFold predicate on the "model_id" field.
func ModelIDEqualFold(v string) predicate.AppDataRecord {
	return predicate.AppDataRecord(sql.FieldEqualFold(FieldModelID, v))
}

// ModelIDContainsFold applies the ContainsFold predicate on the "model_id" field.
func ModelIDContainsFold(v string) predicate.AppDataRecord {
	return predicate.AppDataRecord(sql.FieldContainsFold(FieldModelID, v))
}

// ModelKeyEQ applies the EQ predicate on the "model_key" field.
func ModelKeyEQ(v string) predicate.AppDataRecord {
	return predicate.AppDataRecord(sql.FieldEQ(FieldModelKey, v))
}

// ModelKeyNEQ applies the NEQ predicate on the "model_key" field.
func ModelKeyNEQ(v string) predicate.AppDataRecord {
	return predicate.AppDataRecord(sql.FieldNEQ(FieldModelKey, v))
}

// ModelKeyIn applies the In predicate on the "model_key" field.
func ModelKeyIn(vs ...string) predicate.AppDataRecord {
	return predicate.AppDataRecord(sql.FieldIn(FieldModelKey, vs...))
}

// ModelKeyNotIn applies the NotIn predicate on the "model_key" field.
func ModelKeyNotIn(vs ...string) predicate.AppDataRecord {
	return predicate.AppDataRecord(sql.FieldNotIn(FieldModelKey, vs...))
}

// ModelKeyGT applies the GT predicate on the "model_key" field.
func ModelKeyGT(v string) predicate.AppDataRecord {
	return predicate.AppDataRecord(sql.FieldGT(FieldModelKey, v))
}

// ModelKeyGTE applies the GTE predicate on the "model_key" field.
func ModelKeyGTE(v string) predicate.AppDataRecord {
	return predicate.AppDataRecord(sql.FieldGTE(FieldModelKey, v))
}

// ModelKeyLT applies the LT predicate on the "model_key" field.
func ModelKeyLT(v string) predicate.AppDataRecord {
	return predicate.AppDataRecord(sql.FieldLT(FieldModelKey, v))
}

// ModelKeyLTE applies the LTE predicate on the "model_key" field.
func ModelKeyLTE(v string) predicate.AppDataRecord {
	return predicate.AppDataRecord(sql.FieldLTE(FieldModelKey, v))
}

// ModelKeyContains applies the Contains predicate on the "model_key" field.
func ModelKeyContains(v string) predicate.AppDataRecord {
	return predicate.AppDataRecord(sql.FieldContains(FieldModelKey, v))
}

// ModelKeyHasPrefix applies the HasPrefix predicate on the "model_key" field.
func ModelKeyHasPrefix(v string) predicate.AppDataRecord {
	return predicate.AppDataRecord(sql.FieldHasPrefix(FieldModelKey, v))
}

// ModelKeyHasSuffix applies the HasSuffix predicate on the "model_key" field.
func ModelKeyHasSuffix(v string) predicate.AppDataRecord {
	return predicate.AppDataRecord(sql.FieldHasSuffix(FieldModelKey, v))
}

// ModelKeyEqualFold applies the EqualFold predicate on the "model_key" field.
func ModelKeyEqualFold(v string) predicate.AppDataRecord {
	return predicate.AppDataRecord(sql.FieldEqualFold(FieldModelKey, v))
}

// ModelKeyContainsFold applies the ContainsFold predicate on the "model_key" field.
func ModelKeyContainsFold(v string) predicate.AppDataRecord {
	return predicate.AppDataRecord(sql.FieldContainsFold(FieldModelKey, v))
}

// GroupIDEQ applies the EQ predicate on the "group_id" field.
func GroupIDEQ(v string) predicate.AppDataRecord {
	return predicate.AppDataRecord(sql.FieldEQ(FieldGroupID, v))
}

// GroupIDNEQ applies the NEQ predicate on the "group_id" field.
func GroupIDNEQ(v string) predicate.AppDataRecord {
	return predicate.AppDataRecord(sql.FieldNEQ(FieldGroupID, v))
}

// GroupIDIn applies the In predicate on the "group_id" field.
func GroupIDIn(vs ...string) predicate.AppDataRecord {
	return predicate.AppDataRecord(sql.FieldIn(FieldGroupID, vs...))
}

// GroupIDNotIn applies the NotIn predicate on the "group_id" field.
func GroupIDNotIn(vs ...string) predicate.AppDataRecord {
	return predicate.AppDataRecord(sql.FieldNotIn(FieldGroupID, vs...))
}

// GroupIDGT applies the GT predicate on the "group_id" field.
func GroupIDGT(v string) predicate.AppDataRecord {
	return predicate.AppDataRecord(sql.FieldGT(FieldGroupID, v))
}

// GroupIDGTE applies the GTE predicate on the "group_id" field.
func GroupIDGTE(v string) predicate.AppDataRecord {
	return predicate.AppDataRecord(sql.FieldGTE(FieldGroupID, v))
}

// GroupIDLT applies the LT predicate on the "group_id" field.
func GroupIDLT(v string) predicate.AppDataRecord {
	return predicate.AppDataRecord(sql.FieldLT(FieldGroupID, v))
}

// GroupIDLTE applies the LTE predicate on the "group_id" field.
func GroupIDLTE(v string) predicate.AppDataRecord {
	return predicate.AppDataRecord(sql.FieldLTE(FieldGroupID, v))
}

// GroupIDContains applies the Contains predicate on the "group_id" field.
func GroupIDContains(v string) predicate.AppDataRecord {
	return predicate.AppDataRecord(sql.FieldContains(FieldGroupID, v))
}

// GroupIDHasPrefix applies the HasPrefix predicate on the "group_id" field.
func GroupIDHasPrefix(v string) predicate.AppDataRecord {
	return predicate.AppDataRecord(sql.FieldHasPrefix(FieldGroupID, v))
}

// GroupIDHasSuffix applies the HasSuffix predicate on the "group_id" field.
func GroupIDHasSuffix(v string) predicate.AppDataRecord {
	return predicate.AppDataRecord(sql.FieldHasSuffix(FieldGroupID, v))
}

// GroupIDIsNil applies the IsNil predicate on the "group_id" field.
func GroupIDIsNil() predicate.AppDataRecord {
	return predicate.AppDataRecord(sql.FieldIsNull(FieldGroupID))
}

// GroupIDNotNil applies the NotNil predicate on the "group_id" field.
func GroupIDNotNil() predicate.AppDataRecord {
	return predicate.AppDataRecord(sql.FieldNotNull(FieldGroupID))
}

// GroupIDEqualFold applies the EqualFold predicate on the "group_id" field.
func GroupIDEqualFold(v string) predicate.AppDataRecord {
	return predicate.AppDataRecord(sql.FieldEqualFold(FieldGroupID, v))
}

// GroupIDContainsFold applies the ContainsFold predicate on the "group_id" field.
func GroupIDContainsFold(v string) predicate.AppDataRecord {
	return predicate.AppDataRecord(sql.FieldContainsFold(FieldGroupID, v))
}

// OwnerMemberIDEQ applies the EQ predicate on the "owner_member_id" field.
func OwnerMemberIDEQ(v string) predicate.AppDataRecord {
	return predicate.AppDataRecord(sql.FieldEQ(FieldOwnerMemberID, v))
}

// OwnerMemberIDNEQ applies the NEQ predicate on the "owner_member_id" field.
func OwnerMemberIDNEQ(v string) predicate.AppDataRecord {
	return predicate.AppDataRecord(sql.FieldNEQ(FieldOwnerMemberID, v))
}

// OwnerMemberIDIn applies the In predicate on the "owner_member_id" field.
func OwnerMemberIDIn(vs ...string) predicate.AppDataRecord {
	return predicate.AppDataRecord(sql.FieldIn(FieldOwnerMemberID, vs...))
}

// OwnerMemberIDNotIn applies the NotIn predicate on the "owner_member_id" field.
func OwnerMemberIDNotIn(vs ...string) predicate.AppDataRecord {
	return predicate.AppDataRecord(sql.FieldNotIn(FieldOwnerMemberID, vs...))
}

// OwnerMemberIDGT applies the GT predicate on the "owner_member_id" field.
func OwnerMemberIDGT(v string) predicate.AppDataRecord {
	return predicate.AppDataRecord(sql.FieldGT(FieldOwnerMemberID, v))
}

// OwnerMemberIDGTE applies the GTE predicate on the "owner_member_id" field.
func OwnerMemberIDGTE(v string) predicate.AppDataRecord {
	return predicate.AppDataRecord(sql.FieldGTE(FieldOwnerMemberID, v))
}

// OwnerMemberIDLT applies the LT predicate on the "owner_member_id" field.
func OwnerMemberIDLT(v string) predicate.AppDataRecord {
	return predicate.AppDataRecord(sql.FieldLT(FieldOwnerMemberID, v))
}

// OwnerMemberIDLTE applies the LTE predicate on the "owner_member_id" field.
func OwnerMemberIDLTE(v string) predicate.AppDataRecord {
	return predicate.AppDataRecord(sql.FieldLTE(FieldOwnerMemberID, v))
}

// OwnerMemberIDContains applies the Contains predicate on the "owner_member_id" field.
func OwnerMemberIDContains(v string) predicate.AppDataRecord {
	return predicate.AppDataRecord(sql.FieldContains(FieldOwnerMemberID, v))
}

// OwnerMemberIDHasPrefix applies the HasPrefix predicate on the "owner_member_id" field.
func OwnerMemberIDHasPrefix(v string) predicate.AppDataRecord {
	return predicate.AppDataRecord(sql.FieldHasPrefix(FieldOwnerMemberID, v))
}

// OwnerMemberIDHasSuffix applies the HasSuffix predicate on the "owner_member_id" field.
func OwnerMemberIDHasSuffix(v string) predicate.AppDataRecord {
	return predicate.AppDataRecord(sql.FieldHasSuffix(FieldOwnerMemberID, v))
}

// OwnerMemberIDIsNil applies the IsNil predicate on the "owner_member_id" field.
func OwnerMemberIDIsNil() predicate.AppDataRecord {
	return predicate.AppDataRecord(sql.FieldIsNull(FieldOwnerMemberID))
}

// OwnerMemberIDNotNil applies the NotNil predicate on the "owner_member_id" field.
func OwnerMemberIDNotNil() predicate.AppDataRecord {
	return predicate.AppDataRecord(sql.FieldNotNull(FieldOwnerMemberID))
}

// OwnerMemberIDEqualFold applies the EqualFold predicate on the "owner_member_id" field.
func OwnerMemberIDEqualFold(v string) predicate.AppDataRecord {
	return predicate.AppDataRecord(sql.FieldEqualFold(FieldOwnerMemberID, v))
}

// OwnerMemberIDContainsFold applies the ContainsFold predicate on the "owner_member_id" field.
func OwnerMemberIDContainsFold(v string) predicate.AppDataRecord {
	return predicate.AppDataRecord(sql.FieldContainsFold(FieldOwnerMemberID, v))
}

// DisplayNameEQ applies the EQ predicate on the "display_name" field.
func DisplayNameEQ(v string) predicate.AppDataRecord {
	return predicate.AppDataRecord(sql.FieldEQ(FieldDisplayName, v))
}

// DisplayNameNEQ applies the NEQ predicate on the "display_name" field.
func DisplayNameNEQ(v string) predicate.AppDataRecord {
	return predicate.AppDataRecord(sql.FieldNEQ(FieldDisplayName, v))
}

// DisplayNameIn applies the In predicate on the "display_name" field.
func DisplayNameIn(vs ...string) predicate.AppDataRecord {
	return predicate.AppDataRecord(sql.FieldIn(FieldDisplayName, vs...))
}

// DisplayNameNotIn applies the NotIn predicate on the "display_name" field.
func DisplayNameNotIn(vs ...string) predicate.AppDataRecord {
	return predicate.AppDataRecord(sql.FieldNotIn(FieldDisplayName, vs...))
}

// DisplayNameGT applies the GT predicate on the "display_name" field.
func DisplayNameGT(v string) predicate.AppDataRecord {
	return predicate.AppDataRecord(sql.FieldGT(FieldDisplayName, v))
}

// DisplayNameGTE applies the GTE predicate on the "display_name" field.
func DisplayNameGTE(v string) predicate.AppDataRecord {
	return predicate.AppDataRecord(sql.FieldGTE(FieldDisplayName, v))
}

// DisplayNameLT applies the LT predicate on the "display_name" field.
func DisplayNameLT(v string) predicate.AppDataRecord {
	return predicate.AppDataRecord(sql.FieldLT(FieldDisplayName, v))
}

// DisplayNameLTE applies the LTE predicate on the "display_name" field.
func DisplayNameLTE(v string) predicate.AppDataRecord {
	return predicate.AppDataRecord(sql.FieldLTE(FieldDisplayName, v))
}

// DisplayNameContains applies the Contains predicate on the "display_name" field.
func DisplayNameContains(v string) predicate.AppDataRecord {
	return predicate.AppDataRecord(sql.FieldContains(FieldDisplayName, v))
}

// DisplayNameHasPrefix applies the HasPrefix predicate on the "display_name" field.
func DisplayNameHasPrefix(v string) predicate.AppDataRecord {
	return predicate.AppDataRecord(sql.FieldHasPrefix(FieldDisplayName, v))
}

// DisplayNameHasSuffix applies the HasSuffix predicate on the "display_name" field.
func DisplayNameHasSuffix(v string) predicate.AppDataRecord {
	return predicate.AppDataRecord(sql.FieldHasSuffix(FieldDisplayName, v))
}

// DisplayNameIsNil applies the IsNil predicate on the "display_name" field.
func DisplayNameIsNil() predicate.AppDataRecord {
	return predicate.AppDataRecord(sql.FieldIsNull(FieldDisplayName))
}

// DisplayNameNotNil applies the NotNil predicate on the "display_name" field.
func DisplayNameNotNil() predicate.AppDataRecord {
	return predicate.AppDataRecord(sql.FieldNotNull(FieldDisplayName))
}

// DisplayNameEqualFold applies the EqualFold predicate on the "display_name" field.
func DisplayNameEqualFold(v string) predicate.AppDataRecord {
	return predicate.AppDataRecord(sql.FieldEqualFold(FieldDisplayName, v))
}

// DisplayNameContainsFold applies the ContainsFold predicate on the "display_name" field.
func DisplayNameContainsFold(v string) predicate.AppDataRecord {
	return predicate.AppDataRecord(sql.FieldContainsFold(FieldDisplayName, v))
}

// VisibilityEQ applies the EQ predicate on the "visibility" field.
func VisibilityEQ(v string) predicate.AppDataRecord {
	return predicate.AppDataRecord(sql.FieldEQ(FieldVisibility, v))
}

// VisibilityNEQ applies the NEQ predicate on the "visibility" field.
func VisibilityNEQ(v string) predicate.AppDataRecord {
	return predicate.AppDataRecord(sql.FieldNEQ(FieldVisibility, v))
}

// VisibilityIn applies the In predicate on the "visibility" field.
func VisibilityIn(vs ...string) predicate.AppDataRecord {
	return predicate.AppDataRecord(sql.FieldIn(FieldVisibility, vs...))
}

// VisibilityNotIn applies the NotIn predicate on the "visibility" field.
func VisibilityNotIn(vs ...string) predicate.AppDataRecord {
	return predicate.AppDataRecord(sql.FieldNotIn(FieldVisibility, vs...))
}

// VisibilityGT applies the GT predicate on the "visibility" field.
func VisibilityGT(v string) predicate.AppDataRecord {
	return predicate.AppDataRecord(sql.FieldGT(FieldVisibility, v))
}

// VisibilityGTE applies the GTE predicate on the "visibility" field.
func VisibilityGTE(v string) predicate.AppDataRecord {
	return predicate.AppDataRecord(sql.FieldGTE(FieldVisibility, v))
}

// VisibilityLT applies the LT predicate on the "visibility" field.
func VisibilityLT(v string) predicate.AppDataRecord {
	return predicate.AppDataRecord(sql.FieldLT(FieldVisibility, v))
}

// VisibilityLTE applies the LTE predicate on the "visibility" field.
func VisibilityLTE(v string) predicate.AppDataRecord {
	return predicate.AppDataRecord(sql.FieldLTE(FieldVisibility, v))
}

// VisibilityContains applies the Contains predicate on the "visibility" field.
func VisibilityContains(v string) predicate.AppDataRecord {
	return predicate.AppDataRecord(sql.FieldContains(FieldVisibility, v))
}

// VisibilityHasPrefix applies the HasPrefix predicate on the "visibility" field.
func VisibilityHasPrefix(v string) predicate.AppDataRecord {
	return predicate.AppDataRecord(sql.FieldHasPrefix(FieldVisibility, v))
}

// VisibilityHasSuffix applies the HasSuffix predicate on the "visibility" field.
func VisibilityHasSuffix(v string) predicate.AppDataRecord {
	return predicate.AppDataRecord(sql.FieldHasSuffix(FieldVisibility, v))
}

// VisibilityEqualFold applies the EqualFold predicate on the "visibility" field.
func VisibilityEqualFold(v string) predicate.AppDataRecord {
	return predicate.AppDataRecord(sql.FieldEqualFold(FieldVisibility, v))
}

// VisibilityContainsFold applies the ContainsFold predicate on the "visibility" field.
func VisibilityContainsFold(v string) predicate.AppDataRecord {
	return predicate.AppDataRecord(sql.FieldContainsFold(FieldVisibility, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.AppDataRecord {
	return predicate.AppDataRecord(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.AppDataRecord {
	return predicate.AppDataRecord(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.AppDataRecord {
	return predicate.AppDataRecord(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.AppDataRecord {
	return predicate.AppDataRecord(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.AppDataRecord {
	return predicate.AppDataRecord(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.AppDataRecord {
	return predicate.AppDataRecord(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.AppDataRecord {
	return predicate.AppDataRecord(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.AppDataRecord {
	return predicate.AppDataRecord(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.AppDataRecord {
	return predicate.AppDataRecord(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.AppDataRecord {
	return predicate.AppDataRecord(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.AppDataRecord {
	return predicate.AppDataRecord(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.AppDataRecord {
	return predicate.AppDataRecord(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.AppDataRecord {
	return predicate.AppDataRecord(sql.FieldContainsFold(FieldStatus, v))
}

// MetadataIsNil applies the IsNil predicate on the "metadata" field.
func MetadataIsNil() predicate.AppDataRecord {
	return predicate.AppDataRecord(sql.FieldIsNull(FieldMetadata))
}

// MetadataNotNil applies the NotNil predicate on the "metadata" field.
func MetadataNotNil() predicate.AppDataRecord {
	return predicate.AppDataRecord(sql.FieldNotNull(FieldMetadata))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.AppDataRecord {
	return predicate.AppDataRecord(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.AppDataRecord {
	return predicate.AppDataRecord(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.AppDataRecord {
	return predicate.AppDataRecord(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.AppDataRecord {
	return predicate.AppDataRecord(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.AppDataRecord {
	return predicate.AppDataRecord(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.AppDataRecord {
	return predicate.AppDataRecord(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.AppDataRecord {
	return predicate.AppDataRecord(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.AppDataRecord {
	return predicate.AppDataRecord(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.AppDataRecord {
	return predicate.AppDataRecord(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.AppDataRecord {
	return predicate.AppDataRecord(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.AppDataRecord {
	return predicate.AppDataRecord(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.AppDataRecord {
	return predicate.AppDataRecord(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.AppDataRecord {
	return predicate.AppDataRecord(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.AppDataRecord {
	return predicate.AppDataRecord(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.AppDataRecord {
	return predicate.AppDataRecord(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.AppDataRecord {
	return predicate.AppDataRecord(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.AppDataRecord {
	return predicate.AppDataRecord(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.AppDataRecord {
	return predicate.AppDataRecord(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.AppDataRecord {
	return predicate.AppDataRecord(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.AppDataRecord {
	return predicate.AppDataRecord(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.AppDataRecord {
	return predicate.AppDataRecord(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.AppDataRecord {
	return predicate.AppDataRecord(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.AppDataRecord {
	return predicate.AppDataRecord(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.AppDataRecord {
	return predicate.AppDataRecord(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.AppDataRecord {
	return predicate.AppDataRecord(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.AppDataRecord {
	return predicate.AppDataRecord(sql.FieldNotNull(FieldDeletedAt))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AppDataRecord) predicate.AppDataRecord {
	return predicate.AppDataRecord(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AppDataRecord) predicate.AppDataRecord {
	return predicate.AppDataRecord(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AppDataRecord) predicate.AppDataRecord {
	return predicate.AppDataRecord(sql.NotPredicates(p))
}
