// Code generated by ent, DO NOT EDIT.

package appdatarecordrevision

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/plystra/core/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.AppDataRecordRevision {
	return predicate.AppDataRecordRevision(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.AppDataRecordRevision {
	return predicate.AppDataRecordRevision(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.AppDataRecordRevision {
	return predicate.AppDataRecordRevision(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.AppDataRecordRevision {
	return predicate.AppDataRecordRevision(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.AppDataRecordRevision {
	return predicate.AppDataRecordRevision(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.AppDataRecordRevision {
	return predicate.AppDataRecordRevision(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.AppDataRecordRevision {
	return predicate.AppDataRecordRevision(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.AppDataRecordRevision {
	return predicate.AppDataRecordRevision(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.AppDataRecordRevision {
	return predicate.AppDataRecordRevision(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.AppDataRecordRevision {
	return predicate.AppDataRecordRevision(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.AppDataRecordRevision {
	return predicate.AppDataRecordRevision(sql.FieldContainsFold(FieldID, id))
}

// RecordID applies equality check predicate on the "record_id" field. It's identical to RecordIDEQ.
func RecordID(v string) predicate.AppDataRecordRevision {
	return predicate.AppDataRecordRevision(sql.FieldEQ(FieldRecordID, v))
}

// SpaceID applies equality check predicate on the "space_id" field. It's identical to SpaceIDEQ.
func SpaceID(v string) predicate.AppDataRecordRevision {
	return predicate.AppDataRecordRevision(sql.FieldEQ(FieldSpaceID, v))
}

// ModelID applies equality check predicate on the "model_id" field. It's identical to ModelIDEQ.
func ModelID(v string) predicate.AppDataRecordRevision {
	return predicate.AppDataRecordRevision(sql.FieldEQ(FieldModelID, v))
}

// ModelKey applies equality check predicate on the "model_key" field. It's identical to ModelKeyEQ.
func ModelKey(v string) predicate.AppDataRecordRevision {
	return predicate.AppDataRecordRevision(sql.FieldEQ(FieldModelKey, v))
}

// Revision applies equality check predicate on the "revision" field. It's identical to RevisionEQ.
func Revision(v int) predicate.AppDataRecordRevision {
	return predicate.AppDataRecordRevision(sql.FieldEQ(FieldRevision, v))
}

// Operation applies equality check predicate on the "operation" field. It's identical to OperationEQ.
func Operation(v string) predicate.AppDataRecordRevision {
	return predicate.AppDataRecordRevision(sql.FieldEQ(FieldOperation, v))
}

// ActorUserID applies equality check predicate on the "actor_user_id" field. It's identical to ActorUserIDEQ.
func ActorUserID(v string) predicate.AppDataRecordRevision {
	return predicate.AppDataRecordRevision(sql.FieldEQ(FieldActorUserID, v))
}

// ActorMemberID applies equality check predicate on the "actor_member_id" field. It's identical to ActorMemberIDEQ.
func ActorMemberID(v string) predicate.AppDataRecordRevision {
	return predicate.AppDataRecordRevision(sql.FieldEQ(FieldActorMemberID, v))
}

// ActorUserMemberID applies equality check predicate on the "actor_user_member_id" field. It's identical to ActorUserMemberIDEQ.
func ActorUserMemberID(v string) predicate.AppDataRecordRevision {
	return predicate.AppDataRecordRevision(sql.FieldEQ(FieldActorUserMemberID, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.AppDataRecordRevision {
	return predicate.AppDataRecordRevision(sql.FieldEQ(FieldCreatedAt, v))
}

// RecordIDEQ applies the EQ predicate on the "record_id" field.
func RecordIDEQ(v string) predicate.AppDataRecordRevision {
	return predicate.AppDataRecordRevision(sql.FieldEQ(FieldRecordID, v))
}

// RecordIDNEQ applies the NEQ predicate on the "record_id" field.
func RecordIDNEQ(v string) predicate.AppDataRecordRevision {
	return predicate.AppDataRecordRevision(sql.FieldNEQ(FieldRecordID, v))
}

// RecordIDIn applies the In predicate on the "record_id" field.
func RecordIDIn(vs ...string) predicate.AppDataRecordRevision {
	return predicate.AppDataRecordRevision(sql.FieldIn(FieldRecordID, vs...))
}

// RecordIDNotIn applies the NotIn predicate on the "record_id" field.
func RecordIDNotIn(vs ...string) predicate.AppDataRecordRevision {
	return predicate.AppDataRecordRevision(sql.FieldNotIn(FieldRecordID, vs...))
}

// RecordIDGT applies the GT predicate on the "record_id" field.
func RecordIDGT(v string) predicate.AppDataRecordRevision {
	return predicate.AppDataRecordRevision(sql.FieldGT(FieldRecordID, v))
}

// RecordIDGTE applies the GTE predicate on the "record_id" field.
func RecordIDGTE(v string) predicate.AppDataRecordRevision {
	return predicate.AppDataRecordRevision(sql.FieldGTE(FieldRecordID, v))
}

// RecordIDLT applies the LT predicate on the "record_id" field.
func RecordIDLT(v string) predicate.AppDataRecordRevision {
	return predicate.AppDataRecordRevision(sql.FieldLT(FieldRecordID, v))
}

// RecordIDLTE applies the LTE predicate on the "record_id" field.
func RecordIDLTE(v string) predicate.AppDataRecordRevision {
	return predicate.AppDataRecordRevision(sql.FieldLTE(FieldRecordID, v))
}

// RecordIDContains applies the Contains predicate on the "record_id" field.
func RecordIDContains(v string) predicate.AppDataRecordRevision {
	return predicate.AppDataRecordRevision(sql.FieldContains(FieldRecordID, v))
}

// RecordIDHasPrefix applies the HasPrefix predicate on the "record_id" field.
func RecordIDHasPrefix(v string) predicate.AppDataRecordRevision {
	return predicate.AppDataRecordRevision(sql.FieldHasPrefix(FieldRecordID, v))
}

// RecordIDHasSuffix applies the HasSuffix predicate on the "record_id" field.
func RecordIDHasSuffix(v string) predicate.AppDataRecordRevision {
	return predicate.AppDataRecordRevision(sql.FieldHasSuffix(FieldRecordID, v))
}

// RecordIDEqualFold applies the EqualFold predicate on the "record_id" field.
func RecordIDEqualFold(v string) predicate.AppDataRecordRevision {
	return predicate.AppDataRecordRevision(sql.FieldEqualFold(FieldRecordID, v))
}

// RecordIDContainsFold applies the ContainsFold predicate on the "record_id" field.
func RecordIDContainsFold(v string) predicate.AppDataRecordRevision {
	return predicate.AppDataRecordRevision(sql.FieldContainsFold(FieldRecordID, v))
}

// SpaceIDEQ applies the EQ predicate on the "space_id" field.
func SpaceIDEQ(v string) predicate.AppDataRecordRevision {
	return predicate.AppDataRecordRevision(sql.FieldEQ(FieldSpaceID, v))
}

// SpaceIDNEQ applies the NEQ predicate on the "space_id" field.
func SpaceIDNEQ(v string) predicate.AppDataRecordRevision {
	return predicate.AppDataRecordRevision(sql.FieldNEQ(FieldSpaceID, v))
}

// SpaceIDIn applies the In predicate on the "space_id" field.
func SpaceIDIn(vs ...string) predicate.AppDataRecordRevision {
	return predicate.AppDataRecordRevision(sql.FieldIn(FieldSpaceID, vs...))
}

// SpaceIDNotIn applies the NotIn predicate on the "space_id" field.
func SpaceIDNotIn(vs ...string) predicate.AppDataRecordRevision {
	return predicate.AppDataRecordRevision(sql.FieldNotIn(FieldSpaceID, vs...))
}

// SpaceIDGT applies the GT predicate on the "space_id" field.
func SpaceIDGT(v string) predicate.AppDataRecordRevision {
	return predicate.AppDataRecordRevision(sql.FieldGT(FieldSpaceID, v))
}

// SpaceIDGTE applies the GTE predicate on the "space_id" field.
func SpaceIDGTE(v string) predicate.AppDataRecordRevision {
	return predicate.AppDataRecordRevision(sql.FieldGTE(FieldSpaceID, v))
}

// SpaceIDLT applies the LT predicate on the "space_id" field.
func SpaceIDLT(v string) predicate.AppDataRecordRevision {
	return predicate.AppDataRecordRevision(sql.FieldLT(FieldSpaceID, v))
}

// SpaceIDLTE applies the LTE predicate on the "space_id" field.
func SpaceIDLTE(v string) predicate.AppDataRecordRevision {
	return predicate.AppDataRecordRevision(sql.FieldLTE(FieldSpaceID, v))
}

// SpaceIDContains applies the Contains predicate on the "space_id" field.
func SpaceIDContains(v string) predicate.AppDataRecordRevision {
	return predicate.AppDataRecordRevision(sql.FieldContains(FieldSpaceID, v))
}

// SpaceIDHasPrefix applies the HasPrefix predicate on the "space_id" field.
func SpaceIDHasPrefix(v string) predicate.AppDataRecordRevision {
	return predicate.AppDataRecordRevision(sql.FieldHasPrefix(FieldSpaceID, v))
}

// SpaceIDHasSuffix applies the HasSuffix predicate on the "space_id" field.
func SpaceIDHasSuffix(v string) predicate.AppDataRecordRevision {
	return predicate.AppDataRecordRevision(sql.FieldHasSuffix(FieldSpaceID, v))
}

// SpaceIDEqualFold applies the EqualFold predicate on the "space_id" field.
func SpaceIDEqualFold(v string) predicate.AppDataRecordRevision {
	return predicate.AppDataRecordRevision(sql.FieldEqualFold(FieldSpaceID, v))
}

// SpaceIDContainsFold applies the ContainsFold predicate on the "space_id" field.
func SpaceIDContainsFold(v string) predicate.AppDataRecordRevision {
	return predicate.AppDataRecordRevision(sql.FieldContainsFold(FieldSpaceID, v))
}

// ModelIDEQ applies the EQ predicate on the "model_id" field.
func ModelIDEQ(v string) predicate.AppDataRecordRevision {
	return predicate.AppDataRecordRevision(sql.FieldEQ(FieldModelID, v))
}

// ModelIDNEQ applies the NEQ predicate on the "model_id" field.
func ModelIDNEQ(v string) predicate.AppDataRecordRevision {
	return predicate.AppDataRecordRevision(sql.FieldNEQ(FieldModelID, v))
}

// ModelIDIn applies the In predicate on the "model_id" field.
func ModelIDIn(vs ...string) predicate.AppDataRecordRevision {
	return predicate.AppDataRecordRevision(sql.FieldIn(FieldModelID, vs...))
}

// ModelIDNotIn applies the NotIn predicate on the "model_id" field.
func ModelIDNotIn(vs ...string) predicate.AppDataRecordRevision {
	return predicate.AppDataRecordRevision(sql.FieldNotIn(FieldModelID, vs...))
}

// ModelIDGT applies the GT predicate on the "model_id" field.
func ModelIDGT(v string) predicate.AppDataRecordRevision {
	return predicate.AppDataRecordRevision(sql.FieldGT(FieldModelID, v))
}

// ModelIDGTE applies the GTE predicate on the "model_id" field.
func ModelIDGTE(v string) predicate.AppDataRecordRevision {
	return predicate.AppDataRecordRevision(sql.FieldGTE(FieldModelID, v))
}

// ModelIDLT applies the LT predicate on the "model_id" field.
func ModelIDLT(v string) predicate.AppDataRecordRevision {
	return predicate.AppDataRecordRevision(sql.FieldLT(FieldModelID, v))
}

// ModelIDLTE applies the LTE predicate on the "model_id" field.
func ModelIDLTE(v string) predicate.AppDataRecordRevision {
	return predicate.AppDataRecordRevision(sql.FieldLTE(FieldModelID, v))
}

// ModelIDContains applies the Contains predicate on the "model_id" field.
func ModelIDContains(v string) predicate.AppDataRecordRevision {
	return predicate.AppDataRecordRevision(sql.FieldContains(FieldModelID, v))
}

// ModelIDHasPrefix applies the HasPrefix predicate on the "model_id" field.
func ModelIDHasPrefix(v string) predicate.AppDataRecordRevision {
	return predicate.AppDataRecordRevision(sql.FieldHasPrefix(FieldModelID, v))
}

// ModelIDHasSuffix applies the HasSuffix predicate on the "model_id" field.
func ModelIDHasSuffix(v string) predicate.AppDataRecordRevision {
	return predicate.AppDataRecordRevision(sql.FieldHasSuffix(FieldModelID, v))
}

// ModelIDEqualFold applies the EqualFold predicate on the "model_id" field.
func ModelIDEqualFold(v string) predicate.AppDataRecordRevision {
	return predicate.AppDataRecordRevision(sql.FieldEqualFold(FieldModelID, v))
}

// ModelIDContainsFold applies the ContainsFold predicate on the "model_id" field.
func ModelIDContainsFold(v string) predicate.AppDataRecordRevision {
	return predicate.AppDataRecordRevision(sql.FieldContainsFold(FieldModelID, v))
}

// ModelKeyEQ applies the EQ predicate on the "model_key" field.
func ModelKeyEQ(v string) predicate.AppDataRecordRevision {
	return predicate.AppDataRecordRevision(sql.FieldEQ(FieldModelKey, v))
}

// ModelKeyNEQ applies the NEQ predicate on the "model_key" field.
func ModelKeyNEQ(v string) predicate.AppDataRecordRevision {
	return predicate.AppDataRecordRevision(sql.FieldNEQ(FieldModelKey, v))
}

// ModelKeyIn applies the In predicate on the "model_key" field.
func ModelKeyIn(vs ...string) predicate.AppDataRecordRevision {
	return predicate.AppDataRecordRevision(sql.FieldIn(FieldModelKey, vs...))
}

// ModelKeyNotIn applies the NotIn predicate on the "model_key" field.
func ModelKeyNotIn(vs ...string) predicate.AppDataRecordRevision {
	return predicate.AppDataRecordRevision(sql.FieldNotIn(FieldModelKey, vs...))
}

// ModelKeyGT applies the GT predicate on the "model_key" field.
func ModelKeyGT(v string) predicate.AppDataRecordRevision {
	return predicate.AppDataRecordRevision(sql.FieldGT(FieldModelKey, v))
}

// ModelKeyGTE applies the GTE predicate on the "model_key" field.
func ModelKeyGTE(v string) predicate.AppDataRecordRevision {
	return predicate.AppDataRecordRevision(sql.FieldGTE(FieldModelKey, v))
}

// ModelKeyLT applies the LT predicate on the "model_key" field.
func ModelKeyLT(v string) predicate.AppDataRecordRevision {
	return predicate.AppDataRecordRevision(sql.FieldLT(FieldModelKey, v))
}

// ModelKeyLTE applies the LTE predicate on the "model_key" field.
func ModelKeyLTE(v string) predicate.AppDataRecordRevision {
	return predicate.AppDataRecordRevision(sql.FieldLTE(FieldModelKey, v))
}

// ModelKeyContains applies the Contains predicate on the "model_key" field.
func ModelKeyContains(v string) predicate.AppDataRecordRevision {
	return predicate.AppDataRecordRevision(sql.FieldContains(FieldModelKey, v))
}

// ModelKeyHasPrefix applies the HasPrefix predicate on the "model_key" field.
func ModelKeyHasPrefix(v string) predicate.AppDataRecordRevision {
	return predicate.AppDataRecordRevision(sql.FieldHasPrefix(FieldModelKey, v))
}

// ModelKeyHasSuffix applies the HasSuffix predicate on the "model_key" field.
func ModelKeyHasSuffix(v string) predicate.AppDataRecordRevision {
	return predicate.AppDataRecordRevision(sql.FieldHasSuffix(FieldModelKey, v))
}

// ModelKeyEqualFold applies the EqualFold predicate on the "model_key" field.
func ModelKeyEqualFold(v string) predicate.AppDataRecordRevision {
	return predicate.AppDataRecordRevision(sql.FieldEqualFold(FieldModelKey, v))
}

// ModelKeyContainsFold applies the ContainsFold predicate on the "model_key" field.
func ModelKeyContainsFold(v string) predicate.AppDataRecordRevision {
	return predicate.AppDataRecordRevision(sql.FieldContainsFold(FieldModelKey, v))
}

// RevisionEQ applies the EQ predicate on the "revision" field.
func RevisionEQ(v int) predicate.AppDataRecordRevision {
	return predicate.AppDataRecordRevision(sql.FieldEQ(FieldRevision, v))
}

// RevisionNEQ applies the NEQ predicate on the "revision" field.
func RevisionNEQ(v int) predicate.AppDataRecordRevision {
	return predicate.AppDataRecordRevision(sql.FieldNEQ(FieldRevision, v))
}

// RevisionIn applies the In predicate on the "revision" field.
func RevisionIn(vs ...int) predicate.AppDataRecordRevision {
	return predicate.AppDataRecordRevision(sql.FieldIn(FieldRevision, vs...))
}

// RevisionNotIn applies the NotIn predicate on the "revision" field.
func RevisionNotIn(vs ...int) predicate.AppDataRecordRevision {
	return predicate.AppDataRecordRevision(sql.FieldNotIn(FieldRevision, vs...))
}

// RevisionGT applies the GT predicate on the "revision" field.
func RevisionGT(v int) predicate.AppDataRecordRevision {
	return predicate.AppDataRecordRevision(sql.FieldGT(FieldRevision, v))
}

// RevisionGTE applies the GTE predicate on the "revision" field.
func RevisionGTE(v int) predicate.AppDataRecordRevision {
	return predicate.AppDataRecordRevision(sql.FieldGTE(FieldRevision, v))
}

// RevisionLT applies the LT predicate on the "revision" field.
func RevisionLT(v int) predicate.AppDataRecordRevision {
	return predicate.AppDataRecordRevision(sql.FieldLT(FieldRevision, v))
}

// RevisionLTE applies the LTE predicate on the "revision" field.
func RevisionLTE(v int) predicate.AppDataRecordRevision {
	return predicate.AppDataRecordRevision(sql.FieldLTE(FieldRevision, v))
}

// OperationEQ applies the EQ predicate on the "operation" field.
func OperationEQ(v string) predicate.AppDataRecordRevision {
	return predicate.AppDataRecordRevision(sql.FieldEQ(FieldOperation, v))
}

// OperationNEQ applies the NEQ predicate on the "operation" field.
func OperationNEQ(v string) predicate.AppDataRecordRevision {
	return predicate.AppDataRecordRevision(sql.FieldNEQ(FieldOperation, v))
}

// OperationIn applies the In predicate on the "operation" field.
func OperationIn(vs ...string) predicate.AppDataRecordRevision {
	return predicate.AppDataRecordRevision(sql.FieldIn(FieldOperation, vs...))
}

// OperationNotIn applies the NotIn predicate on the "operation" field.
func OperationNotIn(vs ...string) predicate.AppDataRecordRevision {
	return predicate.AppDataRecordRevision(sql.FieldNotIn(FieldOperation, vs...))
}

// OperationGT applies the GT predicate on the "operation" field.
func OperationGT(v string) predicate.AppDataRecordRevision {
	return predicate.AppDataRecordRevision(sql.FieldGT(FieldOperation, v))
}

// OperationGTE applies the GTE predicate on the "operation" field.
func OperationGTE(v string) predicate.AppDataRecordRevision {
	return predicate.AppDataRecordRevision(sql.FieldGTE(FieldOperation, v))
}

// OperationLT applies the LT predicate on the "operation" field.
func OperationLT(v string) predicate.AppDataRecordRevision {
	return predicate.AppDataRecordRevision(sql.FieldLT(FieldOperation, v))
}

// OperationLTE applies the LTE predicate on the "operation" field.
func OperationLTE(v string) predicate.AppDataRecordRevision {
	return predicate.AppDataRecordRevision(sql.FieldLTE(FieldOperation, v))
}

// OperationContains applies the Contains predicate on the "operation" field.
func OperationContains(v string) predicate.AppDataRecordRevision {
	return predicate.AppDataRecordRevision(sql.FieldContains(FieldOperation, v))
}

// OperationHasPrefix applies the HasPrefix predicate on the "operation" field.
func OperationHasPrefix(v string) predicate.AppDataRecordRevision {
	return predicate.AppDataRecordRevision(sql.FieldHasPrefix(FieldOperation, v))
}

// OperationHasSuffix applies the HasSuffix predicate on the "operation" field.
func OperationHasSuffix(v string) predicate.AppDataRecordRevision {
	return predicate.AppDataRecordRevision(sql.FieldHasSuffix(FieldOperation, v))
}

// OperationEqualFold applies the EqualFold predicate on the "operation" field.
func OperationEqualFold(v string) predicate.AppDataRecordRevision {
	return predicate.AppDataRecordRevision(sql.FieldEqualFold(FieldOperation, v))
}

// OperationContainsFold applies the ContainsFold predicate on the "operation" field.
func OperationContainsFold(v string) predicate.AppDataRecordRevision {
	return predicate.AppDataRecordRevision(sql.FieldContainsFold(FieldOperation, v))
}

// ActorUserIDEQ applies the EQ predicate on the "actor_user_id" field.
func ActorUserIDEQ(v string) predicate.AppDataRecordRevision {
	return predicate.AppDataRecordRevision(sql.FieldEQ(FieldActorUserID, v))
}

// ActorUserIDNEQ applies the NEQ predicate on the "actor_user_id" field.
func ActorUserIDNEQ(v string) predicate.AppDataRecordRevision {
	return predicate.AppDataRecordRevision(sql.FieldNEQ(FieldActorUserID, v))
}

// ActorUserIDIn applies the In predicate on the "actor_user_id" field.
func ActorUserIDIn(vs ...string) predicate.AppDataRecordRevision {
	return predicate.AppDataRecordRevision(sql.FieldIn(FieldActorUserID, vs...))
}

// ActorUserIDNotIn applies the NotIn predicate on the "actor_user_id" field.
func ActorUserIDNotIn(vs ...string) predicate.AppDataRecordRevision {
	return predicate.AppDataRecordRevision(sql.FieldNotIn(FieldActorUserID, vs...))
}

// ActorUserIDGT applies the GT predicate on the "actor_user_id" field.
func ActorUserIDGT(v string) predicate.AppDataRecordRevision {
	return predicate.AppDataRecordRevision(sql.FieldGT(FieldActorUserID, v))
}

// ActorUserIDGTE applies the GTE predicate on the "actor_user_id" field.
func ActorUserIDGTE(v string) predicate.AppDataRecordRevision {
	return predicate.AppDataRecordRevision(sql.FieldGTE(FieldActorUserID, v))
}

// ActorUserIDLT applies the LT predicate on the "actor_user_id" field.
func ActorUserIDLT(v string) predicate.AppDataRecordRevision {
	return predicate.AppDataRecordRevision(sql.FieldLT(FieldActorUserID, v))
}

// ActorUserIDLTE applies the LTE predicate on the "actor_user_id" field.
func ActorUserIDLTE(v string) predicate.AppDataRecordRevision {
	return predicate.AppDataRecordRevision(sql.FieldLTE(FieldActorUserID, v))
}

// ActorUserIDContains applies the Contains predicate on the "actor_user_id" field.
func ActorUserIDContains(v string) predicate.AppDataRecordRevision {
	return predicate.AppDataRecordRevision(sql.FieldContains(FieldActorUserID, v))
}

// ActorUserIDHasPrefix applies the HasPrefix predicate on the "actor_user_id" field.
func ActorUserIDHasPrefix(v string) predicate.AppDataRecordRevision {
	return predicate.AppDataRecordRevision(sql.FieldHasPrefix(FieldActorUserID, v))
}

// ActorUserIDHasSuffix applies the HasSuffix predicate on the "actor_user_id" field.
func ActorUserIDHasSuffix(v string) predicate.AppDataRecordRevision {
	return predicate.AppDataRecordRevision(sql.FieldHasSuffix(FieldActorUserID, v))
}

// ActorUserIDIsNil applies the IsNil predicate on the "actor_user_id" field.
func ActorUserIDIsNil() predicate.AppDataRecordRevision {
	return predicate.AppDataRecordRevision(sql.FieldIsNull(FieldActorUserID))
}

// ActorUserIDNotNil applies the NotNil predicate on the "actor_user_id" field.
func ActorUserIDNotNil() predicate.AppDataRecordRevision {
	return predicate.AppDataRecordRevision(sql.FieldNotNull(FieldActorUserID))
}

// ActorUserIDEqualFold applies the EqualFold predicate on the "actor_user_id" field.
func ActorUserIDEqualFold(v string) predicate.AppDataRecordRevision {
	return predicate.AppDataRecordRevision(sql.FieldEqualFold(FieldActorUserID, v))
}

// ActorUserIDContainsFold applies the ContainsFold predicate on the "actor_user_id" field.
func ActorUserIDContainsFold(v string) predicate.AppDataRecordRevision {
	return predicate.AppDataRecordRevision(sql.FieldContainsFold(FieldActorUserID, v))
}

// ActorMemberIDEQ applies the EQ predicate on the "actor_member_id" field.
func ActorMemberIDEQ(v string) predicate.AppDataRecordRevision {
	return predicate.AppDataRecordRevision(sql.FieldEQ(FieldActorMemberID, v))
}

// ActorMemberIDNEQ applies the NEQ predicate on the "actor_member_id" field.
func ActorMemberIDNEQ(v string) predicate.AppDataRecordRevision {
	return predicate.AppDataRecordRevision(sql.FieldNEQ(FieldActorMemberID, v))
}

// ActorMemberIDIn applies the In predicate on the "actor_member_id" field.
func ActorMemberIDIn(vs ...string) predicate.AppDataRecordRevision {
	return predicate.AppDataRecordRevision(sql.FieldIn(FieldActorMemberID, vs...))
}

// ActorMemberIDNotIn applies the NotIn predicate on the "actor_member_id" field.
func ActorMemberIDNotIn(vs ...string) predicate.AppDataRecordRevision {
	return predicate.AppDataRecordRevision(sql.FieldNotIn(FieldActorMemberID, vs...))
}

// ActorMemberIDGT applies the GT predicate on the "actor_member_id" field.
func ActorMemberIDGT(v string) predicate.AppDataRecordRevision {
	return predicate.AppDataRecordRevision(sql.FieldGT(FieldActorMemberID, v))
}

// ActorMemberIDGTE applies the GTE predicate on the "actor_member_id" field.
func ActorMemberIDGTE(v string) predicate.AppDataRecordRevision {
	return predicate.AppDataRecordRevision(sql.FieldGTE(FieldActorMemberID, v))
}

// ActorMemberIDLT applies the LT predicate on the "actor_member_id" field.
func ActorMemberIDLT(v string) predicate.AppDataRecordRevision {
	return predicate.AppDataRecordRevision(sql.FieldLT(FieldActorMemberID, v))
}

// ActorMemberIDLTE applies the LTE predicate on the "actor_member_id" field.
func ActorMemberIDLTE(v string) predicate.AppDataRecordRevision {
	return predicate.AppDataRecordRevision(sql.FieldLTE(FieldActorMemberID, v))
}

// ActorMemberIDContains applies the Contains predicate on the "actor_member_id" field.
func ActorMemberIDContains(v string) predicate.AppDataRecordRevision {
	return predicate.AppDataRecordRevision(sql.FieldContains(FieldActorMemberID, v))
}

// ActorMemberIDHasPrefix applies the HasPrefix predicate on the "actor_member_id" field.
func ActorMemberIDHasPrefix(v string) predicate.AppDataRecordRevision {
	return predicate.AppDataRecordRevision(sql.FieldHasPrefix(FieldActorMemberID, v))
}

// ActorMemberIDHasSuffix applies the HasSuffix predicate on the "actor_member_id" field.
func ActorMemberIDHasSuffix(v string) predicate.AppDataRecordRevision {
	return predicate.AppDataRecordRevision(sql.FieldHasSuffix(FieldActorMemberID, v))
}

// ActorMemberIDIsNil applies the IsNil predicate on the "actor_member_id" field.
func ActorMemberIDIsNil() predicate.AppDataRecordRevision {
	return predicate.AppDataRecordRevision(sql.FieldIsNull(FieldActorMemberID))
}

// ActorMemberIDNotNil applies the NotNil predicate on the "actor_member_id" field.
func ActorMemberIDNotNil() predicate.AppDataRecordRevision {
	return predicate.AppDataRecordRevision(sql.FieldNotNull(FieldActorMemberID))
}

// ActorMemberIDEqualFold applies the EqualFold predicate on the "actor_member_id" field.
func ActorMemberIDEqualFold(v string) predicate.AppDataRecordRevision {
	return predicate.AppDataRecordRevision(sql.FieldEqualFold(FieldActorMemberID, v))
}

// ActorMemberIDContainsFold applies the ContainsFold predicate on the "actor_member_id" field.
func ActorMemberIDContainsFold(v string) predicate.AppDataRecordRevision {
	return predicate.AppDataRecordRevision(sql.FieldContainsFold(FieldActorMemberID, v))
}

// ActorUserMemberIDEQ applies the EQ predicate on the "actor_user_member_id" field.
func ActorUserMemberIDEQ(v string) predicate.AppDataRecordRevision {
	return predicate.AppDataRecordRevision(sql.FieldEQ(FieldActorUserMemberID, v))
}

// ActorUserMemberIDNEQ applies the NEQ predicate on the "actor_user_member_id" field.
func ActorUserMemberIDNEQ(v string) predicate.AppDataRecordRevision {
	return predicate.AppDataRecordRevision(sql.FieldNEQ(FieldActorUserMemberID, v))
}

// ActorUserMemberIDIn applies the In predicate on the "actor_user_member_id" field.
func ActorUserMemberIDIn(vs ...string) predicate.AppDataRecordRevision {
	return predicate.AppDataRecordRevision(sql.FieldIn(FieldActorUserMemberID, vs...))
}

// ActorUserMemberIDNotIn applies the NotIn predicate on the "actor_user_member_id" field.
func ActorUserMemberIDNotIn(vs ...string) predicate.AppDataRecordRevision {
	return predicate.AppDataRecordRevision(sql.FieldNotIn(FieldActorUserMemberID, vs...))
}

// ActorUserMemberIDGT applies the GT predicate on the "actor_user_member_id" field.
func ActorUserMemberIDGT(v string) predicate.AppDataRecordRevision {
	return predicate.AppDataRecordRevision(sql.FieldGT(FieldActorUserMemberID, v))
}

// ActorUserMemberIDGTE applies the GTE predicate on the "actor_user_member_id" field.
func ActorUserMemberIDGTE(v string) predicate.AppDataRecordRevision {
	return predicate.AppDataRecordRevision(sql.FieldGTE(FieldActorUserMemberID, v))
}

// ActorUserMemberIDLT applies the LT predicate on the "actor_user_member_id" field.
func ActorUserMemberIDLT(v string) predicate.AppDataRecordRevision {
	return predicate.AppDataRecordRevision(sql.FieldLT(FieldActorUserMemberID, v))
}

// ActorUserMemberIDLTE applies the LTE predicate on the "actor_user_member_id" field.
func ActorUserMemberIDLTE(v string) predicate.AppDataRecordRevision {
	return predicate.AppDataRecordRevision(sql.FieldLTE(FieldActorUserMemberID, v))
}

// ActorUserMemberIDContains applies the Contains predicate on the "actor_user_member_id" field.
func ActorUserMemberIDContains(v string) predicate.AppDataRecordRevision {
	return predicate.AppDataRecordRevision(sql.FieldContains(FieldActorUserMemberID, v))
}

// ActorUserMemberIDHasPrefix applies the HasPrefix predicate on the "actor_user_member_id" field.
func ActorUserMemberIDHasPrefix(v string) predicate.AppDataRecordRevision {
	return predicate.AppDataRecordRevision(sql.FieldHasPrefix(FieldActorUserMemberID, v))
}

// ActorUserMemberIDHasSuffix applies the HasSuffix predicate on the "actor_user_member_id" field.
func ActorUserMemberIDHasSuffix(v string) predicate.AppDataRecordRevision {
	return predicate.AppDataRecordRevision(sql.FieldHasSuffix(FieldActorUserMemberID, v))
}

// ActorUserMemberIDIsNil applies the IsNil predicate on the "actor_user_member_id" field.
func ActorUserMemberIDIsNil() predicate.AppDataRecordRevision {
	return predicate.AppDataRecordRevision(sql.FieldIsNull(FieldActorUserMemberID))
}

// ActorUserMemberIDNotNil applies the NotNil predicate on the "actor_user_member_id" field.
func ActorUserMemberIDNotNil() predicate.AppDataRecordRevision {
	return predicate.AppDataRecordRevision(sql.FieldNotNull(FieldActorUserMemberID))
}

// ActorUserMemberIDEqualFold applies the EqualFold predicate on the "actor_user_member_id" field.
func ActorUserMemberIDEqualFold(v string) predicate.AppDataRecordRevision {
	return predicate.AppDataRecordRevision(sql.FieldEqualFold(FieldActorUserMemberID, v))
}

// ActorUserMemberIDContainsFold applies the ContainsFold predicate on the "actor_user_member_id" field.
func ActorUserMemberIDContainsFold(v string) predicate.AppDataRecordRevision {
	return predicate.AppDataRecordRevision(sql.FieldContainsFold(FieldActorUserMemberID, v))
}

// MetadataIsNil applies the IsNil predicate on the "metadata" field.
func MetadataIsNil() predicate.AppDataRecordRevision {
	return predicate.AppDataRecordRevision(sql.FieldIsNull(FieldMetadata))
}

// MetadataNotNil applies the NotNil predicate on the "metadata" field.
func MetadataNotNil() predicate.AppDataRecordRevision {
	return predicate.AppDataRecordRevision(sql.FieldNotNull(FieldMetadata))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.AppDataRecordRevision {
	return predicate.AppDataRecordRevision(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.AppDataRecordRevision {
	return predicate.AppDataRecordRevision(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.AppDataRecordRevision {
	return predicate.AppDataRecordRevision(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.AppDataRecordRevision {
	return predicate.AppDataRecordRevision(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.AppDataRecordRevision {
	return predicate.AppDataRecordRevision(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.AppDataRecordRevision {
	return predicate.AppDataRecordRevision(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.AppDataRecordRevision {
	return predicate.AppDataRecordRevision(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.AppDataRecordRevision {
	return predicate.AppDataRecordRevision(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AppDataRecordRevision) predicate.AppDataRecordRevision {
	return predicate.AppDataRecordRevision(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AppDataRecordRevision) predicate.AppDataRecordRevision {
	return predicate.AppDataRecordRevision(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AppDataRecordRevision) predicate.AppDataRecordRevision {
	return predicate.AppDataRecordRevision(sql.NotPredicates(p))
}
