// Code generated by ent, DO NOT EDIT.

package providermigrationstep

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/plystra/core/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldContainsFold(FieldID, id))
}

// RevisionID applies equality check predicate on the "revision_id" field. It's identical to RevisionIDEQ.
func RevisionID(v string) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldEQ(FieldRevisionID, v))
}

// ProviderPluginID applies equality check predicate on the "provider_plugin_id" field. It's identical to ProviderPluginIDEQ.
func ProviderPluginID(v string) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldEQ(FieldProviderPluginID, v))
}

// StepIndex applies equality check predicate on the "step_index" field. It's identical to StepIndexEQ.
func StepIndex(v int) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldEQ(FieldStepIndex, v))
}

// StatementHash applies equality check predicate on the "statement_hash" field. It's identical to StatementHashEQ.
func StatementHash(v string) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldEQ(FieldStatementHash, v))
}

// StatementKind applies equality check predicate on the "statement_kind" field. It's identical to StatementKindEQ.
func StatementKind(v string) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldEQ(FieldStatementKind, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldEQ(FieldStatus, v))
}

// Destructive applies equality check predicate on the "destructive" field. It's identical to DestructiveEQ.
func Destructive(v bool) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldEQ(FieldDestructive, v))
}

// Backfill applies equality check predicate on the "backfill" field. It's identical to BackfillEQ.
func Backfill(v bool) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldEQ(FieldBackfill, v))
}

// TenantScopeReviewed applies equality check predicate on the "tenant_scope_reviewed" field. It's identical to TenantScopeReviewedEQ.
func TenantScopeReviewed(v bool) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldEQ(FieldTenantScopeReviewed, v))
}

// RlsBypass applies equality check predicate on the "rls_bypass" field. It's identical to RlsBypassEQ.
func RlsBypass(v bool) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldEQ(FieldRlsBypass, v))
}

// Precondition applies equality check predicate on the "precondition" field. It's identical to PreconditionEQ.
func Precondition(v string) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldEQ(FieldPrecondition, v))
}

// RecoveryAction applies equality check predicate on the "recovery_action" field. It's identical to RecoveryActionEQ.
func RecoveryAction(v string) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldEQ(FieldRecoveryAction, v))
}

// StartedAt applies equality check predicate on the "started_at" field. It's identical to StartedAtEQ.
func StartedAt(v time.Time) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldEQ(FieldStartedAt, v))
}

// FinishedAt applies equality check predicate on the "finished_at" field. It's identical to FinishedAtEQ.
func FinishedAt(v time.Time) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldEQ(FieldFinishedAt, v))
}

// Error applies equality check predicate on the "error" field. It's identical to ErrorEQ.
func Error(v string) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldEQ(FieldError, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldEQ(FieldUpdatedAt, v))
}

// RevisionIDEQ applies the EQ predicate on the "revision_id" field.
func RevisionIDEQ(v string) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldEQ(FieldRevisionID, v))
}

// RevisionIDNEQ applies the NEQ predicate on the "revision_id" field.
func RevisionIDNEQ(v string) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldNEQ(FieldRevisionID, v))
}

// RevisionIDIn applies the In predicate on the "revision_id" field.
func RevisionIDIn(vs ...string) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldIn(FieldRevisionID, vs...))
}

// RevisionIDNotIn applies the NotIn predicate on the "revision_id" field.
func RevisionIDNotIn(vs ...string) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldNotIn(FieldRevisionID, vs...))
}

// RevisionIDGT applies the GT predicate on the "revision_id" field.
func RevisionIDGT(v string) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldGT(FieldRevisionID, v))
}

// RevisionIDGTE applies the GTE predicate on the "revision_id" field.
func RevisionIDGTE(v string) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldGTE(FieldRevisionID, v))
}

// RevisionIDLT applies the LT predicate on the "revision_id" field.
func RevisionIDLT(v string) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldLT(FieldRevisionID, v))
}

// RevisionIDLTE applies the LTE predicate on the "revision_id" field.
func RevisionIDLTE(v string) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldLTE(FieldRevisionID, v))
}

// RevisionIDContains applies the Contains predicate on the "revision_id" field.
func RevisionIDContains(v string) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldContains(FieldRevisionID, v))
}

// RevisionIDHasPrefix applies the HasPrefix predicate on the "revision_id" field.
func RevisionIDHasPrefix(v string) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldHasPrefix(FieldRevisionID, v))
}

// RevisionIDHasSuffix applies the HasSuffix predicate on the "revision_id" field.
func RevisionIDHasSuffix(v string) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldHasSuffix(FieldRevisionID, v))
}

// RevisionIDEqualFold applies the EqualFold predicate on the "revision_id" field.
func RevisionIDEqualFold(v string) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldEqualFold(FieldRevisionID, v))
}

// RevisionIDContainsFold applies the ContainsFold predicate on the "revision_id" field.
func RevisionIDContainsFold(v string) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldContainsFold(FieldRevisionID, v))
}

// ProviderPluginIDEQ applies the EQ predicate on the "provider_plugin_id" field.
func ProviderPluginIDEQ(v string) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldEQ(FieldProviderPluginID, v))
}

// ProviderPluginIDNEQ applies the NEQ predicate on the "provider_plugin_id" field.
func ProviderPluginIDNEQ(v string) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldNEQ(FieldProviderPluginID, v))
}

// ProviderPluginIDIn applies the In predicate on the "provider_plugin_id" field.
func ProviderPluginIDIn(vs ...string) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldIn(FieldProviderPluginID, vs...))
}

// ProviderPluginIDNotIn applies the NotIn predicate on the "provider_plugin_id" field.
func ProviderPluginIDNotIn(vs ...string) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldNotIn(FieldProviderPluginID, vs...))
}

// ProviderPluginIDGT applies the GT predicate on the "provider_plugin_id" field.
func ProviderPluginIDGT(v string) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldGT(FieldProviderPluginID, v))
}

// ProviderPluginIDGTE applies the GTE predicate on the "provider_plugin_id" field.
func ProviderPluginIDGTE(v string) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldGTE(FieldProviderPluginID, v))
}

// ProviderPluginIDLT applies the LT predicate on the "provider_plugin_id" field.
func ProviderPluginIDLT(v string) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldLT(FieldProviderPluginID, v))
}

// ProviderPluginIDLTE applies the LTE predicate on the "provider_plugin_id" field.
func ProviderPluginIDLTE(v string) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldLTE(FieldProviderPluginID, v))
}

// ProviderPluginIDContains applies the Contains predicate on the "provider_plugin_id" field.
func ProviderPluginIDContains(v string) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldContains(FieldProviderPluginID, v))
}

// ProviderPluginIDHasPrefix applies the HasPrefix predicate on the "provider_plugin_id" field.
func ProviderPluginIDHasPrefix(v string) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldHasPrefix(FieldProviderPluginID, v))
}

// ProviderPluginIDHasSuffix applies the HasSuffix predicate on the "provider_plugin_id" field.
func ProviderPluginIDHasSuffix(v string) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldHasSuffix(FieldProviderPluginID, v))
}

// ProviderPluginIDEqualFold applies the EqualFold predicate on the "provider_plugin_id" field.
func ProviderPluginIDEqualFold(v string) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldEqualFold(FieldProviderPluginID, v))
}

// ProviderPluginIDContainsFold applies the ContainsFold predicate on the "provider_plugin_id" field.
func ProviderPluginIDContainsFold(v string) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldContainsFold(FieldProviderPluginID, v))
}

// StepIndexEQ applies the EQ predicate on the "step_index" field.
func StepIndexEQ(v int) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldEQ(FieldStepIndex, v))
}

// StepIndexNEQ applies the NEQ predicate on the "step_index" field.
func StepIndexNEQ(v int) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldNEQ(FieldStepIndex, v))
}

// StepIndexIn applies the In predicate on the "step_index" field.
func StepIndexIn(vs ...int) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldIn(FieldStepIndex, vs...))
}

// StepIndexNotIn applies the NotIn predicate on the "step_index" field.
func StepIndexNotIn(vs ...int) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldNotIn(FieldStepIndex, vs...))
}

// StepIndexGT applies the GT predicate on the "step_index" field.
func StepIndexGT(v int) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldGT(FieldStepIndex, v))
}

// StepIndexGTE applies the GTE predicate on the "step_index" field.
func StepIndexGTE(v int) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldGTE(FieldStepIndex, v))
}

// StepIndexLT applies the LT predicate on the "step_index" field.
func StepIndexLT(v int) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldLT(FieldStepIndex, v))
}

// StepIndexLTE applies the LTE predicate on the "step_index" field.
func StepIndexLTE(v int) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldLTE(FieldStepIndex, v))
}

// StatementHashEQ applies the EQ predicate on the "statement_hash" field.
func StatementHashEQ(v string) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldEQ(FieldStatementHash, v))
}

// StatementHashNEQ applies the NEQ predicate on the "statement_hash" field.
func StatementHashNEQ(v string) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldNEQ(FieldStatementHash, v))
}

// StatementHashIn applies the In predicate on the "statement_hash" field.
func StatementHashIn(vs ...string) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldIn(FieldStatementHash, vs...))
}

// StatementHashNotIn applies the NotIn predicate on the "statement_hash" field.
func StatementHashNotIn(vs ...string) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldNotIn(FieldStatementHash, vs...))
}

// StatementHashGT applies the GT predicate on the "statement_hash" field.
func StatementHashGT(v string) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldGT(FieldStatementHash, v))
}

// StatementHashGTE applies the GTE predicate on the "statement_hash" field.
func StatementHashGTE(v string) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldGTE(FieldStatementHash, v))
}

// StatementHashLT applies the LT predicate on the "statement_hash" field.
func StatementHashLT(v string) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldLT(FieldStatementHash, v))
}

// StatementHashLTE applies the LTE predicate on the "statement_hash" field.
func StatementHashLTE(v string) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldLTE(FieldStatementHash, v))
}

// StatementHashContains applies the Contains predicate on the "statement_hash" field.
func StatementHashContains(v string) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldContains(FieldStatementHash, v))
}

// StatementHashHasPrefix applies the HasPrefix predicate on the "statement_hash" field.
func StatementHashHasPrefix(v string) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldHasPrefix(FieldStatementHash, v))
}

// StatementHashHasSuffix applies the HasSuffix predicate on the "statement_hash" field.
func StatementHashHasSuffix(v string) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldHasSuffix(FieldStatementHash, v))
}

// StatementHashEqualFold applies the EqualFold predicate on the "statement_hash" field.
func StatementHashEqualFold(v string) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldEqualFold(FieldStatementHash, v))
}

// StatementHashContainsFold applies the ContainsFold predicate on the "statement_hash" field.
func StatementHashContainsFold(v string) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldContainsFold(FieldStatementHash, v))
}

// StatementKindEQ applies the EQ predicate on the "statement_kind" field.
func StatementKindEQ(v string) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldEQ(FieldStatementKind, v))
}

// StatementKindNEQ applies the NEQ predicate on the "statement_kind" field.
func StatementKindNEQ(v string) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldNEQ(FieldStatementKind, v))
}

// StatementKindIn applies the In predicate on the "statement_kind" field.
func StatementKindIn(vs ...string) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldIn(FieldStatementKind, vs...))
}

// StatementKindNotIn applies the NotIn predicate on the "statement_kind" field.
func StatementKindNotIn(vs ...string) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldNotIn(FieldStatementKind, vs...))
}

// StatementKindGT applies the GT predicate on the "statement_kind" field.
func StatementKindGT(v string) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldGT(FieldStatementKind, v))
}

// StatementKindGTE applies the GTE predicate on the "statement_kind" field.
func StatementKindGTE(v string) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldGTE(FieldStatementKind, v))
}

// StatementKindLT applies the LT predicate on the "statement_kind" field.
func StatementKindLT(v string) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldLT(FieldStatementKind, v))
}

// StatementKindLTE applies the LTE predicate on the "statement_kind" field.
func StatementKindLTE(v string) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldLTE(FieldStatementKind, v))
}

// StatementKindContains applies the Contains predicate on the "statement_kind" field.
func StatementKindContains(v string) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldContains(FieldStatementKind, v))
}

// StatementKindHasPrefix applies the HasPrefix predicate on the "statement_kind" field.
func StatementKindHasPrefix(v string) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldHasPrefix(FieldStatementKind, v))
}

// StatementKindHasSuffix applies the HasSuffix predicate on the "statement_kind" field.
func StatementKindHasSuffix(v string) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldHasSuffix(FieldStatementKind, v))
}

// StatementKindEqualFold applies the EqualFold predicate on the "statement_kind" field.
func StatementKindEqualFold(v string) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldEqualFold(FieldStatementKind, v))
}

// StatementKindContainsFold applies the ContainsFold predicate on the "statement_kind" field.
func StatementKindContainsFold(v string) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldContainsFold(FieldStatementKind, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldContainsFold(FieldStatus, v))
}

// DestructiveEQ applies the EQ predicate on the "destructive" field.
func DestructiveEQ(v bool) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldEQ(FieldDestructive, v))
}

// DestructiveNEQ applies the NEQ predicate on the "destructive" field.
func DestructiveNEQ(v bool) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldNEQ(FieldDestructive, v))
}

// BackfillEQ applies the EQ predicate on the "backfill" field.
func BackfillEQ(v bool) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldEQ(FieldBackfill, v))
}

// BackfillNEQ applies the NEQ predicate on the "backfill" field.
func BackfillNEQ(v bool) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldNEQ(FieldBackfill, v))
}

// TenantScopeReviewedEQ applies the EQ predicate on the "tenant_scope_reviewed" field.
func TenantScopeReviewedEQ(v bool) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldEQ(FieldTenantScopeReviewed, v))
}

// TenantScopeReviewedNEQ applies the NEQ predicate on the "tenant_scope_reviewed" field.
func TenantScopeReviewedNEQ(v bool) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldNEQ(FieldTenantScopeReviewed, v))
}

// RlsBypassEQ applies the EQ predicate on the "rls_bypass" field.
func RlsBypassEQ(v bool) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldEQ(FieldRlsBypass, v))
}

// RlsBypassNEQ applies the NEQ predicate on the "rls_bypass" field.
func RlsBypassNEQ(v bool) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldNEQ(FieldRlsBypass, v))
}

// PreconditionEQ applies the EQ predicate on the "precondition" field.
func PreconditionEQ(v string) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldEQ(FieldPrecondition, v))
}

// PreconditionNEQ applies the NEQ predicate on the "precondition" field.
func PreconditionNEQ(v string) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldNEQ(FieldPrecondition, v))
}

// PreconditionIn applies the In predicate on the "precondition" field.
func PreconditionIn(vs ...string) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldIn(FieldPrecondition, vs...))
}

// PreconditionNotIn applies the NotIn predicate on the "precondition" field.
func PreconditionNotIn(vs ...string) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldNotIn(FieldPrecondition, vs...))
}

// PreconditionGT applies the GT predicate on the "precondition" field.
func PreconditionGT(v string) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldGT(FieldPrecondition, v))
}

// PreconditionGTE applies the GTE predicate on the "precondition" field.
func PreconditionGTE(v string) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldGTE(FieldPrecondition, v))
}

// PreconditionLT applies the LT predicate on the "precondition" field.
func PreconditionLT(v string) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldLT(FieldPrecondition, v))
}

// PreconditionLTE applies the LTE predicate on the "precondition" field.
func PreconditionLTE(v string) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldLTE(FieldPrecondition, v))
}

// PreconditionContains applies the Contains predicate on the "precondition" field.
func PreconditionContains(v string) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldContains(FieldPrecondition, v))
}

// PreconditionHasPrefix applies the HasPrefix predicate on the "precondition" field.
func PreconditionHasPrefix(v string) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldHasPrefix(FieldPrecondition, v))
}

// PreconditionHasSuffix applies the HasSuffix predicate on the "precondition" field.
func PreconditionHasSuffix(v string) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldHasSuffix(FieldPrecondition, v))
}

// PreconditionIsNil applies the IsNil predicate on the "precondition" field.
func PreconditionIsNil() predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldIsNull(FieldPrecondition))
}

// PreconditionNotNil applies the NotNil predicate on the "precondition" field.
func PreconditionNotNil() predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldNotNull(FieldPrecondition))
}

// PreconditionEqualFold applies the EqualFold predicate on the "precondition" field.
func PreconditionEqualFold(v string) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldEqualFold(FieldPrecondition, v))
}

// PreconditionContainsFold applies the ContainsFold predicate on the "precondition" field.
func PreconditionContainsFold(v string) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldContainsFold(FieldPrecondition, v))
}

// RecoveryActionEQ applies the EQ predicate on the "recovery_action" field.
func RecoveryActionEQ(v string) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldEQ(FieldRecoveryAction, v))
}

// RecoveryActionNEQ applies the NEQ predicate on the "recovery_action" field.
func RecoveryActionNEQ(v string) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldNEQ(FieldRecoveryAction, v))
}

// RecoveryActionIn applies the In predicate on the "recovery_action" field.
func RecoveryActionIn(vs ...string) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldIn(FieldRecoveryAction, vs...))
}

// RecoveryActionNotIn applies the NotIn predicate on the "recovery_action" field.
func RecoveryActionNotIn(vs ...string) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldNotIn(FieldRecoveryAction, vs...))
}

// RecoveryActionGT applies the GT predicate on the "recovery_action" field.
func RecoveryActionGT(v string) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldGT(FieldRecoveryAction, v))
}

// RecoveryActionGTE applies the GTE predicate on the "recovery_action" field.
func RecoveryActionGTE(v string) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldGTE(FieldRecoveryAction, v))
}

// RecoveryActionLT applies the LT predicate on the "recovery_action" field.
func RecoveryActionLT(v string) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldLT(FieldRecoveryAction, v))
}

// RecoveryActionLTE applies the LTE predicate on the "recovery_action" field.
func RecoveryActionLTE(v string) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldLTE(FieldRecoveryAction, v))
}

// RecoveryActionContains applies the Contains predicate on the "recovery_action" field.
func RecoveryActionContains(v string) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldContains(FieldRecoveryAction, v))
}

// RecoveryActionHasPrefix applies the HasPrefix predicate on the "recovery_action" field.
func RecoveryActionHasPrefix(v string) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldHasPrefix(FieldRecoveryAction, v))
}

// RecoveryActionHasSuffix applies the HasSuffix predicate on the "recovery_action" field.
func RecoveryActionHasSuffix(v string) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldHasSuffix(FieldRecoveryAction, v))
}

// RecoveryActionIsNil applies the IsNil predicate on the "recovery_action" field.
func RecoveryActionIsNil() predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldIsNull(FieldRecoveryAction))
}

// RecoveryActionNotNil applies the NotNil predicate on the "recovery_action" field.
func RecoveryActionNotNil() predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldNotNull(FieldRecoveryAction))
}

// RecoveryActionEqualFold applies the EqualFold predicate on the "recovery_action" field.
func RecoveryActionEqualFold(v string) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldEqualFold(FieldRecoveryAction, v))
}

// RecoveryActionContainsFold applies the ContainsFold predicate on the "recovery_action" field.
func RecoveryActionContainsFold(v string) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldContainsFold(FieldRecoveryAction, v))
}

// StartedAtEQ applies the EQ predicate on the "started_at" field.
func StartedAtEQ(v time.Time) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldEQ(FieldStartedAt, v))
}

// StartedAtNEQ applies the NEQ predicate on the "started_at" field.
func StartedAtNEQ(v time.Time) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldNEQ(FieldStartedAt, v))
}

// StartedAtIn applies the In predicate on the "started_at" field.
func StartedAtIn(vs ...time.Time) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldIn(FieldStartedAt, vs...))
}

// StartedAtNotIn applies the NotIn predicate on the "started_at" field.
func StartedAtNotIn(vs ...time.Time) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldNotIn(FieldStartedAt, vs...))
}

// StartedAtGT applies the GT predicate on the "started_at" field.
func StartedAtGT(v time.Time) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldGT(FieldStartedAt, v))
}

// StartedAtGTE applies the GTE predicate on the "started_at" field.
func StartedAtGTE(v time.Time) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldGTE(FieldStartedAt, v))
}

// StartedAtLT applies the LT predicate on the "started_at" field.
func StartedAtLT(v time.Time) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldLT(FieldStartedAt, v))
}

// StartedAtLTE applies the LTE predicate on the "started_at" field.
func StartedAtLTE(v time.Time) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldLTE(FieldStartedAt, v))
}

// StartedAtIsNil applies the IsNil predicate on the "started_at" field.
func StartedAtIsNil() predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldIsNull(FieldStartedAt))
}

// StartedAtNotNil applies the NotNil predicate on the "started_at" field.
func StartedAtNotNil() predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldNotNull(FieldStartedAt))
}

// FinishedAtEQ applies the EQ predicate on the "finished_at" field.
func FinishedAtEQ(v time.Time) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldEQ(FieldFinishedAt, v))
}

// FinishedAtNEQ applies the NEQ predicate on the "finished_at" field.
func FinishedAtNEQ(v time.Time) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldNEQ(FieldFinishedAt, v))
}

// FinishedAtIn applies the In predicate on the "finished_at" field.
func FinishedAtIn(vs ...time.Time) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldIn(FieldFinishedAt, vs...))
}

// FinishedAtNotIn applies the NotIn predicate on the "finished_at" field.
func FinishedAtNotIn(vs ...time.Time) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldNotIn(FieldFinishedAt, vs...))
}

// FinishedAtGT applies the GT predicate on the "finished_at" field.
func FinishedAtGT(v time.Time) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldGT(FieldFinishedAt, v))
}

// FinishedAtGTE applies the GTE predicate on the "finished_at" field.
func FinishedAtGTE(v time.Time) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldGTE(FieldFinishedAt, v))
}

// FinishedAtLT applies the LT predicate on the "finished_at" field.
func FinishedAtLT(v time.Time) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldLT(FieldFinishedAt, v))
}

// FinishedAtLTE applies the LTE predicate on the "finished_at" field.
func FinishedAtLTE(v time.Time) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldLTE(FieldFinishedAt, v))
}

// FinishedAtIsNil applies the IsNil predicate on the "finished_at" field.
func FinishedAtIsNil() predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldIsNull(FieldFinishedAt))
}

// FinishedAtNotNil applies the NotNil predicate on the "finished_at" field.
func FinishedAtNotNil() predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldNotNull(FieldFinishedAt))
}

// ErrorEQ applies the EQ predicate on the "error" field.
func ErrorEQ(v string) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldEQ(FieldError, v))
}

// ErrorNEQ applies the NEQ predicate on the "error" field.
func ErrorNEQ(v string) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldNEQ(FieldError, v))
}

// ErrorIn applies the In predicate on the "error" field.
func ErrorIn(vs ...string) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldIn(FieldError, vs...))
}

// ErrorNotIn applies the NotIn predicate on the "error" field.
func ErrorNotIn(vs ...string) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldNotIn(FieldError, vs...))
}

// ErrorGT applies the GT predicate on the "error" field.
func ErrorGT(v string) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldGT(FieldError, v))
}

// ErrorGTE applies the GTE predicate on the "error" field.
func ErrorGTE(v string) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldGTE(FieldError, v))
}

// ErrorLT applies the LT predicate on the "error" field.
func ErrorLT(v string) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldLT(FieldError, v))
}

// ErrorLTE applies the LTE predicate on the "error" field.
func ErrorLTE(v string) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldLTE(FieldError, v))
}

// ErrorContains applies the Contains predicate on the "error" field.
func ErrorContains(v string) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldContains(FieldError, v))
}

// ErrorHasPrefix applies the HasPrefix predicate on the "error" field.
func ErrorHasPrefix(v string) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldHasPrefix(FieldError, v))
}

// ErrorHasSuffix applies the HasSuffix predicate on the "error" field.
func ErrorHasSuffix(v string) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldHasSuffix(FieldError, v))
}

// ErrorIsNil applies the IsNil predicate on the "error" field.
func ErrorIsNil() predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldIsNull(FieldError))
}

// ErrorNotNil applies the NotNil predicate on the "error" field.
func ErrorNotNil() predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldNotNull(FieldError))
}

// ErrorEqualFold applies the EqualFold predicate on the "error" field.
func ErrorEqualFold(v string) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldEqualFold(FieldError, v))
}

// ErrorContainsFold applies the ContainsFold predicate on the "error" field.
func ErrorContainsFold(v string) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldContainsFold(FieldError, v))
}

// MetadataIsNil applies the IsNil predicate on the "metadata" field.
func MetadataIsNil() predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldIsNull(FieldMetadata))
}

// MetadataNotNil applies the NotNil predicate on the "metadata" field.
func MetadataNotNil() predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldNotNull(FieldMetadata))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ProviderMigrationStep) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ProviderMigrationStep) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ProviderMigrationStep) predicate.ProviderMigrationStep {
	return predicate.ProviderMigrationStep(sql.NotPredicates(p))
}
