// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/plystra/plystra/ent/apikey"
)

// ApiKeyCreate is the builder for creating a ApiKey entity.
type ApiKeyCreate struct {
	config
	mutation *ApiKeyMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (_c *ApiKeyCreate) SetName(v string) *ApiKeyCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetKeyPrefix sets the "key_prefix" field.
func (_c *ApiKeyCreate) SetKeyPrefix(v string) *ApiKeyCreate {
	_c.mutation.SetKeyPrefix(v)
	return _c
}

// SetKeyHash sets the "key_hash" field.
func (_c *ApiKeyCreate) SetKeyHash(v string) *ApiKeyCreate {
	_c.mutation.SetKeyHash(v)
	return _c
}

// SetLevel sets the "level" field.
func (_c *ApiKeyCreate) SetLevel(v string) *ApiKeyCreate {
	_c.mutation.SetLevel(v)
	return _c
}

// SetSpaceID sets the "space_id" field.
func (_c *ApiKeyCreate) SetSpaceID(v string) *ApiKeyCreate {
	_c.mutation.SetSpaceID(v)
	return _c
}

// SetNillableSpaceID sets the "space_id" field if the given value is not nil.
func (_c *ApiKeyCreate) SetNillableSpaceID(v *string) *ApiKeyCreate {
	if v != nil {
		_c.SetSpaceID(*v)
	}
	return _c
}

// SetGroupID sets the "group_id" field.
func (_c *ApiKeyCreate) SetGroupID(v string) *ApiKeyCreate {
	_c.mutation.SetGroupID(v)
	return _c
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_c *ApiKeyCreate) SetNillableGroupID(v *string) *ApiKeyCreate {
	if v != nil {
		_c.SetGroupID(*v)
	}
	return _c
}

// SetPermissionKeys sets the "permission_keys" field.
func (_c *ApiKeyCreate) SetPermissionKeys(v []string) *ApiKeyCreate {
	_c.mutation.SetPermissionKeys(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *ApiKeyCreate) SetStatus(v string) *ApiKeyCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *ApiKeyCreate) SetNillableStatus(v *string) *ApiKeyCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *ApiKeyCreate) SetExpiresAt(v time.Time) *ApiKeyCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_c *ApiKeyCreate) SetNillableExpiresAt(v *time.Time) *ApiKeyCreate {
	if v != nil {
		_c.SetExpiresAt(*v)
	}
	return _c
}

// SetLastUsedAt sets the "last_used_at" field.
func (_c *ApiKeyCreate) SetLastUsedAt(v time.Time) *ApiKeyCreate {
	_c.mutation.SetLastUsedAt(v)
	return _c
}

// SetNillableLastUsedAt sets the "last_used_at" field if the given value is not nil.
func (_c *ApiKeyCreate) SetNillableLastUsedAt(v *time.Time) *ApiKeyCreate {
	if v != nil {
		_c.SetLastUsedAt(*v)
	}
	return _c
}

// SetCreatedByUserID sets the "created_by_user_id" field.
func (_c *ApiKeyCreate) SetCreatedByUserID(v string) *ApiKeyCreate {
	_c.mutation.SetCreatedByUserID(v)
	return _c
}

// SetNillableCreatedByUserID sets the "created_by_user_id" field if the given value is not nil.
func (_c *ApiKeyCreate) SetNillableCreatedByUserID(v *string) *ApiKeyCreate {
	if v != nil {
		_c.SetCreatedByUserID(*v)
	}
	return _c
}

// SetCreatedByMemberID sets the "created_by_member_id" field.
func (_c *ApiKeyCreate) SetCreatedByMemberID(v string) *ApiKeyCreate {
	_c.mutation.SetCreatedByMemberID(v)
	return _c
}

// SetNillableCreatedByMemberID sets the "created_by_member_id" field if the given value is not nil.
func (_c *ApiKeyCreate) SetNillableCreatedByMemberID(v *string) *ApiKeyCreate {
	if v != nil {
		_c.SetCreatedByMemberID(*v)
	}
	return _c
}

// SetRevokedAt sets the "revoked_at" field.
func (_c *ApiKeyCreate) SetRevokedAt(v time.Time) *ApiKeyCreate {
	_c.mutation.SetRevokedAt(v)
	return _c
}

// SetNillableRevokedAt sets the "revoked_at" field if the given value is not nil.
func (_c *ApiKeyCreate) SetNillableRevokedAt(v *time.Time) *ApiKeyCreate {
	if v != nil {
		_c.SetRevokedAt(*v)
	}
	return _c
}

// SetRevokedByUserID sets the "revoked_by_user_id" field.
func (_c *ApiKeyCreate) SetRevokedByUserID(v string) *ApiKeyCreate {
	_c.mutation.SetRevokedByUserID(v)
	return _c
}

// SetNillableRevokedByUserID sets the "revoked_by_user_id" field if the given value is not nil.
func (_c *ApiKeyCreate) SetNillableRevokedByUserID(v *string) *ApiKeyCreate {
	if v != nil {
		_c.SetRevokedByUserID(*v)
	}
	return _c
}

// SetRevokedReason sets the "revoked_reason" field.
func (_c *ApiKeyCreate) SetRevokedReason(v string) *ApiKeyCreate {
	_c.mutation.SetRevokedReason(v)
	return _c
}

// SetNillableRevokedReason sets the "revoked_reason" field if the given value is not nil.
func (_c *ApiKeyCreate) SetNillableRevokedReason(v *string) *ApiKeyCreate {
	if v != nil {
		_c.SetRevokedReason(*v)
	}
	return _c
}

// SetMetadata sets the "metadata" field.
func (_c *ApiKeyCreate) SetMetadata(v map[string]interface{}) *ApiKeyCreate {
	_c.mutation.SetMetadata(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ApiKeyCreate) SetCreatedAt(v time.Time) *ApiKeyCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ApiKeyCreate) SetNillableCreatedAt(v *time.Time) *ApiKeyCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ApiKeyCreate) SetUpdatedAt(v time.Time) *ApiKeyCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ApiKeyCreate) SetNillableUpdatedAt(v *time.Time) *ApiKeyCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *ApiKeyCreate) SetDeletedAt(v time.Time) *ApiKeyCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *ApiKeyCreate) SetNillableDeletedAt(v *time.Time) *ApiKeyCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ApiKeyCreate) SetID(v string) *ApiKeyCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the ApiKeyMutation object of the builder.
func (_c *ApiKeyCreate) Mutation() *ApiKeyMutation {
	return _c.mutation
}

// Save creates the ApiKey in the database.
func (_c *ApiKeyCreate) Save(ctx context.Context) (*ApiKey, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ApiKeyCreate) SaveX(ctx context.Context) *ApiKey {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ApiKeyCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ApiKeyCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ApiKeyCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := apikey.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := apikey.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := apikey.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ApiKeyCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "ApiKey.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := apikey.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "ApiKey.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.KeyPrefix(); !ok {
		return &ValidationError{Name: "key_prefix", err: errors.New(`ent: missing required field "ApiKey.key_prefix"`)}
	}
	if v, ok := _c.mutation.KeyPrefix(); ok {
		if err := apikey.KeyPrefixValidator(v); err != nil {
			return &ValidationError{Name: "key_prefix", err: fmt.Errorf(`ent: validator failed for field "ApiKey.key_prefix": %w`, err)}
		}
	}
	if _, ok := _c.mutation.KeyHash(); !ok {
		return &ValidationError{Name: "key_hash", err: errors.New(`ent: missing required field "ApiKey.key_hash"`)}
	}
	if v, ok := _c.mutation.KeyHash(); ok {
		if err := apikey.KeyHashValidator(v); err != nil {
			return &ValidationError{Name: "key_hash", err: fmt.Errorf(`ent: validator failed for field "ApiKey.key_hash": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Level(); !ok {
		return &ValidationError{Name: "level", err: errors.New(`ent: missing required field "ApiKey.level"`)}
	}
	if v, ok := _c.mutation.Level(); ok {
		if err := apikey.LevelValidator(v); err != nil {
			return &ValidationError{Name: "level", err: fmt.Errorf(`ent: validator failed for field "ApiKey.level": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := apikey.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "ApiKey.id": %w`, err)}
		}
	}
	return nil
}

func (_c *ApiKeyCreate) sqlSave(ctx context.Context) (*ApiKey, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected ApiKey.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ApiKeyCreate) createSpec() (*ApiKey, *sqlgraph.CreateSpec) {
	var (
		_node = &ApiKey{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(apikey.Table, sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(apikey.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.KeyPrefix(); ok {
		_spec.SetField(apikey.FieldKeyPrefix, field.TypeString, value)
		_node.KeyPrefix = value
	}
	if value, ok := _c.mutation.KeyHash(); ok {
		_spec.SetField(apikey.FieldKeyHash, field.TypeString, value)
		_node.KeyHash = value
	}
	if value, ok := _c.mutation.Level(); ok {
		_spec.SetField(apikey.FieldLevel, field.TypeString, value)
		_node.Level = value
	}
	if value, ok := _c.mutation.SpaceID(); ok {
		_spec.SetField(apikey.FieldSpaceID, field.TypeString, value)
		_node.SpaceID = &value
	}
	if value, ok := _c.mutation.GroupID(); ok {
		_spec.SetField(apikey.FieldGroupID, field.TypeString, value)
		_node.GroupID = &value
	}
	if value, ok := _c.mutation.PermissionKeys(); ok {
		_spec.SetField(apikey.FieldPermissionKeys, field.TypeJSON, value)
		_node.PermissionKeys = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(apikey.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(apikey.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = &value
	}
	if value, ok := _c.mutation.LastUsedAt(); ok {
		_spec.SetField(apikey.FieldLastUsedAt, field.TypeTime, value)
		_node.LastUsedAt = &value
	}
	if value, ok := _c.mutation.CreatedByUserID(); ok {
		_spec.SetField(apikey.FieldCreatedByUserID, field.TypeString, value)
		_node.CreatedByUserID = &value
	}
	if value, ok := _c.mutation.CreatedByMemberID(); ok {
		_spec.SetField(apikey.FieldCreatedByMemberID, field.TypeString, value)
		_node.CreatedByMemberID = &value
	}
	if value, ok := _c.mutation.RevokedAt(); ok {
		_spec.SetField(apikey.FieldRevokedAt, field.TypeTime, value)
		_node.RevokedAt = &value
	}
	if value, ok := _c.mutation.RevokedByUserID(); ok {
		_spec.SetField(apikey.FieldRevokedByUserID, field.TypeString, value)
		_node.RevokedByUserID = &value
	}
	if value, ok := _c.mutation.RevokedReason(); ok {
		_spec.SetField(apikey.FieldRevokedReason, field.TypeString, value)
		_node.RevokedReason = &value
	}
	if value, ok := _c.mutation.Metadata(); ok {
		_spec.SetField(apikey.FieldMetadata, field.TypeJSON, value)
		_node.Metadata = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(apikey.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(apikey.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(apikey.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	return _node, _spec
}

// ApiKeyCreateBulk is the builder for creating many ApiKey entities in bulk.
type ApiKeyCreateBulk struct {
	config
	err      error
	builders []*ApiKeyCreate
}

// Save creates the ApiKey entities in the database.
func (_c *ApiKeyCreateBulk) Save(ctx context.Context) ([]*ApiKey, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ApiKey, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ApiKeyMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ApiKeyCreateBulk) SaveX(ctx context.Context) []*ApiKey {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ApiKeyCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ApiKeyCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
