// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/plystra/core/ent/apikey"
)

// ApiKey is the model entity for the ApiKey schema.
type ApiKey struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// KeyPrefix holds the value of the "key_prefix" field.
	KeyPrefix string `json:"key_prefix,omitempty"`
	// KeyHash holds the value of the "key_hash" field.
	KeyHash string `json:"-"`
	// Level holds the value of the "level" field.
	Level string `json:"level,omitempty"`
	// SpaceID holds the value of the "space_id" field.
	SpaceID *string `json:"space_id,omitempty"`
	// GroupID holds the value of the "group_id" field.
	GroupID *string `json:"group_id,omitempty"`
	// PermissionKeys holds the value of the "permission_keys" field.
	PermissionKeys []string `json:"permission_keys,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// ExpiresAt holds the value of the "expires_at" field.
	ExpiresAt *time.Time `json:"expires_at,omitempty"`
	// LastUsedAt holds the value of the "last_used_at" field.
	LastUsedAt *time.Time `json:"last_used_at,omitempty"`
	// CreatedByUserID holds the value of the "created_by_user_id" field.
	CreatedByUserID *string `json:"created_by_user_id,omitempty"`
	// CreatedByMemberID holds the value of the "created_by_member_id" field.
	CreatedByMemberID *string `json:"created_by_member_id,omitempty"`
	// ProviderRuntimePluginID holds the value of the "provider_runtime_plugin_id" field.
	ProviderRuntimePluginID *string `json:"provider_runtime_plugin_id,omitempty"`
	// RevokedAt holds the value of the "revoked_at" field.
	RevokedAt *time.Time `json:"revoked_at,omitempty"`
	// RevokedByUserID holds the value of the "revoked_by_user_id" field.
	RevokedByUserID *string `json:"revoked_by_user_id,omitempty"`
	// RevokedReason holds the value of the "revoked_reason" field.
	RevokedReason *string `json:"revoked_reason,omitempty"`
	// Metadata holds the value of the "metadata" field.
	Metadata map[string]interface{} `json:"metadata,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt    *time.Time `json:"deleted_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ApiKey) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case apikey.FieldPermissionKeys, apikey.FieldMetadata:
			values[i] = new([]byte)
		case apikey.FieldID, apikey.FieldName, apikey.FieldKeyPrefix, apikey.FieldKeyHash, apikey.FieldLevel, apikey.FieldSpaceID, apikey.FieldGroupID, apikey.FieldStatus, apikey.FieldCreatedByUserID, apikey.FieldCreatedByMemberID, apikey.FieldProviderRuntimePluginID, apikey.FieldRevokedByUserID, apikey.FieldRevokedReason:
			values[i] = new(sql.NullString)
		case apikey.FieldExpiresAt, apikey.FieldLastUsedAt, apikey.FieldRevokedAt, apikey.FieldCreatedAt, apikey.FieldUpdatedAt, apikey.FieldDeletedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ApiKey fields.
func (_m *ApiKey) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case apikey.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case apikey.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case apikey.FieldKeyPrefix:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field key_prefix", values[i])
			} else if value.Valid {
				_m.KeyPrefix = value.String
			}
		case apikey.FieldKeyHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field key_hash", values[i])
			} else if value.Valid {
				_m.KeyHash = value.String
			}
		case apikey.FieldLevel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field level", values[i])
			} else if value.Valid {
				_m.Level = value.String
			}
		case apikey.FieldSpaceID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field space_id", values[i])
			} else if value.Valid {
				_m.SpaceID = new(string)
				*_m.SpaceID = value.String
			}
		case apikey.FieldGroupID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field group_id", values[i])
			} else if value.Valid {
				_m.GroupID = new(string)
				*_m.GroupID = value.String
			}
		case apikey.FieldPermissionKeys:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field permission_keys", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.PermissionKeys); err != nil {
					return fmt.Errorf("unmarshal field permission_keys: %w", err)
				}
			}
		case apikey.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case apikey.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				_m.ExpiresAt = new(time.Time)
				*_m.ExpiresAt = value.Time
			}
		case apikey.FieldLastUsedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_used_at", values[i])
			} else if value.Valid {
				_m.LastUsedAt = new(time.Time)
				*_m.LastUsedAt = value.Time
			}
		case apikey.FieldCreatedByUserID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field created_by_user_id", values[i])
			} else if value.Valid {
				_m.CreatedByUserID = new(string)
				*_m.CreatedByUserID = value.String
			}
		case apikey.FieldCreatedByMemberID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field created_by_member_id", values[i])
			} else if value.Valid {
				_m.CreatedByMemberID = new(string)
				*_m.CreatedByMemberID = value.String
			}
		case apikey.FieldProviderRuntimePluginID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provider_runtime_plugin_id", values[i])
			} else if value.Valid {
				_m.ProviderRuntimePluginID = new(string)
				*_m.ProviderRuntimePluginID = value.String
			}
		case apikey.FieldRevokedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field revoked_at", values[i])
			} else if value.Valid {
				_m.RevokedAt = new(time.Time)
				*_m.RevokedAt = value.Time
			}
		case apikey.FieldRevokedByUserID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field revoked_by_user_id", values[i])
			} else if value.Valid {
				_m.RevokedByUserID = new(string)
				*_m.RevokedByUserID = value.String
			}
		case apikey.FieldRevokedReason:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field revoked_reason", values[i])
			} else if value.Valid {
				_m.RevokedReason = new(string)
				*_m.RevokedReason = value.String
			}
		case apikey.FieldMetadata:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field metadata", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Metadata); err != nil {
					return fmt.Errorf("unmarshal field metadata: %w", err)
				}
			}
		case apikey.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case apikey.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case apikey.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = new(time.Time)
				*_m.DeletedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ApiKey.
// This includes values selected through modifiers, order, etc.
func (_m *ApiKey) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this ApiKey.
// Note that you need to call ApiKey.Unwrap() before calling this method if this ApiKey
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ApiKey) Update() *ApiKeyUpdateOne {
	return NewApiKeyClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ApiKey entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ApiKey) Unwrap() *ApiKey {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ApiKey is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ApiKey) String() string {
	var builder strings.Builder
	builder.WriteString("ApiKey(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("key_prefix=")
	builder.WriteString(_m.KeyPrefix)
	builder.WriteString(", ")
	builder.WriteString("key_hash=<sensitive>")
	builder.WriteString(", ")
	builder.WriteString("level=")
	builder.WriteString(_m.Level)
	builder.WriteString(", ")
	if v := _m.SpaceID; v != nil {
		builder.WriteString("space_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.GroupID; v != nil {
		builder.WriteString("group_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("permission_keys=")
	builder.WriteString(fmt.Sprintf("%v", _m.PermissionKeys))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	if v := _m.ExpiresAt; v != nil {
		builder.WriteString("expires_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.LastUsedAt; v != nil {
		builder.WriteString("last_used_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.CreatedByUserID; v != nil {
		builder.WriteString("created_by_user_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.CreatedByMemberID; v != nil {
		builder.WriteString("created_by_member_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ProviderRuntimePluginID; v != nil {
		builder.WriteString("provider_runtime_plugin_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.RevokedAt; v != nil {
		builder.WriteString("revoked_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.RevokedByUserID; v != nil {
		builder.WriteString("revoked_by_user_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.RevokedReason; v != nil {
		builder.WriteString("revoked_reason=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("metadata=")
	builder.WriteString(fmt.Sprintf("%v", _m.Metadata))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// ApiKeys is a parsable slice of ApiKey.
type ApiKeys []*ApiKey
