// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/plystra/plystra/ent/appdatamodel"
)

// AppDataModelCreate is the builder for creating a AppDataModel entity.
type AppDataModelCreate struct {
	config
	mutation *AppDataModelMutation
	hooks    []Hook
}

// SetSpaceID sets the "space_id" field.
func (_c *AppDataModelCreate) SetSpaceID(v string) *AppDataModelCreate {
	_c.mutation.SetSpaceID(v)
	return _c
}

// SetKey sets the "key" field.
func (_c *AppDataModelCreate) SetKey(v string) *AppDataModelCreate {
	_c.mutation.SetKey(v)
	return _c
}

// SetDisplayName sets the "display_name" field.
func (_c *AppDataModelCreate) SetDisplayName(v string) *AppDataModelCreate {
	_c.mutation.SetDisplayName(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *AppDataModelCreate) SetDescription(v string) *AppDataModelCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *AppDataModelCreate) SetNillableDescription(v *string) *AppDataModelCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetSource sets the "source" field.
func (_c *AppDataModelCreate) SetSource(v string) *AppDataModelCreate {
	_c.mutation.SetSource(v)
	return _c
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_c *AppDataModelCreate) SetNillableSource(v *string) *AppDataModelCreate {
	if v != nil {
		_c.SetSource(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *AppDataModelCreate) SetStatus(v string) *AppDataModelCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *AppDataModelCreate) SetNillableStatus(v *string) *AppDataModelCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetSchema sets the "schema" field.
func (_c *AppDataModelCreate) SetSchema(v map[string]interface{}) *AppDataModelCreate {
	_c.mutation.SetSchema(v)
	return _c
}

// SetMetadata sets the "metadata" field.
func (_c *AppDataModelCreate) SetMetadata(v map[string]interface{}) *AppDataModelCreate {
	_c.mutation.SetMetadata(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *AppDataModelCreate) SetCreatedAt(v time.Time) *AppDataModelCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *AppDataModelCreate) SetNillableCreatedAt(v *time.Time) *AppDataModelCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *AppDataModelCreate) SetUpdatedAt(v time.Time) *AppDataModelCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *AppDataModelCreate) SetNillableUpdatedAt(v *time.Time) *AppDataModelCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *AppDataModelCreate) SetDeletedAt(v time.Time) *AppDataModelCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *AppDataModelCreate) SetNillableDeletedAt(v *time.Time) *AppDataModelCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *AppDataModelCreate) SetID(v string) *AppDataModelCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the AppDataModelMutation object of the builder.
func (_c *AppDataModelCreate) Mutation() *AppDataModelMutation {
	return _c.mutation
}

// Save creates the AppDataModel in the database.
func (_c *AppDataModelCreate) Save(ctx context.Context) (*AppDataModel, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AppDataModelCreate) SaveX(ctx context.Context) *AppDataModel {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AppDataModelCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AppDataModelCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AppDataModelCreate) defaults() {
	if _, ok := _c.mutation.Source(); !ok {
		v := appdatamodel.DefaultSource
		_c.mutation.SetSource(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := appdatamodel.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := appdatamodel.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := appdatamodel.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AppDataModelCreate) check() error {
	if _, ok := _c.mutation.SpaceID(); !ok {
		return &ValidationError{Name: "space_id", err: errors.New(`ent: missing required field "AppDataModel.space_id"`)}
	}
	if v, ok := _c.mutation.SpaceID(); ok {
		if err := appdatamodel.SpaceIDValidator(v); err != nil {
			return &ValidationError{Name: "space_id", err: fmt.Errorf(`ent: validator failed for field "AppDataModel.space_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Key(); !ok {
		return &ValidationError{Name: "key", err: errors.New(`ent: missing required field "AppDataModel.key"`)}
	}
	if v, ok := _c.mutation.Key(); ok {
		if err := appdatamodel.KeyValidator(v); err != nil {
			return &ValidationError{Name: "key", err: fmt.Errorf(`ent: validator failed for field "AppDataModel.key": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DisplayName(); !ok {
		return &ValidationError{Name: "display_name", err: errors.New(`ent: missing required field "AppDataModel.display_name"`)}
	}
	if v, ok := _c.mutation.DisplayName(); ok {
		if err := appdatamodel.DisplayNameValidator(v); err != nil {
			return &ValidationError{Name: "display_name", err: fmt.Errorf(`ent: validator failed for field "AppDataModel.display_name": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := appdatamodel.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "AppDataModel.id": %w`, err)}
		}
	}
	return nil
}

func (_c *AppDataModelCreate) sqlSave(ctx context.Context) (*AppDataModel, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected AppDataModel.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AppDataModelCreate) createSpec() (*AppDataModel, *sqlgraph.CreateSpec) {
	var (
		_node = &AppDataModel{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(appdatamodel.Table, sqlgraph.NewFieldSpec(appdatamodel.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.SpaceID(); ok {
		_spec.SetField(appdatamodel.FieldSpaceID, field.TypeString, value)
		_node.SpaceID = value
	}
	if value, ok := _c.mutation.Key(); ok {
		_spec.SetField(appdatamodel.FieldKey, field.TypeString, value)
		_node.Key = value
	}
	if value, ok := _c.mutation.DisplayName(); ok {
		_spec.SetField(appdatamodel.FieldDisplayName, field.TypeString, value)
		_node.DisplayName = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(appdatamodel.FieldDescription, field.TypeString, value)
		_node.Description = &value
	}
	if value, ok := _c.mutation.Source(); ok {
		_spec.SetField(appdatamodel.FieldSource, field.TypeString, value)
		_node.Source = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(appdatamodel.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Schema(); ok {
		_spec.SetField(appdatamodel.FieldSchema, field.TypeJSON, value)
		_node.Schema = value
	}
	if value, ok := _c.mutation.Metadata(); ok {
		_spec.SetField(appdatamodel.FieldMetadata, field.TypeJSON, value)
		_node.Metadata = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(appdatamodel.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(appdatamodel.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(appdatamodel.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	return _node, _spec
}

// AppDataModelCreateBulk is the builder for creating many AppDataModel entities in bulk.
type AppDataModelCreateBulk struct {
	config
	err      error
	builders []*AppDataModelCreate
}

// Save creates the AppDataModel entities in the database.
func (_c *AppDataModelCreateBulk) Save(ctx context.Context) ([]*AppDataModel, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AppDataModel, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AppDataModelMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AppDataModelCreateBulk) SaveX(ctx context.Context) []*AppDataModel {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AppDataModelCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AppDataModelCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
