// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/plystra/plystra/ent/authchallenge"
	"github.com/plystra/plystra/ent/predicate"
)

// AuthChallengeUpdate is the builder for updating AuthChallenge entities.
type AuthChallengeUpdate struct {
	config
	hooks    []Hook
	mutation *AuthChallengeMutation
}

// Where appends a list predicates to the AuthChallengeUpdate builder.
func (_u *AuthChallengeUpdate) Where(ps ...predicate.AuthChallenge) *AuthChallengeUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetPurpose sets the "purpose" field.
func (_u *AuthChallengeUpdate) SetPurpose(v string) *AuthChallengeUpdate {
	_u.mutation.SetPurpose(v)
	return _u
}

// SetNillablePurpose sets the "purpose" field if the given value is not nil.
func (_u *AuthChallengeUpdate) SetNillablePurpose(v *string) *AuthChallengeUpdate {
	if v != nil {
		_u.SetPurpose(*v)
	}
	return _u
}

// SetDeliveryMethod sets the "delivery_method" field.
func (_u *AuthChallengeUpdate) SetDeliveryMethod(v string) *AuthChallengeUpdate {
	_u.mutation.SetDeliveryMethod(v)
	return _u
}

// SetNillableDeliveryMethod sets the "delivery_method" field if the given value is not nil.
func (_u *AuthChallengeUpdate) SetNillableDeliveryMethod(v *string) *AuthChallengeUpdate {
	if v != nil {
		_u.SetDeliveryMethod(*v)
	}
	return _u
}

// SetEmail sets the "email" field.
func (_u *AuthChallengeUpdate) SetEmail(v string) *AuthChallengeUpdate {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *AuthChallengeUpdate) SetNillableEmail(v *string) *AuthChallengeUpdate {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *AuthChallengeUpdate) SetUserID(v string) *AuthChallengeUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *AuthChallengeUpdate) SetNillableUserID(v *string) *AuthChallengeUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// ClearUserID clears the value of the "user_id" field.
func (_u *AuthChallengeUpdate) ClearUserID() *AuthChallengeUpdate {
	_u.mutation.ClearUserID()
	return _u
}

// SetSecretHash sets the "secret_hash" field.
func (_u *AuthChallengeUpdate) SetSecretHash(v string) *AuthChallengeUpdate {
	_u.mutation.SetSecretHash(v)
	return _u
}

// SetNillableSecretHash sets the "secret_hash" field if the given value is not nil.
func (_u *AuthChallengeUpdate) SetNillableSecretHash(v *string) *AuthChallengeUpdate {
	if v != nil {
		_u.SetSecretHash(*v)
	}
	return _u
}

// SetCodeHash sets the "code_hash" field.
func (_u *AuthChallengeUpdate) SetCodeHash(v string) *AuthChallengeUpdate {
	_u.mutation.SetCodeHash(v)
	return _u
}

// SetNillableCodeHash sets the "code_hash" field if the given value is not nil.
func (_u *AuthChallengeUpdate) SetNillableCodeHash(v *string) *AuthChallengeUpdate {
	if v != nil {
		_u.SetCodeHash(*v)
	}
	return _u
}

// ClearCodeHash clears the value of the "code_hash" field.
func (_u *AuthChallengeUpdate) ClearCodeHash() *AuthChallengeUpdate {
	_u.mutation.ClearCodeHash()
	return _u
}

// SetRedirectURL sets the "redirect_url" field.
func (_u *AuthChallengeUpdate) SetRedirectURL(v string) *AuthChallengeUpdate {
	_u.mutation.SetRedirectURL(v)
	return _u
}

// SetNillableRedirectURL sets the "redirect_url" field if the given value is not nil.
func (_u *AuthChallengeUpdate) SetNillableRedirectURL(v *string) *AuthChallengeUpdate {
	if v != nil {
		_u.SetRedirectURL(*v)
	}
	return _u
}

// ClearRedirectURL clears the value of the "redirect_url" field.
func (_u *AuthChallengeUpdate) ClearRedirectURL() *AuthChallengeUpdate {
	_u.mutation.ClearRedirectURL()
	return _u
}

// SetRequestIP sets the "request_ip" field.
func (_u *AuthChallengeUpdate) SetRequestIP(v string) *AuthChallengeUpdate {
	_u.mutation.SetRequestIP(v)
	return _u
}

// SetNillableRequestIP sets the "request_ip" field if the given value is not nil.
func (_u *AuthChallengeUpdate) SetNillableRequestIP(v *string) *AuthChallengeUpdate {
	if v != nil {
		_u.SetRequestIP(*v)
	}
	return _u
}

// ClearRequestIP clears the value of the "request_ip" field.
func (_u *AuthChallengeUpdate) ClearRequestIP() *AuthChallengeUpdate {
	_u.mutation.ClearRequestIP()
	return _u
}

// SetRequestUserAgent sets the "request_user_agent" field.
func (_u *AuthChallengeUpdate) SetRequestUserAgent(v string) *AuthChallengeUpdate {
	_u.mutation.SetRequestUserAgent(v)
	return _u
}

// SetNillableRequestUserAgent sets the "request_user_agent" field if the given value is not nil.
func (_u *AuthChallengeUpdate) SetNillableRequestUserAgent(v *string) *AuthChallengeUpdate {
	if v != nil {
		_u.SetRequestUserAgent(*v)
	}
	return _u
}

// ClearRequestUserAgent clears the value of the "request_user_agent" field.
func (_u *AuthChallengeUpdate) ClearRequestUserAgent() *AuthChallengeUpdate {
	_u.mutation.ClearRequestUserAgent()
	return _u
}

// SetAttempts sets the "attempts" field.
func (_u *AuthChallengeUpdate) SetAttempts(v int) *AuthChallengeUpdate {
	_u.mutation.ResetAttempts()
	_u.mutation.SetAttempts(v)
	return _u
}

// SetNillableAttempts sets the "attempts" field if the given value is not nil.
func (_u *AuthChallengeUpdate) SetNillableAttempts(v *int) *AuthChallengeUpdate {
	if v != nil {
		_u.SetAttempts(*v)
	}
	return _u
}

// AddAttempts adds value to the "attempts" field.
func (_u *AuthChallengeUpdate) AddAttempts(v int) *AuthChallengeUpdate {
	_u.mutation.AddAttempts(v)
	return _u
}

// SetMaxAttempts sets the "max_attempts" field.
func (_u *AuthChallengeUpdate) SetMaxAttempts(v int) *AuthChallengeUpdate {
	_u.mutation.ResetMaxAttempts()
	_u.mutation.SetMaxAttempts(v)
	return _u
}

// SetNillableMaxAttempts sets the "max_attempts" field if the given value is not nil.
func (_u *AuthChallengeUpdate) SetNillableMaxAttempts(v *int) *AuthChallengeUpdate {
	if v != nil {
		_u.SetMaxAttempts(*v)
	}
	return _u
}

// AddMaxAttempts adds value to the "max_attempts" field.
func (_u *AuthChallengeUpdate) AddMaxAttempts(v int) *AuthChallengeUpdate {
	_u.mutation.AddMaxAttempts(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *AuthChallengeUpdate) SetStatus(v string) *AuthChallengeUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *AuthChallengeUpdate) SetNillableStatus(v *string) *AuthChallengeUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *AuthChallengeUpdate) SetExpiresAt(v time.Time) *AuthChallengeUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *AuthChallengeUpdate) SetNillableExpiresAt(v *time.Time) *AuthChallengeUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetConsumedAt sets the "consumed_at" field.
func (_u *AuthChallengeUpdate) SetConsumedAt(v time.Time) *AuthChallengeUpdate {
	_u.mutation.SetConsumedAt(v)
	return _u
}

// SetNillableConsumedAt sets the "consumed_at" field if the given value is not nil.
func (_u *AuthChallengeUpdate) SetNillableConsumedAt(v *time.Time) *AuthChallengeUpdate {
	if v != nil {
		_u.SetConsumedAt(*v)
	}
	return _u
}

// ClearConsumedAt clears the value of the "consumed_at" field.
func (_u *AuthChallengeUpdate) ClearConsumedAt() *AuthChallengeUpdate {
	_u.mutation.ClearConsumedAt()
	return _u
}

// SetRevokedAt sets the "revoked_at" field.
func (_u *AuthChallengeUpdate) SetRevokedAt(v time.Time) *AuthChallengeUpdate {
	_u.mutation.SetRevokedAt(v)
	return _u
}

// SetNillableRevokedAt sets the "revoked_at" field if the given value is not nil.
func (_u *AuthChallengeUpdate) SetNillableRevokedAt(v *time.Time) *AuthChallengeUpdate {
	if v != nil {
		_u.SetRevokedAt(*v)
	}
	return _u
}

// ClearRevokedAt clears the value of the "revoked_at" field.
func (_u *AuthChallengeUpdate) ClearRevokedAt() *AuthChallengeUpdate {
	_u.mutation.ClearRevokedAt()
	return _u
}

// SetEmailProviderMessageID sets the "email_provider_message_id" field.
func (_u *AuthChallengeUpdate) SetEmailProviderMessageID(v string) *AuthChallengeUpdate {
	_u.mutation.SetEmailProviderMessageID(v)
	return _u
}

// SetNillableEmailProviderMessageID sets the "email_provider_message_id" field if the given value is not nil.
func (_u *AuthChallengeUpdate) SetNillableEmailProviderMessageID(v *string) *AuthChallengeUpdate {
	if v != nil {
		_u.SetEmailProviderMessageID(*v)
	}
	return _u
}

// ClearEmailProviderMessageID clears the value of the "email_provider_message_id" field.
func (_u *AuthChallengeUpdate) ClearEmailProviderMessageID() *AuthChallengeUpdate {
	_u.mutation.ClearEmailProviderMessageID()
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *AuthChallengeUpdate) SetMetadata(v map[string]interface{}) *AuthChallengeUpdate {
	_u.mutation.SetMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *AuthChallengeUpdate) ClearMetadata() *AuthChallengeUpdate {
	_u.mutation.ClearMetadata()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AuthChallengeUpdate) SetUpdatedAt(v time.Time) *AuthChallengeUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *AuthChallengeUpdate) SetDeletedAt(v time.Time) *AuthChallengeUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *AuthChallengeUpdate) SetNillableDeletedAt(v *time.Time) *AuthChallengeUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *AuthChallengeUpdate) ClearDeletedAt() *AuthChallengeUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// Mutation returns the AuthChallengeMutation object of the builder.
func (_u *AuthChallengeUpdate) Mutation() *AuthChallengeMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AuthChallengeUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AuthChallengeUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AuthChallengeUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AuthChallengeUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AuthChallengeUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := authchallenge.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AuthChallengeUpdate) check() error {
	if v, ok := _u.mutation.Purpose(); ok {
		if err := authchallenge.PurposeValidator(v); err != nil {
			return &ValidationError{Name: "purpose", err: fmt.Errorf(`ent: validator failed for field "AuthChallenge.purpose": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DeliveryMethod(); ok {
		if err := authchallenge.DeliveryMethodValidator(v); err != nil {
			return &ValidationError{Name: "delivery_method", err: fmt.Errorf(`ent: validator failed for field "AuthChallenge.delivery_method": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Email(); ok {
		if err := authchallenge.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "AuthChallenge.email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SecretHash(); ok {
		if err := authchallenge.SecretHashValidator(v); err != nil {
			return &ValidationError{Name: "secret_hash", err: fmt.Errorf(`ent: validator failed for field "AuthChallenge.secret_hash": %w`, err)}
		}
	}
	return nil
}

func (_u *AuthChallengeUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(authchallenge.Table, authchallenge.Columns, sqlgraph.NewFieldSpec(authchallenge.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Purpose(); ok {
		_spec.SetField(authchallenge.FieldPurpose, field.TypeString, value)
	}
	if value, ok := _u.mutation.DeliveryMethod(); ok {
		_spec.SetField(authchallenge.FieldDeliveryMethod, field.TypeString, value)
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(authchallenge.FieldEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(authchallenge.FieldUserID, field.TypeString, value)
	}
	if _u.mutation.UserIDCleared() {
		_spec.ClearField(authchallenge.FieldUserID, field.TypeString)
	}
	if value, ok := _u.mutation.SecretHash(); ok {
		_spec.SetField(authchallenge.FieldSecretHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.CodeHash(); ok {
		_spec.SetField(authchallenge.FieldCodeHash, field.TypeString, value)
	}
	if _u.mutation.CodeHashCleared() {
		_spec.ClearField(authchallenge.FieldCodeHash, field.TypeString)
	}
	if value, ok := _u.mutation.RedirectURL(); ok {
		_spec.SetField(authchallenge.FieldRedirectURL, field.TypeString, value)
	}
	if _u.mutation.RedirectURLCleared() {
		_spec.ClearField(authchallenge.FieldRedirectURL, field.TypeString)
	}
	if value, ok := _u.mutation.RequestIP(); ok {
		_spec.SetField(authchallenge.FieldRequestIP, field.TypeString, value)
	}
	if _u.mutation.RequestIPCleared() {
		_spec.ClearField(authchallenge.FieldRequestIP, field.TypeString)
	}
	if value, ok := _u.mutation.RequestUserAgent(); ok {
		_spec.SetField(authchallenge.FieldRequestUserAgent, field.TypeString, value)
	}
	if _u.mutation.RequestUserAgentCleared() {
		_spec.ClearField(authchallenge.FieldRequestUserAgent, field.TypeString)
	}
	if value, ok := _u.mutation.Attempts(); ok {
		_spec.SetField(authchallenge.FieldAttempts, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAttempts(); ok {
		_spec.AddField(authchallenge.FieldAttempts, field.TypeInt, value)
	}
	if value, ok := _u.mutation.MaxAttempts(); ok {
		_spec.SetField(authchallenge.FieldMaxAttempts, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxAttempts(); ok {
		_spec.AddField(authchallenge.FieldMaxAttempts, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(authchallenge.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(authchallenge.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ConsumedAt(); ok {
		_spec.SetField(authchallenge.FieldConsumedAt, field.TypeTime, value)
	}
	if _u.mutation.ConsumedAtCleared() {
		_spec.ClearField(authchallenge.FieldConsumedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.RevokedAt(); ok {
		_spec.SetField(authchallenge.FieldRevokedAt, field.TypeTime, value)
	}
	if _u.mutation.RevokedAtCleared() {
		_spec.ClearField(authchallenge.FieldRevokedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.EmailProviderMessageID(); ok {
		_spec.SetField(authchallenge.FieldEmailProviderMessageID, field.TypeString, value)
	}
	if _u.mutation.EmailProviderMessageIDCleared() {
		_spec.ClearField(authchallenge.FieldEmailProviderMessageID, field.TypeString)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(authchallenge.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(authchallenge.FieldMetadata, field.TypeJSON)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(authchallenge.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(authchallenge.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(authchallenge.FieldDeletedAt, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{authchallenge.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AuthChallengeUpdateOne is the builder for updating a single AuthChallenge entity.
type AuthChallengeUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AuthChallengeMutation
}

// SetPurpose sets the "purpose" field.
func (_u *AuthChallengeUpdateOne) SetPurpose(v string) *AuthChallengeUpdateOne {
	_u.mutation.SetPurpose(v)
	return _u
}

// SetNillablePurpose sets the "purpose" field if the given value is not nil.
func (_u *AuthChallengeUpdateOne) SetNillablePurpose(v *string) *AuthChallengeUpdateOne {
	if v != nil {
		_u.SetPurpose(*v)
	}
	return _u
}

// SetDeliveryMethod sets the "delivery_method" field.
func (_u *AuthChallengeUpdateOne) SetDeliveryMethod(v string) *AuthChallengeUpdateOne {
	_u.mutation.SetDeliveryMethod(v)
	return _u
}

// SetNillableDeliveryMethod sets the "delivery_method" field if the given value is not nil.
func (_u *AuthChallengeUpdateOne) SetNillableDeliveryMethod(v *string) *AuthChallengeUpdateOne {
	if v != nil {
		_u.SetDeliveryMethod(*v)
	}
	return _u
}

// SetEmail sets the "email" field.
func (_u *AuthChallengeUpdateOne) SetEmail(v string) *AuthChallengeUpdateOne {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *AuthChallengeUpdateOne) SetNillableEmail(v *string) *AuthChallengeUpdateOne {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *AuthChallengeUpdateOne) SetUserID(v string) *AuthChallengeUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *AuthChallengeUpdateOne) SetNillableUserID(v *string) *AuthChallengeUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// ClearUserID clears the value of the "user_id" field.
func (_u *AuthChallengeUpdateOne) ClearUserID() *AuthChallengeUpdateOne {
	_u.mutation.ClearUserID()
	return _u
}

// SetSecretHash sets the "secret_hash" field.
func (_u *AuthChallengeUpdateOne) SetSecretHash(v string) *AuthChallengeUpdateOne {
	_u.mutation.SetSecretHash(v)
	return _u
}

// SetNillableSecretHash sets the "secret_hash" field if the given value is not nil.
func (_u *AuthChallengeUpdateOne) SetNillableSecretHash(v *string) *AuthChallengeUpdateOne {
	if v != nil {
		_u.SetSecretHash(*v)
	}
	return _u
}

// SetCodeHash sets the "code_hash" field.
func (_u *AuthChallengeUpdateOne) SetCodeHash(v string) *AuthChallengeUpdateOne {
	_u.mutation.SetCodeHash(v)
	return _u
}

// SetNillableCodeHash sets the "code_hash" field if the given value is not nil.
func (_u *AuthChallengeUpdateOne) SetNillableCodeHash(v *string) *AuthChallengeUpdateOne {
	if v != nil {
		_u.SetCodeHash(*v)
	}
	return _u
}

// ClearCodeHash clears the value of the "code_hash" field.
func (_u *AuthChallengeUpdateOne) ClearCodeHash() *AuthChallengeUpdateOne {
	_u.mutation.ClearCodeHash()
	return _u
}

// SetRedirectURL sets the "redirect_url" field.
func (_u *AuthChallengeUpdateOne) SetRedirectURL(v string) *AuthChallengeUpdateOne {
	_u.mutation.SetRedirectURL(v)
	return _u
}

// SetNillableRedirectURL sets the "redirect_url" field if the given value is not nil.
func (_u *AuthChallengeUpdateOne) SetNillableRedirectURL(v *string) *AuthChallengeUpdateOne {
	if v != nil {
		_u.SetRedirectURL(*v)
	}
	return _u
}

// ClearRedirectURL clears the value of the "redirect_url" field.
func (_u *AuthChallengeUpdateOne) ClearRedirectURL() *AuthChallengeUpdateOne {
	_u.mutation.ClearRedirectURL()
	return _u
}

// SetRequestIP sets the "request_ip" field.
func (_u *AuthChallengeUpdateOne) SetRequestIP(v string) *AuthChallengeUpdateOne {
	_u.mutation.SetRequestIP(v)
	return _u
}

// SetNillableRequestIP sets the "request_ip" field if the given value is not nil.
func (_u *AuthChallengeUpdateOne) SetNillableRequestIP(v *string) *AuthChallengeUpdateOne {
	if v != nil {
		_u.SetRequestIP(*v)
	}
	return _u
}

// ClearRequestIP clears the value of the "request_ip" field.
func (_u *AuthChallengeUpdateOne) ClearRequestIP() *AuthChallengeUpdateOne {
	_u.mutation.ClearRequestIP()
	return _u
}

// SetRequestUserAgent sets the "request_user_agent" field.
func (_u *AuthChallengeUpdateOne) SetRequestUserAgent(v string) *AuthChallengeUpdateOne {
	_u.mutation.SetRequestUserAgent(v)
	return _u
}

// SetNillableRequestUserAgent sets the "request_user_agent" field if the given value is not nil.
func (_u *AuthChallengeUpdateOne) SetNillableRequestUserAgent(v *string) *AuthChallengeUpdateOne {
	if v != nil {
		_u.SetRequestUserAgent(*v)
	}
	return _u
}

// ClearRequestUserAgent clears the value of the "request_user_agent" field.
func (_u *AuthChallengeUpdateOne) ClearRequestUserAgent() *AuthChallengeUpdateOne {
	_u.mutation.ClearRequestUserAgent()
	return _u
}

// SetAttempts sets the "attempts" field.
func (_u *AuthChallengeUpdateOne) SetAttempts(v int) *AuthChallengeUpdateOne {
	_u.mutation.ResetAttempts()
	_u.mutation.SetAttempts(v)
	return _u
}

// SetNillableAttempts sets the "attempts" field if the given value is not nil.
func (_u *AuthChallengeUpdateOne) SetNillableAttempts(v *int) *AuthChallengeUpdateOne {
	if v != nil {
		_u.SetAttempts(*v)
	}
	return _u
}

// AddAttempts adds value to the "attempts" field.
func (_u *AuthChallengeUpdateOne) AddAttempts(v int) *AuthChallengeUpdateOne {
	_u.mutation.AddAttempts(v)
	return _u
}

// SetMaxAttempts sets the "max_attempts" field.
func (_u *AuthChallengeUpdateOne) SetMaxAttempts(v int) *AuthChallengeUpdateOne {
	_u.mutation.ResetMaxAttempts()
	_u.mutation.SetMaxAttempts(v)
	return _u
}

// SetNillableMaxAttempts sets the "max_attempts" field if the given value is not nil.
func (_u *AuthChallengeUpdateOne) SetNillableMaxAttempts(v *int) *AuthChallengeUpdateOne {
	if v != nil {
		_u.SetMaxAttempts(*v)
	}
	return _u
}

// AddMaxAttempts adds value to the "max_attempts" field.
func (_u *AuthChallengeUpdateOne) AddMaxAttempts(v int) *AuthChallengeUpdateOne {
	_u.mutation.AddMaxAttempts(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *AuthChallengeUpdateOne) SetStatus(v string) *AuthChallengeUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *AuthChallengeUpdateOne) SetNillableStatus(v *string) *AuthChallengeUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *AuthChallengeUpdateOne) SetExpiresAt(v time.Time) *AuthChallengeUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *AuthChallengeUpdateOne) SetNillableExpiresAt(v *time.Time) *AuthChallengeUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetConsumedAt sets the "consumed_at" field.
func (_u *AuthChallengeUpdateOne) SetConsumedAt(v time.Time) *AuthChallengeUpdateOne {
	_u.mutation.SetConsumedAt(v)
	return _u
}

// SetNillableConsumedAt sets the "consumed_at" field if the given value is not nil.
func (_u *AuthChallengeUpdateOne) SetNillableConsumedAt(v *time.Time) *AuthChallengeUpdateOne {
	if v != nil {
		_u.SetConsumedAt(*v)
	}
	return _u
}

// ClearConsumedAt clears the value of the "consumed_at" field.
func (_u *AuthChallengeUpdateOne) ClearConsumedAt() *AuthChallengeUpdateOne {
	_u.mutation.ClearConsumedAt()
	return _u
}

// SetRevokedAt sets the "revoked_at" field.
func (_u *AuthChallengeUpdateOne) SetRevokedAt(v time.Time) *AuthChallengeUpdateOne {
	_u.mutation.SetRevokedAt(v)
	return _u
}

// SetNillableRevokedAt sets the "revoked_at" field if the given value is not nil.
func (_u *AuthChallengeUpdateOne) SetNillableRevokedAt(v *time.Time) *AuthChallengeUpdateOne {
	if v != nil {
		_u.SetRevokedAt(*v)
	}
	return _u
}

// ClearRevokedAt clears the value of the "revoked_at" field.
func (_u *AuthChallengeUpdateOne) ClearRevokedAt() *AuthChallengeUpdateOne {
	_u.mutation.ClearRevokedAt()
	return _u
}

// SetEmailProviderMessageID sets the "email_provider_message_id" field.
func (_u *AuthChallengeUpdateOne) SetEmailProviderMessageID(v string) *AuthChallengeUpdateOne {
	_u.mutation.SetEmailProviderMessageID(v)
	return _u
}

// SetNillableEmailProviderMessageID sets the "email_provider_message_id" field if the given value is not nil.
func (_u *AuthChallengeUpdateOne) SetNillableEmailProviderMessageID(v *string) *AuthChallengeUpdateOne {
	if v != nil {
		_u.SetEmailProviderMessageID(*v)
	}
	return _u
}

// ClearEmailProviderMessageID clears the value of the "email_provider_message_id" field.
func (_u *AuthChallengeUpdateOne) ClearEmailProviderMessageID() *AuthChallengeUpdateOne {
	_u.mutation.ClearEmailProviderMessageID()
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *AuthChallengeUpdateOne) SetMetadata(v map[string]interface{}) *AuthChallengeUpdateOne {
	_u.mutation.SetMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *AuthChallengeUpdateOne) ClearMetadata() *AuthChallengeUpdateOne {
	_u.mutation.ClearMetadata()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AuthChallengeUpdateOne) SetUpdatedAt(v time.Time) *AuthChallengeUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *AuthChallengeUpdateOne) SetDeletedAt(v time.Time) *AuthChallengeUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *AuthChallengeUpdateOne) SetNillableDeletedAt(v *time.Time) *AuthChallengeUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *AuthChallengeUpdateOne) ClearDeletedAt() *AuthChallengeUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// Mutation returns the AuthChallengeMutation object of the builder.
func (_u *AuthChallengeUpdateOne) Mutation() *AuthChallengeMutation {
	return _u.mutation
}

// Where appends a list predicates to the AuthChallengeUpdate builder.
func (_u *AuthChallengeUpdateOne) Where(ps ...predicate.AuthChallenge) *AuthChallengeUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AuthChallengeUpdateOne) Select(field string, fields ...string) *AuthChallengeUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AuthChallenge entity.
func (_u *AuthChallengeUpdateOne) Save(ctx context.Context) (*AuthChallenge, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AuthChallengeUpdateOne) SaveX(ctx context.Context) *AuthChallenge {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AuthChallengeUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AuthChallengeUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AuthChallengeUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := authchallenge.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AuthChallengeUpdateOne) check() error {
	if v, ok := _u.mutation.Purpose(); ok {
		if err := authchallenge.PurposeValidator(v); err != nil {
			return &ValidationError{Name: "purpose", err: fmt.Errorf(`ent: validator failed for field "AuthChallenge.purpose": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DeliveryMethod(); ok {
		if err := authchallenge.DeliveryMethodValidator(v); err != nil {
			return &ValidationError{Name: "delivery_method", err: fmt.Errorf(`ent: validator failed for field "AuthChallenge.delivery_method": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Email(); ok {
		if err := authchallenge.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "AuthChallenge.email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SecretHash(); ok {
		if err := authchallenge.SecretHashValidator(v); err != nil {
			return &ValidationError{Name: "secret_hash", err: fmt.Errorf(`ent: validator failed for field "AuthChallenge.secret_hash": %w`, err)}
		}
	}
	return nil
}

func (_u *AuthChallengeUpdateOne) sqlSave(ctx context.Context) (_node *AuthChallenge, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(authchallenge.Table, authchallenge.Columns, sqlgraph.NewFieldSpec(authchallenge.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AuthChallenge.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, authchallenge.FieldID)
		for _, f := range fields {
			if !authchallenge.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != authchallenge.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Purpose(); ok {
		_spec.SetField(authchallenge.FieldPurpose, field.TypeString, value)
	}
	if value, ok := _u.mutation.DeliveryMethod(); ok {
		_spec.SetField(authchallenge.FieldDeliveryMethod, field.TypeString, value)
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(authchallenge.FieldEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(authchallenge.FieldUserID, field.TypeString, value)
	}
	if _u.mutation.UserIDCleared() {
		_spec.ClearField(authchallenge.FieldUserID, field.TypeString)
	}
	if value, ok := _u.mutation.SecretHash(); ok {
		_spec.SetField(authchallenge.FieldSecretHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.CodeHash(); ok {
		_spec.SetField(authchallenge.FieldCodeHash, field.TypeString, value)
	}
	if _u.mutation.CodeHashCleared() {
		_spec.ClearField(authchallenge.FieldCodeHash, field.TypeString)
	}
	if value, ok := _u.mutation.RedirectURL(); ok {
		_spec.SetField(authchallenge.FieldRedirectURL, field.TypeString, value)
	}
	if _u.mutation.RedirectURLCleared() {
		_spec.ClearField(authchallenge.FieldRedirectURL, field.TypeString)
	}
	if value, ok := _u.mutation.RequestIP(); ok {
		_spec.SetField(authchallenge.FieldRequestIP, field.TypeString, value)
	}
	if _u.mutation.RequestIPCleared() {
		_spec.ClearField(authchallenge.FieldRequestIP, field.TypeString)
	}
	if value, ok := _u.mutation.RequestUserAgent(); ok {
		_spec.SetField(authchallenge.FieldRequestUserAgent, field.TypeString, value)
	}
	if _u.mutation.RequestUserAgentCleared() {
		_spec.ClearField(authchallenge.FieldRequestUserAgent, field.TypeString)
	}
	if value, ok := _u.mutation.Attempts(); ok {
		_spec.SetField(authchallenge.FieldAttempts, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAttempts(); ok {
		_spec.AddField(authchallenge.FieldAttempts, field.TypeInt, value)
	}
	if value, ok := _u.mutation.MaxAttempts(); ok {
		_spec.SetField(authchallenge.FieldMaxAttempts, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxAttempts(); ok {
		_spec.AddField(authchallenge.FieldMaxAttempts, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(authchallenge.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(authchallenge.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ConsumedAt(); ok {
		_spec.SetField(authchallenge.FieldConsumedAt, field.TypeTime, value)
	}
	if _u.mutation.ConsumedAtCleared() {
		_spec.ClearField(authchallenge.FieldConsumedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.RevokedAt(); ok {
		_spec.SetField(authchallenge.FieldRevokedAt, field.TypeTime, value)
	}
	if _u.mutation.RevokedAtCleared() {
		_spec.ClearField(authchallenge.FieldRevokedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.EmailProviderMessageID(); ok {
		_spec.SetField(authchallenge.FieldEmailProviderMessageID, field.TypeString, value)
	}
	if _u.mutation.EmailProviderMessageIDCleared() {
		_spec.ClearField(authchallenge.FieldEmailProviderMessageID, field.TypeString)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(authchallenge.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(authchallenge.FieldMetadata, field.TypeJSON)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(authchallenge.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(authchallenge.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(authchallenge.FieldDeletedAt, field.TypeTime)
	}
	_node = &AuthChallenge{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{authchallenge.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
