// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/plystra/plystra/ent/backgroundjob"
)

// BackgroundJob is the model entity for the BackgroundJob schema.
type BackgroundJob struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// JobType holds the value of the "job_type" field.
	JobType string `json:"job_type,omitempty"`
	// Payload holds the value of the "payload" field.
	Payload map[string]interface{} `json:"payload,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// Attempts holds the value of the "attempts" field.
	Attempts int `json:"attempts,omitempty"`
	// MaxAttempts holds the value of the "max_attempts" field.
	MaxAttempts int `json:"max_attempts,omitempty"`
	// RunAfter holds the value of the "run_after" field.
	RunAfter time.Time `json:"run_after,omitempty"`
	// LastError holds the value of the "last_error" field.
	LastError *string `json:"last_error,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*BackgroundJob) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case backgroundjob.FieldPayload:
			values[i] = new([]byte)
		case backgroundjob.FieldAttempts, backgroundjob.FieldMaxAttempts:
			values[i] = new(sql.NullInt64)
		case backgroundjob.FieldID, backgroundjob.FieldJobType, backgroundjob.FieldStatus, backgroundjob.FieldLastError:
			values[i] = new(sql.NullString)
		case backgroundjob.FieldRunAfter, backgroundjob.FieldCreatedAt, backgroundjob.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the BackgroundJob fields.
func (_m *BackgroundJob) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case backgroundjob.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case backgroundjob.FieldJobType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field job_type", values[i])
			} else if value.Valid {
				_m.JobType = value.String
			}
		case backgroundjob.FieldPayload:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field payload", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Payload); err != nil {
					return fmt.Errorf("unmarshal field payload: %w", err)
				}
			}
		case backgroundjob.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case backgroundjob.FieldAttempts:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field attempts", values[i])
			} else if value.Valid {
				_m.Attempts = int(value.Int64)
			}
		case backgroundjob.FieldMaxAttempts:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field max_attempts", values[i])
			} else if value.Valid {
				_m.MaxAttempts = int(value.Int64)
			}
		case backgroundjob.FieldRunAfter:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field run_after", values[i])
			} else if value.Valid {
				_m.RunAfter = value.Time
			}
		case backgroundjob.FieldLastError:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field last_error", values[i])
			} else if value.Valid {
				_m.LastError = new(string)
				*_m.LastError = value.String
			}
		case backgroundjob.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case backgroundjob.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the BackgroundJob.
// This includes values selected through modifiers, order, etc.
func (_m *BackgroundJob) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this BackgroundJob.
// Note that you need to call BackgroundJob.Unwrap() before calling this method if this BackgroundJob
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *BackgroundJob) Update() *BackgroundJobUpdateOne {
	return NewBackgroundJobClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the BackgroundJob entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *BackgroundJob) Unwrap() *BackgroundJob {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: BackgroundJob is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *BackgroundJob) String() string {
	var builder strings.Builder
	builder.WriteString("BackgroundJob(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("job_type=")
	builder.WriteString(_m.JobType)
	builder.WriteString(", ")
	builder.WriteString("payload=")
	builder.WriteString(fmt.Sprintf("%v", _m.Payload))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("attempts=")
	builder.WriteString(fmt.Sprintf("%v", _m.Attempts))
	builder.WriteString(", ")
	builder.WriteString("max_attempts=")
	builder.WriteString(fmt.Sprintf("%v", _m.MaxAttempts))
	builder.WriteString(", ")
	builder.WriteString("run_after=")
	builder.WriteString(_m.RunAfter.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.LastError; v != nil {
		builder.WriteString("last_error=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// BackgroundJobs is a parsable slice of BackgroundJob.
type BackgroundJobs []*BackgroundJob
