// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/plystra/core/ent/providermigrationrevision"
)

// ProviderMigrationRevisionCreate is the builder for creating a ProviderMigrationRevision entity.
type ProviderMigrationRevisionCreate struct {
	config
	mutation *ProviderMigrationRevisionMutation
	hooks    []Hook
}

// SetProviderPluginID sets the "provider_plugin_id" field.
func (_c *ProviderMigrationRevisionCreate) SetProviderPluginID(v string) *ProviderMigrationRevisionCreate {
	_c.mutation.SetProviderPluginID(v)
	return _c
}

// SetInstallationID sets the "installation_id" field.
func (_c *ProviderMigrationRevisionCreate) SetInstallationID(v string) *ProviderMigrationRevisionCreate {
	_c.mutation.SetInstallationID(v)
	return _c
}

// SetRevision sets the "revision" field.
func (_c *ProviderMigrationRevisionCreate) SetRevision(v string) *ProviderMigrationRevisionCreate {
	_c.mutation.SetRevision(v)
	return _c
}

// SetBundleHash sets the "bundle_hash" field.
func (_c *ProviderMigrationRevisionCreate) SetBundleHash(v string) *ProviderMigrationRevisionCreate {
	_c.mutation.SetBundleHash(v)
	return _c
}

// SetSchemaName sets the "schema_name" field.
func (_c *ProviderMigrationRevisionCreate) SetSchemaName(v string) *ProviderMigrationRevisionCreate {
	_c.mutation.SetSchemaName(v)
	return _c
}

// SetFromSchemaVersion sets the "from_schema_version" field.
func (_c *ProviderMigrationRevisionCreate) SetFromSchemaVersion(v int) *ProviderMigrationRevisionCreate {
	_c.mutation.SetFromSchemaVersion(v)
	return _c
}

// SetNillableFromSchemaVersion sets the "from_schema_version" field if the given value is not nil.
func (_c *ProviderMigrationRevisionCreate) SetNillableFromSchemaVersion(v *int) *ProviderMigrationRevisionCreate {
	if v != nil {
		_c.SetFromSchemaVersion(*v)
	}
	return _c
}

// SetToSchemaVersion sets the "to_schema_version" field.
func (_c *ProviderMigrationRevisionCreate) SetToSchemaVersion(v int) *ProviderMigrationRevisionCreate {
	_c.mutation.SetToSchemaVersion(v)
	return _c
}

// SetNillableToSchemaVersion sets the "to_schema_version" field if the given value is not nil.
func (_c *ProviderMigrationRevisionCreate) SetNillableToSchemaVersion(v *int) *ProviderMigrationRevisionCreate {
	if v != nil {
		_c.SetToSchemaVersion(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *ProviderMigrationRevisionCreate) SetStatus(v string) *ProviderMigrationRevisionCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *ProviderMigrationRevisionCreate) SetNillableStatus(v *string) *ProviderMigrationRevisionCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetDestructive sets the "destructive" field.
func (_c *ProviderMigrationRevisionCreate) SetDestructive(v bool) *ProviderMigrationRevisionCreate {
	_c.mutation.SetDestructive(v)
	return _c
}

// SetNillableDestructive sets the "destructive" field if the given value is not nil.
func (_c *ProviderMigrationRevisionCreate) SetNillableDestructive(v *bool) *ProviderMigrationRevisionCreate {
	if v != nil {
		_c.SetDestructive(*v)
	}
	return _c
}

// SetRlsBypass sets the "rls_bypass" field.
func (_c *ProviderMigrationRevisionCreate) SetRlsBypass(v bool) *ProviderMigrationRevisionCreate {
	_c.mutation.SetRlsBypass(v)
	return _c
}

// SetNillableRlsBypass sets the "rls_bypass" field if the given value is not nil.
func (_c *ProviderMigrationRevisionCreate) SetNillableRlsBypass(v *bool) *ProviderMigrationRevisionCreate {
	if v != nil {
		_c.SetRlsBypass(*v)
	}
	return _c
}

// SetRequiresManualReview sets the "requires_manual_review" field.
func (_c *ProviderMigrationRevisionCreate) SetRequiresManualReview(v bool) *ProviderMigrationRevisionCreate {
	_c.mutation.SetRequiresManualReview(v)
	return _c
}

// SetNillableRequiresManualReview sets the "requires_manual_review" field if the given value is not nil.
func (_c *ProviderMigrationRevisionCreate) SetNillableRequiresManualReview(v *bool) *ProviderMigrationRevisionCreate {
	if v != nil {
		_c.SetRequiresManualReview(*v)
	}
	return _c
}

// SetReviewedByUserID sets the "reviewed_by_user_id" field.
func (_c *ProviderMigrationRevisionCreate) SetReviewedByUserID(v string) *ProviderMigrationRevisionCreate {
	_c.mutation.SetReviewedByUserID(v)
	return _c
}

// SetNillableReviewedByUserID sets the "reviewed_by_user_id" field if the given value is not nil.
func (_c *ProviderMigrationRevisionCreate) SetNillableReviewedByUserID(v *string) *ProviderMigrationRevisionCreate {
	if v != nil {
		_c.SetReviewedByUserID(*v)
	}
	return _c
}

// SetReviewedAt sets the "reviewed_at" field.
func (_c *ProviderMigrationRevisionCreate) SetReviewedAt(v time.Time) *ProviderMigrationRevisionCreate {
	_c.mutation.SetReviewedAt(v)
	return _c
}

// SetNillableReviewedAt sets the "reviewed_at" field if the given value is not nil.
func (_c *ProviderMigrationRevisionCreate) SetNillableReviewedAt(v *time.Time) *ProviderMigrationRevisionCreate {
	if v != nil {
		_c.SetReviewedAt(*v)
	}
	return _c
}

// SetStartedAt sets the "started_at" field.
func (_c *ProviderMigrationRevisionCreate) SetStartedAt(v time.Time) *ProviderMigrationRevisionCreate {
	_c.mutation.SetStartedAt(v)
	return _c
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_c *ProviderMigrationRevisionCreate) SetNillableStartedAt(v *time.Time) *ProviderMigrationRevisionCreate {
	if v != nil {
		_c.SetStartedAt(*v)
	}
	return _c
}

// SetFinishedAt sets the "finished_at" field.
func (_c *ProviderMigrationRevisionCreate) SetFinishedAt(v time.Time) *ProviderMigrationRevisionCreate {
	_c.mutation.SetFinishedAt(v)
	return _c
}

// SetNillableFinishedAt sets the "finished_at" field if the given value is not nil.
func (_c *ProviderMigrationRevisionCreate) SetNillableFinishedAt(v *time.Time) *ProviderMigrationRevisionCreate {
	if v != nil {
		_c.SetFinishedAt(*v)
	}
	return _c
}

// SetLastError sets the "last_error" field.
func (_c *ProviderMigrationRevisionCreate) SetLastError(v string) *ProviderMigrationRevisionCreate {
	_c.mutation.SetLastError(v)
	return _c
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_c *ProviderMigrationRevisionCreate) SetNillableLastError(v *string) *ProviderMigrationRevisionCreate {
	if v != nil {
		_c.SetLastError(*v)
	}
	return _c
}

// SetMetadata sets the "metadata" field.
func (_c *ProviderMigrationRevisionCreate) SetMetadata(v map[string]interface{}) *ProviderMigrationRevisionCreate {
	_c.mutation.SetMetadata(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ProviderMigrationRevisionCreate) SetCreatedAt(v time.Time) *ProviderMigrationRevisionCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ProviderMigrationRevisionCreate) SetNillableCreatedAt(v *time.Time) *ProviderMigrationRevisionCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ProviderMigrationRevisionCreate) SetUpdatedAt(v time.Time) *ProviderMigrationRevisionCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ProviderMigrationRevisionCreate) SetNillableUpdatedAt(v *time.Time) *ProviderMigrationRevisionCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ProviderMigrationRevisionCreate) SetID(v string) *ProviderMigrationRevisionCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the ProviderMigrationRevisionMutation object of the builder.
func (_c *ProviderMigrationRevisionCreate) Mutation() *ProviderMigrationRevisionMutation {
	return _c.mutation
}

// Save creates the ProviderMigrationRevision in the database.
func (_c *ProviderMigrationRevisionCreate) Save(ctx context.Context) (*ProviderMigrationRevision, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ProviderMigrationRevisionCreate) SaveX(ctx context.Context) *ProviderMigrationRevision {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ProviderMigrationRevisionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ProviderMigrationRevisionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ProviderMigrationRevisionCreate) defaults() {
	if _, ok := _c.mutation.FromSchemaVersion(); !ok {
		v := providermigrationrevision.DefaultFromSchemaVersion
		_c.mutation.SetFromSchemaVersion(v)
	}
	if _, ok := _c.mutation.ToSchemaVersion(); !ok {
		v := providermigrationrevision.DefaultToSchemaVersion
		_c.mutation.SetToSchemaVersion(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := providermigrationrevision.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.Destructive(); !ok {
		v := providermigrationrevision.DefaultDestructive
		_c.mutation.SetDestructive(v)
	}
	if _, ok := _c.mutation.RlsBypass(); !ok {
		v := providermigrationrevision.DefaultRlsBypass
		_c.mutation.SetRlsBypass(v)
	}
	if _, ok := _c.mutation.RequiresManualReview(); !ok {
		v := providermigrationrevision.DefaultRequiresManualReview
		_c.mutation.SetRequiresManualReview(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := providermigrationrevision.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := providermigrationrevision.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ProviderMigrationRevisionCreate) check() error {
	if _, ok := _c.mutation.ProviderPluginID(); !ok {
		return &ValidationError{Name: "provider_plugin_id", err: errors.New(`ent: missing required field "ProviderMigrationRevision.provider_plugin_id"`)}
	}
	if v, ok := _c.mutation.ProviderPluginID(); ok {
		if err := providermigrationrevision.ProviderPluginIDValidator(v); err != nil {
			return &ValidationError{Name: "provider_plugin_id", err: fmt.Errorf(`ent: validator failed for field "ProviderMigrationRevision.provider_plugin_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.InstallationID(); !ok {
		return &ValidationError{Name: "installation_id", err: errors.New(`ent: missing required field "ProviderMigrationRevision.installation_id"`)}
	}
	if v, ok := _c.mutation.InstallationID(); ok {
		if err := providermigrationrevision.InstallationIDValidator(v); err != nil {
			return &ValidationError{Name: "installation_id", err: fmt.Errorf(`ent: validator failed for field "ProviderMigrationRevision.installation_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Revision(); !ok {
		return &ValidationError{Name: "revision", err: errors.New(`ent: missing required field "ProviderMigrationRevision.revision"`)}
	}
	if v, ok := _c.mutation.Revision(); ok {
		if err := providermigrationrevision.RevisionValidator(v); err != nil {
			return &ValidationError{Name: "revision", err: fmt.Errorf(`ent: validator failed for field "ProviderMigrationRevision.revision": %w`, err)}
		}
	}
	if _, ok := _c.mutation.BundleHash(); !ok {
		return &ValidationError{Name: "bundle_hash", err: errors.New(`ent: missing required field "ProviderMigrationRevision.bundle_hash"`)}
	}
	if v, ok := _c.mutation.BundleHash(); ok {
		if err := providermigrationrevision.BundleHashValidator(v); err != nil {
			return &ValidationError{Name: "bundle_hash", err: fmt.Errorf(`ent: validator failed for field "ProviderMigrationRevision.bundle_hash": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SchemaName(); !ok {
		return &ValidationError{Name: "schema_name", err: errors.New(`ent: missing required field "ProviderMigrationRevision.schema_name"`)}
	}
	if v, ok := _c.mutation.SchemaName(); ok {
		if err := providermigrationrevision.SchemaNameValidator(v); err != nil {
			return &ValidationError{Name: "schema_name", err: fmt.Errorf(`ent: validator failed for field "ProviderMigrationRevision.schema_name": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := providermigrationrevision.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "ProviderMigrationRevision.id": %w`, err)}
		}
	}
	return nil
}

func (_c *ProviderMigrationRevisionCreate) sqlSave(ctx context.Context) (*ProviderMigrationRevision, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected ProviderMigrationRevision.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ProviderMigrationRevisionCreate) createSpec() (*ProviderMigrationRevision, *sqlgraph.CreateSpec) {
	var (
		_node = &ProviderMigrationRevision{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(providermigrationrevision.Table, sqlgraph.NewFieldSpec(providermigrationrevision.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.ProviderPluginID(); ok {
		_spec.SetField(providermigrationrevision.FieldProviderPluginID, field.TypeString, value)
		_node.ProviderPluginID = value
	}
	if value, ok := _c.mutation.InstallationID(); ok {
		_spec.SetField(providermigrationrevision.FieldInstallationID, field.TypeString, value)
		_node.InstallationID = value
	}
	if value, ok := _c.mutation.Revision(); ok {
		_spec.SetField(providermigrationrevision.FieldRevision, field.TypeString, value)
		_node.Revision = value
	}
	if value, ok := _c.mutation.BundleHash(); ok {
		_spec.SetField(providermigrationrevision.FieldBundleHash, field.TypeString, value)
		_node.BundleHash = value
	}
	if value, ok := _c.mutation.SchemaName(); ok {
		_spec.SetField(providermigrationrevision.FieldSchemaName, field.TypeString, value)
		_node.SchemaName = value
	}
	if value, ok := _c.mutation.FromSchemaVersion(); ok {
		_spec.SetField(providermigrationrevision.FieldFromSchemaVersion, field.TypeInt, value)
		_node.FromSchemaVersion = value
	}
	if value, ok := _c.mutation.ToSchemaVersion(); ok {
		_spec.SetField(providermigrationrevision.FieldToSchemaVersion, field.TypeInt, value)
		_node.ToSchemaVersion = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(providermigrationrevision.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Destructive(); ok {
		_spec.SetField(providermigrationrevision.FieldDestructive, field.TypeBool, value)
		_node.Destructive = value
	}
	if value, ok := _c.mutation.RlsBypass(); ok {
		_spec.SetField(providermigrationrevision.FieldRlsBypass, field.TypeBool, value)
		_node.RlsBypass = value
	}
	if value, ok := _c.mutation.RequiresManualReview(); ok {
		_spec.SetField(providermigrationrevision.FieldRequiresManualReview, field.TypeBool, value)
		_node.RequiresManualReview = value
	}
	if value, ok := _c.mutation.ReviewedByUserID(); ok {
		_spec.SetField(providermigrationrevision.FieldReviewedByUserID, field.TypeString, value)
		_node.ReviewedByUserID = &value
	}
	if value, ok := _c.mutation.ReviewedAt(); ok {
		_spec.SetField(providermigrationrevision.FieldReviewedAt, field.TypeTime, value)
		_node.ReviewedAt = &value
	}
	if value, ok := _c.mutation.StartedAt(); ok {
		_spec.SetField(providermigrationrevision.FieldStartedAt, field.TypeTime, value)
		_node.StartedAt = &value
	}
	if value, ok := _c.mutation.FinishedAt(); ok {
		_spec.SetField(providermigrationrevision.FieldFinishedAt, field.TypeTime, value)
		_node.FinishedAt = &value
	}
	if value, ok := _c.mutation.LastError(); ok {
		_spec.SetField(providermigrationrevision.FieldLastError, field.TypeString, value)
		_node.LastError = &value
	}
	if value, ok := _c.mutation.Metadata(); ok {
		_spec.SetField(providermigrationrevision.FieldMetadata, field.TypeJSON, value)
		_node.Metadata = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(providermigrationrevision.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(providermigrationrevision.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// ProviderMigrationRevisionCreateBulk is the builder for creating many ProviderMigrationRevision entities in bulk.
type ProviderMigrationRevisionCreateBulk struct {
	config
	err      error
	builders []*ProviderMigrationRevisionCreate
}

// Save creates the ProviderMigrationRevision entities in the database.
func (_c *ProviderMigrationRevisionCreateBulk) Save(ctx context.Context) ([]*ProviderMigrationRevision, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ProviderMigrationRevision, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ProviderMigrationRevisionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ProviderMigrationRevisionCreateBulk) SaveX(ctx context.Context) []*ProviderMigrationRevision {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ProviderMigrationRevisionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ProviderMigrationRevisionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
