// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/plystra/core/ent/predicate"
	"github.com/plystra/core/ent/resourcetype"
)

// ResourceTypeDelete is the builder for deleting a ResourceType entity.
type ResourceTypeDelete struct {
	config
	hooks    []Hook
	mutation *ResourceTypeMutation
}

// Where appends a list predicates to the ResourceTypeDelete builder.
func (_d *ResourceTypeDelete) Where(ps ...predicate.ResourceType) *ResourceTypeDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *ResourceTypeDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ResourceTypeDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *ResourceTypeDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(resourcetype.Table, sqlgraph.NewFieldSpec(resourcetype.FieldID, field.TypeString))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// ResourceTypeDeleteOne is the builder for deleting a single ResourceType entity.
type ResourceTypeDeleteOne struct {
	_d *ResourceTypeDelete
}

// Where appends a list predicates to the ResourceTypeDelete builder.
func (_d *ResourceTypeDeleteOne) Where(ps ...predicate.ResourceType) *ResourceTypeDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *ResourceTypeDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{resourcetype.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ResourceTypeDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
