// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/plystra/plystra/ent/templateinstallation"
)

// TemplateInstallationCreate is the builder for creating a TemplateInstallation entity.
type TemplateInstallationCreate struct {
	config
	mutation *TemplateInstallationMutation
	hooks    []Hook
}

// SetTemplateID sets the "template_id" field.
func (_c *TemplateInstallationCreate) SetTemplateID(v string) *TemplateInstallationCreate {
	_c.mutation.SetTemplateID(v)
	return _c
}

// SetTemplateVersion sets the "template_version" field.
func (_c *TemplateInstallationCreate) SetTemplateVersion(v string) *TemplateInstallationCreate {
	_c.mutation.SetTemplateVersion(v)
	return _c
}

// SetSpaceID sets the "space_id" field.
func (_c *TemplateInstallationCreate) SetSpaceID(v string) *TemplateInstallationCreate {
	_c.mutation.SetSpaceID(v)
	return _c
}

// SetNillableSpaceID sets the "space_id" field if the given value is not nil.
func (_c *TemplateInstallationCreate) SetNillableSpaceID(v *string) *TemplateInstallationCreate {
	if v != nil {
		_c.SetSpaceID(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *TemplateInstallationCreate) SetStatus(v string) *TemplateInstallationCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *TemplateInstallationCreate) SetNillableStatus(v *string) *TemplateInstallationCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetManifestSnapshot sets the "manifest_snapshot" field.
func (_c *TemplateInstallationCreate) SetManifestSnapshot(v map[string]interface{}) *TemplateInstallationCreate {
	_c.mutation.SetManifestSnapshot(v)
	return _c
}

// SetInstalledByUserID sets the "installed_by_user_id" field.
func (_c *TemplateInstallationCreate) SetInstalledByUserID(v string) *TemplateInstallationCreate {
	_c.mutation.SetInstalledByUserID(v)
	return _c
}

// SetNillableInstalledByUserID sets the "installed_by_user_id" field if the given value is not nil.
func (_c *TemplateInstallationCreate) SetNillableInstalledByUserID(v *string) *TemplateInstallationCreate {
	if v != nil {
		_c.SetInstalledByUserID(*v)
	}
	return _c
}

// SetInstalledByMemberID sets the "installed_by_member_id" field.
func (_c *TemplateInstallationCreate) SetInstalledByMemberID(v string) *TemplateInstallationCreate {
	_c.mutation.SetInstalledByMemberID(v)
	return _c
}

// SetNillableInstalledByMemberID sets the "installed_by_member_id" field if the given value is not nil.
func (_c *TemplateInstallationCreate) SetNillableInstalledByMemberID(v *string) *TemplateInstallationCreate {
	if v != nil {
		_c.SetInstalledByMemberID(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *TemplateInstallationCreate) SetCreatedAt(v time.Time) *TemplateInstallationCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *TemplateInstallationCreate) SetNillableCreatedAt(v *time.Time) *TemplateInstallationCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *TemplateInstallationCreate) SetID(v string) *TemplateInstallationCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the TemplateInstallationMutation object of the builder.
func (_c *TemplateInstallationCreate) Mutation() *TemplateInstallationMutation {
	return _c.mutation
}

// Save creates the TemplateInstallation in the database.
func (_c *TemplateInstallationCreate) Save(ctx context.Context) (*TemplateInstallation, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *TemplateInstallationCreate) SaveX(ctx context.Context) *TemplateInstallation {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TemplateInstallationCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TemplateInstallationCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *TemplateInstallationCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := templateinstallation.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := templateinstallation.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *TemplateInstallationCreate) check() error {
	if _, ok := _c.mutation.TemplateID(); !ok {
		return &ValidationError{Name: "template_id", err: errors.New(`ent: missing required field "TemplateInstallation.template_id"`)}
	}
	if v, ok := _c.mutation.TemplateID(); ok {
		if err := templateinstallation.TemplateIDValidator(v); err != nil {
			return &ValidationError{Name: "template_id", err: fmt.Errorf(`ent: validator failed for field "TemplateInstallation.template_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TemplateVersion(); !ok {
		return &ValidationError{Name: "template_version", err: errors.New(`ent: missing required field "TemplateInstallation.template_version"`)}
	}
	if v, ok := _c.mutation.TemplateVersion(); ok {
		if err := templateinstallation.TemplateVersionValidator(v); err != nil {
			return &ValidationError{Name: "template_version", err: fmt.Errorf(`ent: validator failed for field "TemplateInstallation.template_version": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ManifestSnapshot(); !ok {
		return &ValidationError{Name: "manifest_snapshot", err: errors.New(`ent: missing required field "TemplateInstallation.manifest_snapshot"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := templateinstallation.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "TemplateInstallation.id": %w`, err)}
		}
	}
	return nil
}

func (_c *TemplateInstallationCreate) sqlSave(ctx context.Context) (*TemplateInstallation, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected TemplateInstallation.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *TemplateInstallationCreate) createSpec() (*TemplateInstallation, *sqlgraph.CreateSpec) {
	var (
		_node = &TemplateInstallation{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(templateinstallation.Table, sqlgraph.NewFieldSpec(templateinstallation.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.TemplateID(); ok {
		_spec.SetField(templateinstallation.FieldTemplateID, field.TypeString, value)
		_node.TemplateID = value
	}
	if value, ok := _c.mutation.TemplateVersion(); ok {
		_spec.SetField(templateinstallation.FieldTemplateVersion, field.TypeString, value)
		_node.TemplateVersion = value
	}
	if value, ok := _c.mutation.SpaceID(); ok {
		_spec.SetField(templateinstallation.FieldSpaceID, field.TypeString, value)
		_node.SpaceID = &value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(templateinstallation.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.ManifestSnapshot(); ok {
		_spec.SetField(templateinstallation.FieldManifestSnapshot, field.TypeJSON, value)
		_node.ManifestSnapshot = value
	}
	if value, ok := _c.mutation.InstalledByUserID(); ok {
		_spec.SetField(templateinstallation.FieldInstalledByUserID, field.TypeString, value)
		_node.InstalledByUserID = &value
	}
	if value, ok := _c.mutation.InstalledByMemberID(); ok {
		_spec.SetField(templateinstallation.FieldInstalledByMemberID, field.TypeString, value)
		_node.InstalledByMemberID = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(templateinstallation.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// TemplateInstallationCreateBulk is the builder for creating many TemplateInstallation entities in bulk.
type TemplateInstallationCreateBulk struct {
	config
	err      error
	builders []*TemplateInstallationCreate
}

// Save creates the TemplateInstallation entities in the database.
func (_c *TemplateInstallationCreateBulk) Save(ctx context.Context) ([]*TemplateInstallation, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*TemplateInstallation, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TemplateInstallationMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *TemplateInstallationCreateBulk) SaveX(ctx context.Context) []*TemplateInstallation {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TemplateInstallationCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TemplateInstallationCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
