// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/plystra/plystra/ent/predicate"
	"github.com/plystra/plystra/ent/usermember"
)

// UserMemberUpdate is the builder for updating UserMember entities.
type UserMemberUpdate struct {
	config
	hooks    []Hook
	mutation *UserMemberMutation
}

// Where appends a list predicates to the UserMemberUpdate builder.
func (_u *UserMemberUpdate) Where(ps ...predicate.UserMember) *UserMemberUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *UserMemberUpdate) SetUserID(v string) *UserMemberUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *UserMemberUpdate) SetNillableUserID(v *string) *UserMemberUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetMemberID sets the "member_id" field.
func (_u *UserMemberUpdate) SetMemberID(v string) *UserMemberUpdate {
	_u.mutation.SetMemberID(v)
	return _u
}

// SetNillableMemberID sets the "member_id" field if the given value is not nil.
func (_u *UserMemberUpdate) SetNillableMemberID(v *string) *UserMemberUpdate {
	if v != nil {
		_u.SetMemberID(*v)
	}
	return _u
}

// SetSpaceID sets the "space_id" field.
func (_u *UserMemberUpdate) SetSpaceID(v string) *UserMemberUpdate {
	_u.mutation.SetSpaceID(v)
	return _u
}

// SetNillableSpaceID sets the "space_id" field if the given value is not nil.
func (_u *UserMemberUpdate) SetNillableSpaceID(v *string) *UserMemberUpdate {
	if v != nil {
		_u.SetSpaceID(*v)
	}
	return _u
}

// SetRelationType sets the "relation_type" field.
func (_u *UserMemberUpdate) SetRelationType(v string) *UserMemberUpdate {
	_u.mutation.SetRelationType(v)
	return _u
}

// SetNillableRelationType sets the "relation_type" field if the given value is not nil.
func (_u *UserMemberUpdate) SetNillableRelationType(v *string) *UserMemberUpdate {
	if v != nil {
		_u.SetRelationType(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *UserMemberUpdate) SetStatus(v string) *UserMemberUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *UserMemberUpdate) SetNillableStatus(v *string) *UserMemberUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetIsPrimary sets the "is_primary" field.
func (_u *UserMemberUpdate) SetIsPrimary(v bool) *UserMemberUpdate {
	_u.mutation.SetIsPrimary(v)
	return _u
}

// SetNillableIsPrimary sets the "is_primary" field if the given value is not nil.
func (_u *UserMemberUpdate) SetNillableIsPrimary(v *bool) *UserMemberUpdate {
	if v != nil {
		_u.SetIsPrimary(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *UserMemberUpdate) SetExpiresAt(v time.Time) *UserMemberUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *UserMemberUpdate) SetNillableExpiresAt(v *time.Time) *UserMemberUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *UserMemberUpdate) ClearExpiresAt() *UserMemberUpdate {
	_u.mutation.ClearExpiresAt()
	return _u
}

// SetLinkedByMemberID sets the "linked_by_member_id" field.
func (_u *UserMemberUpdate) SetLinkedByMemberID(v string) *UserMemberUpdate {
	_u.mutation.SetLinkedByMemberID(v)
	return _u
}

// SetNillableLinkedByMemberID sets the "linked_by_member_id" field if the given value is not nil.
func (_u *UserMemberUpdate) SetNillableLinkedByMemberID(v *string) *UserMemberUpdate {
	if v != nil {
		_u.SetLinkedByMemberID(*v)
	}
	return _u
}

// ClearLinkedByMemberID clears the value of the "linked_by_member_id" field.
func (_u *UserMemberUpdate) ClearLinkedByMemberID() *UserMemberUpdate {
	_u.mutation.ClearLinkedByMemberID()
	return _u
}

// SetLinkedAt sets the "linked_at" field.
func (_u *UserMemberUpdate) SetLinkedAt(v time.Time) *UserMemberUpdate {
	_u.mutation.SetLinkedAt(v)
	return _u
}

// SetNillableLinkedAt sets the "linked_at" field if the given value is not nil.
func (_u *UserMemberUpdate) SetNillableLinkedAt(v *time.Time) *UserMemberUpdate {
	if v != nil {
		_u.SetLinkedAt(*v)
	}
	return _u
}

// ClearLinkedAt clears the value of the "linked_at" field.
func (_u *UserMemberUpdate) ClearLinkedAt() *UserMemberUpdate {
	_u.mutation.ClearLinkedAt()
	return _u
}

// SetRevokedAt sets the "revoked_at" field.
func (_u *UserMemberUpdate) SetRevokedAt(v time.Time) *UserMemberUpdate {
	_u.mutation.SetRevokedAt(v)
	return _u
}

// SetNillableRevokedAt sets the "revoked_at" field if the given value is not nil.
func (_u *UserMemberUpdate) SetNillableRevokedAt(v *time.Time) *UserMemberUpdate {
	if v != nil {
		_u.SetRevokedAt(*v)
	}
	return _u
}

// ClearRevokedAt clears the value of the "revoked_at" field.
func (_u *UserMemberUpdate) ClearRevokedAt() *UserMemberUpdate {
	_u.mutation.ClearRevokedAt()
	return _u
}

// SetRevokedReason sets the "revoked_reason" field.
func (_u *UserMemberUpdate) SetRevokedReason(v string) *UserMemberUpdate {
	_u.mutation.SetRevokedReason(v)
	return _u
}

// SetNillableRevokedReason sets the "revoked_reason" field if the given value is not nil.
func (_u *UserMemberUpdate) SetNillableRevokedReason(v *string) *UserMemberUpdate {
	if v != nil {
		_u.SetRevokedReason(*v)
	}
	return _u
}

// ClearRevokedReason clears the value of the "revoked_reason" field.
func (_u *UserMemberUpdate) ClearRevokedReason() *UserMemberUpdate {
	_u.mutation.ClearRevokedReason()
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *UserMemberUpdate) SetMetadata(v map[string]interface{}) *UserMemberUpdate {
	_u.mutation.SetMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *UserMemberUpdate) ClearMetadata() *UserMemberUpdate {
	_u.mutation.ClearMetadata()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserMemberUpdate) SetUpdatedAt(v time.Time) *UserMemberUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *UserMemberUpdate) SetDeletedAt(v time.Time) *UserMemberUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *UserMemberUpdate) SetNillableDeletedAt(v *time.Time) *UserMemberUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *UserMemberUpdate) ClearDeletedAt() *UserMemberUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// Mutation returns the UserMemberMutation object of the builder.
func (_u *UserMemberUpdate) Mutation() *UserMemberMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UserMemberUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserMemberUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UserMemberUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserMemberUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserMemberUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := usermember.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserMemberUpdate) check() error {
	if v, ok := _u.mutation.UserID(); ok {
		if err := usermember.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "UserMember.user_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MemberID(); ok {
		if err := usermember.MemberIDValidator(v); err != nil {
			return &ValidationError{Name: "member_id", err: fmt.Errorf(`ent: validator failed for field "UserMember.member_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SpaceID(); ok {
		if err := usermember.SpaceIDValidator(v); err != nil {
			return &ValidationError{Name: "space_id", err: fmt.Errorf(`ent: validator failed for field "UserMember.space_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RelationType(); ok {
		if err := usermember.RelationTypeValidator(v); err != nil {
			return &ValidationError{Name: "relation_type", err: fmt.Errorf(`ent: validator failed for field "UserMember.relation_type": %w`, err)}
		}
	}
	return nil
}

func (_u *UserMemberUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(usermember.Table, usermember.Columns, sqlgraph.NewFieldSpec(usermember.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(usermember.FieldUserID, field.TypeString, value)
	}
	if value, ok := _u.mutation.MemberID(); ok {
		_spec.SetField(usermember.FieldMemberID, field.TypeString, value)
	}
	if value, ok := _u.mutation.SpaceID(); ok {
		_spec.SetField(usermember.FieldSpaceID, field.TypeString, value)
	}
	if value, ok := _u.mutation.RelationType(); ok {
		_spec.SetField(usermember.FieldRelationType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(usermember.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsPrimary(); ok {
		_spec.SetField(usermember.FieldIsPrimary, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(usermember.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(usermember.FieldExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LinkedByMemberID(); ok {
		_spec.SetField(usermember.FieldLinkedByMemberID, field.TypeString, value)
	}
	if _u.mutation.LinkedByMemberIDCleared() {
		_spec.ClearField(usermember.FieldLinkedByMemberID, field.TypeString)
	}
	if value, ok := _u.mutation.LinkedAt(); ok {
		_spec.SetField(usermember.FieldLinkedAt, field.TypeTime, value)
	}
	if _u.mutation.LinkedAtCleared() {
		_spec.ClearField(usermember.FieldLinkedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.RevokedAt(); ok {
		_spec.SetField(usermember.FieldRevokedAt, field.TypeTime, value)
	}
	if _u.mutation.RevokedAtCleared() {
		_spec.ClearField(usermember.FieldRevokedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.RevokedReason(); ok {
		_spec.SetField(usermember.FieldRevokedReason, field.TypeString, value)
	}
	if _u.mutation.RevokedReasonCleared() {
		_spec.ClearField(usermember.FieldRevokedReason, field.TypeString)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(usermember.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(usermember.FieldMetadata, field.TypeJSON)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(usermember.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(usermember.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(usermember.FieldDeletedAt, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{usermember.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UserMemberUpdateOne is the builder for updating a single UserMember entity.
type UserMemberUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserMemberMutation
}

// SetUserID sets the "user_id" field.
func (_u *UserMemberUpdateOne) SetUserID(v string) *UserMemberUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *UserMemberUpdateOne) SetNillableUserID(v *string) *UserMemberUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetMemberID sets the "member_id" field.
func (_u *UserMemberUpdateOne) SetMemberID(v string) *UserMemberUpdateOne {
	_u.mutation.SetMemberID(v)
	return _u
}

// SetNillableMemberID sets the "member_id" field if the given value is not nil.
func (_u *UserMemberUpdateOne) SetNillableMemberID(v *string) *UserMemberUpdateOne {
	if v != nil {
		_u.SetMemberID(*v)
	}
	return _u
}

// SetSpaceID sets the "space_id" field.
func (_u *UserMemberUpdateOne) SetSpaceID(v string) *UserMemberUpdateOne {
	_u.mutation.SetSpaceID(v)
	return _u
}

// SetNillableSpaceID sets the "space_id" field if the given value is not nil.
func (_u *UserMemberUpdateOne) SetNillableSpaceID(v *string) *UserMemberUpdateOne {
	if v != nil {
		_u.SetSpaceID(*v)
	}
	return _u
}

// SetRelationType sets the "relation_type" field.
func (_u *UserMemberUpdateOne) SetRelationType(v string) *UserMemberUpdateOne {
	_u.mutation.SetRelationType(v)
	return _u
}

// SetNillableRelationType sets the "relation_type" field if the given value is not nil.
func (_u *UserMemberUpdateOne) SetNillableRelationType(v *string) *UserMemberUpdateOne {
	if v != nil {
		_u.SetRelationType(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *UserMemberUpdateOne) SetStatus(v string) *UserMemberUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *UserMemberUpdateOne) SetNillableStatus(v *string) *UserMemberUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetIsPrimary sets the "is_primary" field.
func (_u *UserMemberUpdateOne) SetIsPrimary(v bool) *UserMemberUpdateOne {
	_u.mutation.SetIsPrimary(v)
	return _u
}

// SetNillableIsPrimary sets the "is_primary" field if the given value is not nil.
func (_u *UserMemberUpdateOne) SetNillableIsPrimary(v *bool) *UserMemberUpdateOne {
	if v != nil {
		_u.SetIsPrimary(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *UserMemberUpdateOne) SetExpiresAt(v time.Time) *UserMemberUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *UserMemberUpdateOne) SetNillableExpiresAt(v *time.Time) *UserMemberUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *UserMemberUpdateOne) ClearExpiresAt() *UserMemberUpdateOne {
	_u.mutation.ClearExpiresAt()
	return _u
}

// SetLinkedByMemberID sets the "linked_by_member_id" field.
func (_u *UserMemberUpdateOne) SetLinkedByMemberID(v string) *UserMemberUpdateOne {
	_u.mutation.SetLinkedByMemberID(v)
	return _u
}

// SetNillableLinkedByMemberID sets the "linked_by_member_id" field if the given value is not nil.
func (_u *UserMemberUpdateOne) SetNillableLinkedByMemberID(v *string) *UserMemberUpdateOne {
	if v != nil {
		_u.SetLinkedByMemberID(*v)
	}
	return _u
}

// ClearLinkedByMemberID clears the value of the "linked_by_member_id" field.
func (_u *UserMemberUpdateOne) ClearLinkedByMemberID() *UserMemberUpdateOne {
	_u.mutation.ClearLinkedByMemberID()
	return _u
}

// SetLinkedAt sets the "linked_at" field.
func (_u *UserMemberUpdateOne) SetLinkedAt(v time.Time) *UserMemberUpdateOne {
	_u.mutation.SetLinkedAt(v)
	return _u
}

// SetNillableLinkedAt sets the "linked_at" field if the given value is not nil.
func (_u *UserMemberUpdateOne) SetNillableLinkedAt(v *time.Time) *UserMemberUpdateOne {
	if v != nil {
		_u.SetLinkedAt(*v)
	}
	return _u
}

// ClearLinkedAt clears the value of the "linked_at" field.
func (_u *UserMemberUpdateOne) ClearLinkedAt() *UserMemberUpdateOne {
	_u.mutation.ClearLinkedAt()
	return _u
}

// SetRevokedAt sets the "revoked_at" field.
func (_u *UserMemberUpdateOne) SetRevokedAt(v time.Time) *UserMemberUpdateOne {
	_u.mutation.SetRevokedAt(v)
	return _u
}

// SetNillableRevokedAt sets the "revoked_at" field if the given value is not nil.
func (_u *UserMemberUpdateOne) SetNillableRevokedAt(v *time.Time) *UserMemberUpdateOne {
	if v != nil {
		_u.SetRevokedAt(*v)
	}
	return _u
}

// ClearRevokedAt clears the value of the "revoked_at" field.
func (_u *UserMemberUpdateOne) ClearRevokedAt() *UserMemberUpdateOne {
	_u.mutation.ClearRevokedAt()
	return _u
}

// SetRevokedReason sets the "revoked_reason" field.
func (_u *UserMemberUpdateOne) SetRevokedReason(v string) *UserMemberUpdateOne {
	_u.mutation.SetRevokedReason(v)
	return _u
}

// SetNillableRevokedReason sets the "revoked_reason" field if the given value is not nil.
func (_u *UserMemberUpdateOne) SetNillableRevokedReason(v *string) *UserMemberUpdateOne {
	if v != nil {
		_u.SetRevokedReason(*v)
	}
	return _u
}

// ClearRevokedReason clears the value of the "revoked_reason" field.
func (_u *UserMemberUpdateOne) ClearRevokedReason() *UserMemberUpdateOne {
	_u.mutation.ClearRevokedReason()
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *UserMemberUpdateOne) SetMetadata(v map[string]interface{}) *UserMemberUpdateOne {
	_u.mutation.SetMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *UserMemberUpdateOne) ClearMetadata() *UserMemberUpdateOne {
	_u.mutation.ClearMetadata()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserMemberUpdateOne) SetUpdatedAt(v time.Time) *UserMemberUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *UserMemberUpdateOne) SetDeletedAt(v time.Time) *UserMemberUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *UserMemberUpdateOne) SetNillableDeletedAt(v *time.Time) *UserMemberUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *UserMemberUpdateOne) ClearDeletedAt() *UserMemberUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// Mutation returns the UserMemberMutation object of the builder.
func (_u *UserMemberUpdateOne) Mutation() *UserMemberMutation {
	return _u.mutation
}

// Where appends a list predicates to the UserMemberUpdate builder.
func (_u *UserMemberUpdateOne) Where(ps ...predicate.UserMember) *UserMemberUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UserMemberUpdateOne) Select(field string, fields ...string) *UserMemberUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated UserMember entity.
func (_u *UserMemberUpdateOne) Save(ctx context.Context) (*UserMember, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserMemberUpdateOne) SaveX(ctx context.Context) *UserMember {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UserMemberUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserMemberUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserMemberUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := usermember.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserMemberUpdateOne) check() error {
	if v, ok := _u.mutation.UserID(); ok {
		if err := usermember.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "UserMember.user_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MemberID(); ok {
		if err := usermember.MemberIDValidator(v); err != nil {
			return &ValidationError{Name: "member_id", err: fmt.Errorf(`ent: validator failed for field "UserMember.member_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SpaceID(); ok {
		if err := usermember.SpaceIDValidator(v); err != nil {
			return &ValidationError{Name: "space_id", err: fmt.Errorf(`ent: validator failed for field "UserMember.space_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RelationType(); ok {
		if err := usermember.RelationTypeValidator(v); err != nil {
			return &ValidationError{Name: "relation_type", err: fmt.Errorf(`ent: validator failed for field "UserMember.relation_type": %w`, err)}
		}
	}
	return nil
}

func (_u *UserMemberUpdateOne) sqlSave(ctx context.Context) (_node *UserMember, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(usermember.Table, usermember.Columns, sqlgraph.NewFieldSpec(usermember.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UserMember.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, usermember.FieldID)
		for _, f := range fields {
			if !usermember.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != usermember.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(usermember.FieldUserID, field.TypeString, value)
	}
	if value, ok := _u.mutation.MemberID(); ok {
		_spec.SetField(usermember.FieldMemberID, field.TypeString, value)
	}
	if value, ok := _u.mutation.SpaceID(); ok {
		_spec.SetField(usermember.FieldSpaceID, field.TypeString, value)
	}
	if value, ok := _u.mutation.RelationType(); ok {
		_spec.SetField(usermember.FieldRelationType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(usermember.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsPrimary(); ok {
		_spec.SetField(usermember.FieldIsPrimary, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(usermember.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(usermember.FieldExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LinkedByMemberID(); ok {
		_spec.SetField(usermember.FieldLinkedByMemberID, field.TypeString, value)
	}
	if _u.mutation.LinkedByMemberIDCleared() {
		_spec.ClearField(usermember.FieldLinkedByMemberID, field.TypeString)
	}
	if value, ok := _u.mutation.LinkedAt(); ok {
		_spec.SetField(usermember.FieldLinkedAt, field.TypeTime, value)
	}
	if _u.mutation.LinkedAtCleared() {
		_spec.ClearField(usermember.FieldLinkedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.RevokedAt(); ok {
		_spec.SetField(usermember.FieldRevokedAt, field.TypeTime, value)
	}
	if _u.mutation.RevokedAtCleared() {
		_spec.ClearField(usermember.FieldRevokedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.RevokedReason(); ok {
		_spec.SetField(usermember.FieldRevokedReason, field.TypeString, value)
	}
	if _u.mutation.RevokedReasonCleared() {
		_spec.ClearField(usermember.FieldRevokedReason, field.TypeString)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(usermember.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(usermember.FieldMetadata, field.TypeJSON)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(usermember.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(usermember.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(usermember.FieldDeletedAt, field.TypeTime)
	}
	_node = &UserMember{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{usermember.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
