// Code generated by ent, DO NOT EDIT.

package appdatamodel

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the appdatamodel type in the database.
	Label = "app_data_model"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldSpaceID holds the string denoting the space_id field in the database.
	FieldSpaceID = "space_id"
	// FieldKey holds the string denoting the key field in the database.
	FieldKey = "key"
	// FieldDisplayName holds the string denoting the display_name field in the database.
	FieldDisplayName = "display_name"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldSource holds the string denoting the source field in the database.
	FieldSource = "source"
	// FieldOwnerPluginKey holds the string denoting the owner_plugin_key field in the database.
	FieldOwnerPluginKey = "owner_plugin_key"
	// FieldDeclaredResourceKey holds the string denoting the declared_resource_key field in the database.
	FieldDeclaredResourceKey = "declared_resource_key"
	// FieldOwnerPluginType holds the string denoting the owner_plugin_type field in the database.
	FieldOwnerPluginType = "owner_plugin_type"
	// FieldAppID holds the string denoting the app_id field in the database.
	FieldAppID = "app_id"
	// FieldTrustBundleID holds the string denoting the trust_bundle_id field in the database.
	FieldTrustBundleID = "trust_bundle_id"
	// FieldOwnerModuleKey holds the string denoting the owner_module_key field in the database.
	FieldOwnerModuleKey = "owner_module_key"
	// FieldTenantScoped holds the string denoting the tenant_scoped field in the database.
	FieldTenantScoped = "tenant_scoped"
	// FieldAuditEnforcement holds the string denoting the audit_enforcement field in the database.
	FieldAuditEnforcement = "audit_enforcement"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldSchema holds the string denoting the schema field in the database.
	FieldSchema = "schema"
	// FieldMetadata holds the string denoting the metadata field in the database.
	FieldMetadata = "metadata"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// Table holds the table name of the appdatamodel in the database.
	Table = "app_data_models"
)

// Columns holds all SQL columns for appdatamodel fields.
var Columns = []string{
	FieldID,
	FieldSpaceID,
	FieldKey,
	FieldDisplayName,
	FieldDescription,
	FieldSource,
	FieldOwnerPluginKey,
	FieldDeclaredResourceKey,
	FieldOwnerPluginType,
	FieldAppID,
	FieldTrustBundleID,
	FieldOwnerModuleKey,
	FieldTenantScoped,
	FieldAuditEnforcement,
	FieldStatus,
	FieldSchema,
	FieldMetadata,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDeletedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// SpaceIDValidator is a validator for the "space_id" field. It is called by the builders before save.
	SpaceIDValidator func(string) error
	// KeyValidator is a validator for the "key" field. It is called by the builders before save.
	KeyValidator func(string) error
	// DisplayNameValidator is a validator for the "display_name" field. It is called by the builders before save.
	DisplayNameValidator func(string) error
	// DefaultSource holds the default value on creation for the "source" field.
	DefaultSource string
	// DefaultTenantScoped holds the default value on creation for the "tenant_scoped" field.
	DefaultTenantScoped bool
	// DefaultAuditEnforcement holds the default value on creation for the "audit_enforcement" field.
	DefaultAuditEnforcement string
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(string) error
)

// OrderOption defines the ordering options for the AppDataModel queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// BySpaceID orders the results by the space_id field.
func BySpaceID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSpaceID, opts...).ToFunc()
}

// ByKey orders the results by the key field.
func ByKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldKey, opts...).ToFunc()
}

// ByDisplayName orders the results by the display_name field.
func ByDisplayName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDisplayName, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// BySource orders the results by the source field.
func BySource(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSource, opts...).ToFunc()
}

// ByOwnerPluginKey orders the results by the owner_plugin_key field.
func ByOwnerPluginKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOwnerPluginKey, opts...).ToFunc()
}

// ByDeclaredResourceKey orders the results by the declared_resource_key field.
func ByDeclaredResourceKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeclaredResourceKey, opts...).ToFunc()
}

// ByOwnerPluginType orders the results by the owner_plugin_type field.
func ByOwnerPluginType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOwnerPluginType, opts...).ToFunc()
}

// ByAppID orders the results by the app_id field.
func ByAppID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAppID, opts...).ToFunc()
}

// ByTrustBundleID orders the results by the trust_bundle_id field.
func ByTrustBundleID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTrustBundleID, opts...).ToFunc()
}

// ByOwnerModuleKey orders the results by the owner_module_key field.
func ByOwnerModuleKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOwnerModuleKey, opts...).ToFunc()
}

// ByTenantScoped orders the results by the tenant_scoped field.
func ByTenantScoped(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTenantScoped, opts...).ToFunc()
}

// ByAuditEnforcement orders the results by the audit_enforcement field.
func ByAuditEnforcement(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAuditEnforcement, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByDeletedAt orders the results by the deleted_at field.
func ByDeletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedAt, opts...).ToFunc()
}
