// Code generated by ent, DO NOT EDIT.

package appdatamodel

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/plystra/core/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.AppDataModel {
	return predicate.AppDataModel(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.AppDataModel {
	return predicate.AppDataModel(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.AppDataModel {
	return predicate.AppDataModel(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.AppDataModel {
	return predicate.AppDataModel(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.AppDataModel {
	return predicate.AppDataModel(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.AppDataModel {
	return predicate.AppDataModel(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.AppDataModel {
	return predicate.AppDataModel(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.AppDataModel {
	return predicate.AppDataModel(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.AppDataModel {
	return predicate.AppDataModel(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.AppDataModel {
	return predicate.AppDataModel(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.AppDataModel {
	return predicate.AppDataModel(sql.FieldContainsFold(FieldID, id))
}

// SpaceID applies equality check predicate on the "space_id" field. It's identical to SpaceIDEQ.
func SpaceID(v string) predicate.AppDataModel {
	return predicate.AppDataModel(sql.FieldEQ(FieldSpaceID, v))
}

// Key applies equality check predicate on the "key" field. It's identical to KeyEQ.
func Key(v string) predicate.AppDataModel {
	return predicate.AppDataModel(sql.FieldEQ(FieldKey, v))
}

// DisplayName applies equality check predicate on the "display_name" field. It's identical to DisplayNameEQ.
func DisplayName(v string) predicate.AppDataModel {
	return predicate.AppDataModel(sql.FieldEQ(FieldDisplayName, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.AppDataModel {
	return predicate.AppDataModel(sql.FieldEQ(FieldDescription, v))
}

// Source applies equality check predicate on the "source" field. It's identical to SourceEQ.
func Source(v string) predicate.AppDataModel {
	return predicate.AppDataModel(sql.FieldEQ(FieldSource, v))
}

// OwnerPluginKey applies equality check predicate on the "owner_plugin_key" field. It's identical to OwnerPluginKeyEQ.
func OwnerPluginKey(v string) predicate.AppDataModel {
	return predicate.AppDataModel(sql.FieldEQ(FieldOwnerPluginKey, v))
}

// DeclaredResourceKey applies equality check predicate on the "declared_resource_key" field. It's identical to DeclaredResourceKeyEQ.
func DeclaredResourceKey(v string) predicate.AppDataModel {
	return predicate.AppDataModel(sql.FieldEQ(FieldDeclaredResourceKey, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.AppDataModel {
	return predicate.AppDataModel(sql.FieldEQ(FieldStatus, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.AppDataModel {
	return predicate.AppDataModel(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.AppDataModel {
	return predicate.AppDataModel(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.AppDataModel {
	return predicate.AppDataModel(sql.FieldEQ(FieldDeletedAt, v))
}

// SpaceIDEQ applies the EQ predicate on the "space_id" field.
func SpaceIDEQ(v string) predicate.AppDataModel {
	return predicate.AppDataModel(sql.FieldEQ(FieldSpaceID, v))
}

// SpaceIDNEQ applies the NEQ predicate on the "space_id" field.
func SpaceIDNEQ(v string) predicate.AppDataModel {
	return predicate.AppDataModel(sql.FieldNEQ(FieldSpaceID, v))
}

// SpaceIDIn applies the In predicate on the "space_id" field.
func SpaceIDIn(vs ...string) predicate.AppDataModel {
	return predicate.AppDataModel(sql.FieldIn(FieldSpaceID, vs...))
}

// SpaceIDNotIn applies the NotIn predicate on the "space_id" field.
func SpaceIDNotIn(vs ...string) predicate.AppDataModel {
	return predicate.AppDataModel(sql.FieldNotIn(FieldSpaceID, vs...))
}

// SpaceIDGT applies the GT predicate on the "space_id" field.
func SpaceIDGT(v string) predicate.AppDataModel {
	return predicate.AppDataModel(sql.FieldGT(FieldSpaceID, v))
}

// SpaceIDGTE applies the GTE predicate on the "space_id" field.
func SpaceIDGTE(v string) predicate.AppDataModel {
	return predicate.AppDataModel(sql.FieldGTE(FieldSpaceID, v))
}

// SpaceIDLT applies the LT predicate on the "space_id" field.
func SpaceIDLT(v string) predicate.AppDataModel {
	return predicate.AppDataModel(sql.FieldLT(FieldSpaceID, v))
}

// SpaceIDLTE applies the LTE predicate on the "space_id" field.
func SpaceIDLTE(v string) predicate.AppDataModel {
	return predicate.AppDataModel(sql.FieldLTE(FieldSpaceID, v))
}

// SpaceIDContains applies the Contains predicate on the "space_id" field.
func SpaceIDContains(v string) predicate.AppDataModel {
	return predicate.AppDataModel(sql.FieldContains(FieldSpaceID, v))
}

// SpaceIDHasPrefix applies the HasPrefix predicate on the "space_id" field.
func SpaceIDHasPrefix(v string) predicate.AppDataModel {
	return predicate.AppDataModel(sql.FieldHasPrefix(FieldSpaceID, v))
}

// SpaceIDHasSuffix applies the HasSuffix predicate on the "space_id" field.
func SpaceIDHasSuffix(v string) predicate.AppDataModel {
	return predicate.AppDataModel(sql.FieldHasSuffix(FieldSpaceID, v))
}

// SpaceIDEqualFold applies the EqualFold predicate on the "space_id" field.
func SpaceIDEqualFold(v string) predicate.AppDataModel {
	return predicate.AppDataModel(sql.FieldEqualFold(FieldSpaceID, v))
}

// SpaceIDContainsFold applies the ContainsFold predicate on the "space_id" field.
func SpaceIDContainsFold(v string) predicate.AppDataModel {
	return predicate.AppDataModel(sql.FieldContainsFold(FieldSpaceID, v))
}

// KeyEQ applies the EQ predicate on the "key" field.
func KeyEQ(v string) predicate.AppDataModel {
	return predicate.AppDataModel(sql.FieldEQ(FieldKey, v))
}

// KeyNEQ applies the NEQ predicate on the "key" field.
func KeyNEQ(v string) predicate.AppDataModel {
	return predicate.AppDataModel(sql.FieldNEQ(FieldKey, v))
}

// KeyIn applies the In predicate on the "key" field.
func KeyIn(vs ...string) predicate.AppDataModel {
	return predicate.AppDataModel(sql.FieldIn(FieldKey, vs...))
}

// KeyNotIn applies the NotIn predicate on the "key" field.
func KeyNotIn(vs ...string) predicate.AppDataModel {
	return predicate.AppDataModel(sql.FieldNotIn(FieldKey, vs...))
}

// KeyGT applies the GT predicate on the "key" field.
func KeyGT(v string) predicate.AppDataModel {
	return predicate.AppDataModel(sql.FieldGT(FieldKey, v))
}

// KeyGTE applies the GTE predicate on the "key" field.
func KeyGTE(v string) predicate.AppDataModel {
	return predicate.AppDataModel(sql.FieldGTE(FieldKey, v))
}

// KeyLT applies the LT predicate on the "key" field.
func KeyLT(v string) predicate.AppDataModel {
	return predicate.AppDataModel(sql.FieldLT(FieldKey, v))
}

// KeyLTE applies the LTE predicate on the "key" field.
func KeyLTE(v string) predicate.AppDataModel {
	return predicate.AppDataModel(sql.FieldLTE(FieldKey, v))
}

// KeyContains applies the Contains predicate on the "key" field.
func KeyContains(v string) predicate.AppDataModel {
	return predicate.AppDataModel(sql.FieldContains(FieldKey, v))
}

// KeyHasPrefix applies the HasPrefix predicate on the "key" field.
func KeyHasPrefix(v string) predicate.AppDataModel {
	return predicate.AppDataModel(sql.FieldHasPrefix(FieldKey, v))
}

// KeyHasSuffix applies the HasSuffix predicate on the "key" field.
func KeyHasSuffix(v string) predicate.AppDataModel {
	return predicate.AppDataModel(sql.FieldHasSuffix(FieldKey, v))
}

// KeyEqualFold applies the EqualFold predicate on the "key" field.
func KeyEqualFold(v string) predicate.AppDataModel {
	return predicate.AppDataModel(sql.FieldEqualFold(FieldKey, v))
}

// KeyContainsFold applies the ContainsFold predicate on the "key" field.
func KeyContainsFold(v string) predicate.AppDataModel {
	return predicate.AppDataModel(sql.FieldContainsFold(FieldKey, v))
}

// DisplayNameEQ applies the EQ predicate on the "display_name" field.
func DisplayNameEQ(v string) predicate.AppDataModel {
	return predicate.AppDataModel(sql.FieldEQ(FieldDisplayName, v))
}

// DisplayNameNEQ applies the NEQ predicate on the "display_name" field.
func DisplayNameNEQ(v string) predicate.AppDataModel {
	return predicate.AppDataModel(sql.FieldNEQ(FieldDisplayName, v))
}

// DisplayNameIn applies the In predicate on the "display_name" field.
func DisplayNameIn(vs ...string) predicate.AppDataModel {
	return predicate.AppDataModel(sql.FieldIn(FieldDisplayName, vs...))
}

// DisplayNameNotIn applies the NotIn predicate on the "display_name" field.
func DisplayNameNotIn(vs ...string) predicate.AppDataModel {
	return predicate.AppDataModel(sql.FieldNotIn(FieldDisplayName, vs...))
}

// DisplayNameGT applies the GT predicate on the "display_name" field.
func DisplayNameGT(v string) predicate.AppDataModel {
	return predicate.AppDataModel(sql.FieldGT(FieldDisplayName, v))
}

// DisplayNameGTE applies the GTE predicate on the "display_name" field.
func DisplayNameGTE(v string) predicate.AppDataModel {
	return predicate.AppDataModel(sql.FieldGTE(FieldDisplayName, v))
}

// DisplayNameLT applies the LT predicate on the "display_name" field.
func DisplayNameLT(v string) predicate.AppDataModel {
	return predicate.AppDataModel(sql.FieldLT(FieldDisplayName, v))
}

// DisplayNameLTE applies the LTE predicate on the "display_name" field.
func DisplayNameLTE(v string) predicate.AppDataModel {
	return predicate.AppDataModel(sql.FieldLTE(FieldDisplayName, v))
}

// DisplayNameContains applies the Contains predicate on the "display_name" field.
func DisplayNameContains(v string) predicate.AppDataModel {
	return predicate.AppDataModel(sql.FieldContains(FieldDisplayName, v))
}

// DisplayNameHasPrefix applies the HasPrefix predicate on the "display_name" field.
func DisplayNameHasPrefix(v string) predicate.AppDataModel {
	return predicate.AppDataModel(sql.FieldHasPrefix(FieldDisplayName, v))
}

// DisplayNameHasSuffix applies the HasSuffix predicate on the "display_name" field.
func DisplayNameHasSuffix(v string) predicate.AppDataModel {
	return predicate.AppDataModel(sql.FieldHasSuffix(FieldDisplayName, v))
}

// DisplayNameEqualFold applies the EqualFold predicate on the "display_name" field.
func DisplayNameEqualFold(v string) predicate.AppDataModel {
	return predicate.AppDataModel(sql.FieldEqualFold(FieldDisplayName, v))
}

// DisplayNameContainsFold applies the ContainsFold predicate on the "display_name" field.
func DisplayNameContainsFold(v string) predicate.AppDataModel {
	return predicate.AppDataModel(sql.FieldContainsFold(FieldDisplayName, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.AppDataModel {
	return predicate.AppDataModel(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.AppDataModel {
	return predicate.AppDataModel(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.AppDataModel {
	return predicate.AppDataModel(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.AppDataModel {
	return predicate.AppDataModel(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.AppDataModel {
	return predicate.AppDataModel(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.AppDataModel {
	return predicate.AppDataModel(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.AppDataModel {
	return predicate.AppDataModel(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.AppDataModel {
	return predicate.AppDataModel(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.AppDataModel {
	return predicate.AppDataModel(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.AppDataModel {
	return predicate.AppDataModel(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.AppDataModel {
	return predicate.AppDataModel(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionIsNil applies the IsNil predicate on the "description" field.
func DescriptionIsNil() predicate.AppDataModel {
	return predicate.AppDataModel(sql.FieldIsNull(FieldDescription))
}

// DescriptionNotNil applies the NotNil predicate on the "description" field.
func DescriptionNotNil() predicate.AppDataModel {
	return predicate.AppDataModel(sql.FieldNotNull(FieldDescription))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.AppDataModel {
	return predicate.AppDataModel(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.AppDataModel {
	return predicate.AppDataModel(sql.FieldContainsFold(FieldDescription, v))
}

// SourceEQ applies the EQ predicate on the "source" field.
func SourceEQ(v string) predicate.AppDataModel {
	return predicate.AppDataModel(sql.FieldEQ(FieldSource, v))
}

// SourceNEQ applies the NEQ predicate on the "source" field.
func SourceNEQ(v string) predicate.AppDataModel {
	return predicate.AppDataModel(sql.FieldNEQ(FieldSource, v))
}

// SourceIn applies the In predicate on the "source" field.
func SourceIn(vs ...string) predicate.AppDataModel {
	return predicate.AppDataModel(sql.FieldIn(FieldSource, vs...))
}

// SourceNotIn applies the NotIn predicate on the "source" field.
func SourceNotIn(vs ...string) predicate.AppDataModel {
	return predicate.AppDataModel(sql.FieldNotIn(FieldSource, vs...))
}

// SourceGT applies the GT predicate on the "source" field.
func SourceGT(v string) predicate.AppDataModel {
	return predicate.AppDataModel(sql.FieldGT(FieldSource, v))
}

// SourceGTE applies the GTE predicate on the "source" field.
func SourceGTE(v string) predicate.AppDataModel {
	return predicate.AppDataModel(sql.FieldGTE(FieldSource, v))
}

// SourceLT applies the LT predicate on the "source" field.
func SourceLT(v string) predicate.AppDataModel {
	return predicate.AppDataModel(sql.FieldLT(FieldSource, v))
}

// SourceLTE applies the LTE predicate on the "source" field.
func SourceLTE(v string) predicate.AppDataModel {
	return predicate.AppDataModel(sql.FieldLTE(FieldSource, v))
}

// SourceContains applies the Contains predicate on the "source" field.
func SourceContains(v string) predicate.AppDataModel {
	return predicate.AppDataModel(sql.FieldContains(FieldSource, v))
}

// SourceHasPrefix applies the HasPrefix predicate on the "source" field.
func SourceHasPrefix(v string) predicate.AppDataModel {
	return predicate.AppDataModel(sql.FieldHasPrefix(FieldSource, v))
}

// SourceHasSuffix applies the HasSuffix predicate on the "source" field.
func SourceHasSuffix(v string) predicate.AppDataModel {
	return predicate.AppDataModel(sql.FieldHasSuffix(FieldSource, v))
}

// SourceEqualFold applies the EqualFold predicate on the "source" field.
func SourceEqualFold(v string) predicate.AppDataModel {
	return predicate.AppDataModel(sql.FieldEqualFold(FieldSource, v))
}

// SourceContainsFold applies the ContainsFold predicate on the "source" field.
func SourceContainsFold(v string) predicate.AppDataModel {
	return predicate.AppDataModel(sql.FieldContainsFold(FieldSource, v))
}

// OwnerPluginKeyEQ applies the EQ predicate on the "owner_plugin_key" field.
func OwnerPluginKeyEQ(v string) predicate.AppDataModel {
	return predicate.AppDataModel(sql.FieldEQ(FieldOwnerPluginKey, v))
}

// OwnerPluginKeyNEQ applies the NEQ predicate on the "owner_plugin_key" field.
func OwnerPluginKeyNEQ(v string) predicate.AppDataModel {
	return predicate.AppDataModel(sql.FieldNEQ(FieldOwnerPluginKey, v))
}

// OwnerPluginKeyIn applies the In predicate on the "owner_plugin_key" field.
func OwnerPluginKeyIn(vs ...string) predicate.AppDataModel {
	return predicate.AppDataModel(sql.FieldIn(FieldOwnerPluginKey, vs...))
}

// OwnerPluginKeyNotIn applies the NotIn predicate on the "owner_plugin_key" field.
func OwnerPluginKeyNotIn(vs ...string) predicate.AppDataModel {
	return predicate.AppDataModel(sql.FieldNotIn(FieldOwnerPluginKey, vs...))
}

// OwnerPluginKeyGT applies the GT predicate on the "owner_plugin_key" field.
func OwnerPluginKeyGT(v string) predicate.AppDataModel {
	return predicate.AppDataModel(sql.FieldGT(FieldOwnerPluginKey, v))
}

// OwnerPluginKeyGTE applies the GTE predicate on the "owner_plugin_key" field.
func OwnerPluginKeyGTE(v string) predicate.AppDataModel {
	return predicate.AppDataModel(sql.FieldGTE(FieldOwnerPluginKey, v))
}

// OwnerPluginKeyLT applies the LT predicate on the "owner_plugin_key" field.
func OwnerPluginKeyLT(v string) predicate.AppDataModel {
	return predicate.AppDataModel(sql.FieldLT(FieldOwnerPluginKey, v))
}

// OwnerPluginKeyLTE applies the LTE predicate on the "owner_plugin_key" field.
func OwnerPluginKeyLTE(v string) predicate.AppDataModel {
	return predicate.AppDataModel(sql.FieldLTE(FieldOwnerPluginKey, v))
}

// OwnerPluginKeyContains applies the Contains predicate on the "owner_plugin_key" field.
func OwnerPluginKeyContains(v string) predicate.AppDataModel {
	return predicate.AppDataModel(sql.FieldContains(FieldOwnerPluginKey, v))
}

// OwnerPluginKeyHasPrefix applies the HasPrefix predicate on the "owner_plugin_key" field.
func OwnerPluginKeyHasPrefix(v string) predicate.AppDataModel {
	return predicate.AppDataModel(sql.FieldHasPrefix(FieldOwnerPluginKey, v))
}

// OwnerPluginKeyHasSuffix applies the HasSuffix predicate on the "owner_plugin_key" field.
func OwnerPluginKeyHasSuffix(v string) predicate.AppDataModel {
	return predicate.AppDataModel(sql.FieldHasSuffix(FieldOwnerPluginKey, v))
}

// OwnerPluginKeyIsNil applies the IsNil predicate on the "owner_plugin_key" field.
func OwnerPluginKeyIsNil() predicate.AppDataModel {
	return predicate.AppDataModel(sql.FieldIsNull(FieldOwnerPluginKey))
}

// OwnerPluginKeyNotNil applies the NotNil predicate on the "owner_plugin_key" field.
func OwnerPluginKeyNotNil() predicate.AppDataModel {
	return predicate.AppDataModel(sql.FieldNotNull(FieldOwnerPluginKey))
}

// OwnerPluginKeyEqualFold applies the EqualFold predicate on the "owner_plugin_key" field.
func OwnerPluginKeyEqualFold(v string) predicate.AppDataModel {
	return predicate.AppDataModel(sql.FieldEqualFold(FieldOwnerPluginKey, v))
}

// OwnerPluginKeyContainsFold applies the ContainsFold predicate on the "owner_plugin_key" field.
func OwnerPluginKeyContainsFold(v string) predicate.AppDataModel {
	return predicate.AppDataModel(sql.FieldContainsFold(FieldOwnerPluginKey, v))
}

// DeclaredResourceKeyEQ applies the EQ predicate on the "declared_resource_key" field.
func DeclaredResourceKeyEQ(v string) predicate.AppDataModel {
	return predicate.AppDataModel(sql.FieldEQ(FieldDeclaredResourceKey, v))
}

// DeclaredResourceKeyNEQ applies the NEQ predicate on the "declared_resource_key" field.
func DeclaredResourceKeyNEQ(v string) predicate.AppDataModel {
	return predicate.AppDataModel(sql.FieldNEQ(FieldDeclaredResourceKey, v))
}

// DeclaredResourceKeyIn applies the In predicate on the "declared_resource_key" field.
func DeclaredResourceKeyIn(vs ...string) predicate.AppDataModel {
	return predicate.AppDataModel(sql.FieldIn(FieldDeclaredResourceKey, vs...))
}

// DeclaredResourceKeyNotIn applies the NotIn predicate on the "declared_resource_key" field.
func DeclaredResourceKeyNotIn(vs ...string) predicate.AppDataModel {
	return predicate.AppDataModel(sql.FieldNotIn(FieldDeclaredResourceKey, vs...))
}

// DeclaredResourceKeyGT applies the GT predicate on the "declared_resource_key" field.
func DeclaredResourceKeyGT(v string) predicate.AppDataModel {
	return predicate.AppDataModel(sql.FieldGT(FieldDeclaredResourceKey, v))
}

// DeclaredResourceKeyGTE applies the GTE predicate on the "declared_resource_key" field.
func DeclaredResourceKeyGTE(v string) predicate.AppDataModel {
	return predicate.AppDataModel(sql.FieldGTE(FieldDeclaredResourceKey, v))
}

// DeclaredResourceKeyLT applies the LT predicate on the "declared_resource_key" field.
func DeclaredResourceKeyLT(v string) predicate.AppDataModel {
	return predicate.AppDataModel(sql.FieldLT(FieldDeclaredResourceKey, v))
}

// DeclaredResourceKeyLTE applies the LTE predicate on the "declared_resource_key" field.
func DeclaredResourceKeyLTE(v string) predicate.AppDataModel {
	return predicate.AppDataModel(sql.FieldLTE(FieldDeclaredResourceKey, v))
}

// DeclaredResourceKeyContains applies the Contains predicate on the "declared_resource_key" field.
func DeclaredResourceKeyContains(v string) predicate.AppDataModel {
	return predicate.AppDataModel(sql.FieldContains(FieldDeclaredResourceKey, v))
}

// DeclaredResourceKeyHasPrefix applies the HasPrefix predicate on the "declared_resource_key" field.
func DeclaredResourceKeyHasPrefix(v string) predicate.AppDataModel {
	return predicate.AppDataModel(sql.FieldHasPrefix(FieldDeclaredResourceKey, v))
}

// DeclaredResourceKeyHasSuffix applies the HasSuffix predicate on the "declared_resource_key" field.
func DeclaredResourceKeyHasSuffix(v string) predicate.AppDataModel {
	return predicate.AppDataModel(sql.FieldHasSuffix(FieldDeclaredResourceKey, v))
}

// DeclaredResourceKeyIsNil applies the IsNil predicate on the "declared_resource_key" field.
func DeclaredResourceKeyIsNil() predicate.AppDataModel {
	return predicate.AppDataModel(sql.FieldIsNull(FieldDeclaredResourceKey))
}

// DeclaredResourceKeyNotNil applies the NotNil predicate on the "declared_resource_key" field.
func DeclaredResourceKeyNotNil() predicate.AppDataModel {
	return predicate.AppDataModel(sql.FieldNotNull(FieldDeclaredResourceKey))
}

// DeclaredResourceKeyEqualFold applies the EqualFold predicate on the "declared_resource_key" field.
func DeclaredResourceKeyEqualFold(v string) predicate.AppDataModel {
	return predicate.AppDataModel(sql.FieldEqualFold(FieldDeclaredResourceKey, v))
}

// DeclaredResourceKeyContainsFold applies the ContainsFold predicate on the "declared_resource_key" field.
func DeclaredResourceKeyContainsFold(v string) predicate.AppDataModel {
	return predicate.AppDataModel(sql.FieldContainsFold(FieldDeclaredResourceKey, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.AppDataModel {
	return predicate.AppDataModel(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.AppDataModel {
	return predicate.AppDataModel(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.AppDataModel {
	return predicate.AppDataModel(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.AppDataModel {
	return predicate.AppDataModel(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.AppDataModel {
	return predicate.AppDataModel(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.AppDataModel {
	return predicate.AppDataModel(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.AppDataModel {
	return predicate.AppDataModel(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.AppDataModel {
	return predicate.AppDataModel(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.AppDataModel {
	return predicate.AppDataModel(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.AppDataModel {
	return predicate.AppDataModel(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.AppDataModel {
	return predicate.AppDataModel(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.AppDataModel {
	return predicate.AppDataModel(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.AppDataModel {
	return predicate.AppDataModel(sql.FieldContainsFold(FieldStatus, v))
}

// MetadataIsNil applies the IsNil predicate on the "metadata" field.
func MetadataIsNil() predicate.AppDataModel {
	return predicate.AppDataModel(sql.FieldIsNull(FieldMetadata))
}

// MetadataNotNil applies the NotNil predicate on the "metadata" field.
func MetadataNotNil() predicate.AppDataModel {
	return predicate.AppDataModel(sql.FieldNotNull(FieldMetadata))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.AppDataModel {
	return predicate.AppDataModel(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.AppDataModel {
	return predicate.AppDataModel(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.AppDataModel {
	return predicate.AppDataModel(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.AppDataModel {
	return predicate.AppDataModel(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.AppDataModel {
	return predicate.AppDataModel(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.AppDataModel {
	return predicate.AppDataModel(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.AppDataModel {
	return predicate.AppDataModel(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.AppDataModel {
	return predicate.AppDataModel(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.AppDataModel {
	return predicate.AppDataModel(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.AppDataModel {
	return predicate.AppDataModel(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.AppDataModel {
	return predicate.AppDataModel(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.AppDataModel {
	return predicate.AppDataModel(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.AppDataModel {
	return predicate.AppDataModel(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.AppDataModel {
	return predicate.AppDataModel(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.AppDataModel {
	return predicate.AppDataModel(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.AppDataModel {
	return predicate.AppDataModel(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.AppDataModel {
	return predicate.AppDataModel(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.AppDataModel {
	return predicate.AppDataModel(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.AppDataModel {
	return predicate.AppDataModel(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.AppDataModel {
	return predicate.AppDataModel(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.AppDataModel {
	return predicate.AppDataModel(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.AppDataModel {
	return predicate.AppDataModel(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.AppDataModel {
	return predicate.AppDataModel(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.AppDataModel {
	return predicate.AppDataModel(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.AppDataModel {
	return predicate.AppDataModel(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.AppDataModel {
	return predicate.AppDataModel(sql.FieldNotNull(FieldDeletedAt))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AppDataModel) predicate.AppDataModel {
	return predicate.AppDataModel(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AppDataModel) predicate.AppDataModel {
	return predicate.AppDataModel(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AppDataModel) predicate.AppDataModel {
	return predicate.AppDataModel(sql.NotPredicates(p))
}
